#+TITLE: Where's the Halloween Towns!?
#+DATE: 2022-10-20T21:06:01-07:00
#+DRAFT: false
#+DESCRIPTION: Every year for the past three at least, Fiesta does a halloween theme every where, but not this year...maybe?
#+TAGS[]: fiesta news
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Hi hi everypeep 👋🏻

Is everyone having a good and scary halloween time? Got your favorite beverages in blood bags, some good spaghetti brains, and....the scariest of it all, candy corn? For me Halloween is one of my favorite times of year! One of the things a really like about [[http://fiesta.gamingo.com][Fiesta Online]] during this time of year is the spooky make over that comes to all the major towns. In the past years this would usually come to the game in the first or second update of October. However, it is now almost Halloween proper, just 11 days of the day I'm writing this, and still no sign of my spook-tacular towns 🥲
* No news is good news?
So, naturally, someone /might/ think, well golly Yayoi you just gotta be patient, after all they haven't said their not doing Halloween shinanigins, right? I mean sure, that's true, but it isn't like they haven't mentioned Halloween at all. Earlier this week the Fiesta Online team posted [[https://fiesta.gamigo.com/us/news/offer_boo_a_scaretastic_sale_10201122-204][this article]] on their site's official news section. The mention Jack-O Pumpkin, who has been a staple of events surrounding the Halloween update, but what is the actual news? *The scarier-than-every Halloween sale* yay! They talk about getting Halloween-themed costumes, masks, tails, and other stuff for 30% off in the item store, but no mention of anything else related to Jack-O's "favorite time of year" I know, they still haven't mentioned that they aren't doing anything, but this seems like they would rather just throw up a sale, maybe make some extra money and have the whole holiday done and dusted!
* What has happened to Halloween?
This is really my favorite time of year, always has been. I love any excuse to celebrate things scary, creepy, and even a bit gory (just don't tell my friends 😉), yet it seems /everyone/ is just skipping over Halloween. I mean, I guess I get it, from a marking standpoint, Halloween, Thanksgiving (US), and Christmas are all right in line and the last two are very major holidays, and, with both Halloween and Christmas being about giving something out and getting something back, it makes since for companies like Gamigo to pour more energy into Christmas than Halloween. Doesn't mean I have to like it though 😤
* I could be wrong
Maybe, by the time this goes up and/or the time you read it, I've been proven wrong and Gamigo did, in fact, release the Halloween content I know and love. I would love for that to be the guess. Please prove me wrong here Gamigo 🙏🏻 However, I'm not holding my breath just yet.

Praying for Halloween Content,
-Yayoi
