#+TITLE: Covid Visit!
#+DATE: 2023-05-15T20:04:39-07:00
#+DRAFT: false
#+DESCRIPTION: COVID-19 is still here and I found out the hard way!
#+TAGS[]: news personal
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: COVID-19 has come around and now I have a lot of time!

I'm hoping this isn't going to be a very long entry, but we won't know that until I have written the whole thing 😝. I'm not in a very serious mood, though maybe I should be. On Saturday, 13 May, I was very tired and stayed in bed most of the time. I let my parents know and I was visited with a COVID-19 test. I took the test and I tested positive for COVID in 2023!

* About my COVID Case
I'll get this out of the way really quick. If anyone reading this is worried, you don't have to be. My case is very mild and I have been recovering rather quickly. I am keeping myself isolated and all is well so far. I will be unable to work for the next four days, but this is a procedure from the company due to the nature of my job.
* The Good Part
Believe it or not, this isn't all bad. I've been feeling overworked and burnt out lately. I never have time for self-care and hobbies. This includes updating this website. I have time for this now and I have been playing games and drawing.

In fact, I'm hoping to add another picture to my [[{{% ref "/gallery/creations" %}}][Creations]] very soon. This one is taking a little long because I was not able to be up very long during the weekend, but I should have time to work on it a bit more soon, though I am working through some needed training and still doing school work as I don't need to leave for that.
* For the future
Yesterday I started Portal again, I noticed something I haven't noticed before. Portal is my favorite game and I'm still learning new things. I haven't decided to, but I /might/ add some Portal achievement guides or walkthroughs. Again, I'm not sure I will want to do this, but at least I warned you if I do decide to. I may also look into other walkthroughs and guides to add while I'm out. I know this isn't much of a plan yet, but I just wanted to through this in here.
