#+TITLE: Commissions are OPEN!!
#+DATE: 2023-08-24T15:00:57-07:00
#+DRAFT: false
#+DESCRIPTION: Some stuff happened this week! One BEEG thing is that I am opening commissions!
#+TAGS[]: site news announcement
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: This week was not as small as last week, but the updates are still few. One thing is that I've been doing a lot of thinking and I have decided to open up commissions! Other than that, and, as far as this site goes, I have also decided not to wait until I have completed No Man's Sky to write about it. You can consider this my first impressions of the game. As I said, I am planning on writing a full review once I have completed the main story missions, but I didn't want to wait that long because I really like the game!

This week was not as small as last week, but the updates are still few. One thing is that I've been doing a lot of thinking and I have decided to open up commissions! Other than that, and, as far as this site goes, I have also decided not to wait until I have completed [[{{%ref "reviews/no-mans-sky.org" %}}][No Man's Sky]] to write about it. You can consider this my first impressions of the game. As I said, I am planning on writing a full review once I have completed the main story missions, but I didn't want to wait that long because I really like the game!

* About Commissions!
After the success of my last commission, I have decided that I would like to do more of them. Once again I have to thank [[https://www.twitch.tv/jadeeyeddemoness][my friend]] for giving me the opportunity to work on commission. I have a [[https://forums.onigirionegai.info/viewtopic.php?t=24][forum post]] up where you can let me know you are interested in a commission. We can even start work shopping the idea in that thread or I'll DM you. If you don't want to register on the forums, that's fine, you can also [[mailto:yayoi_chi@icloud.com?subject=Commission][e-mail me]] or contact me using the information posted at the bottom of every page to get a hold of me. At the moment pricing is done per project, but I will estimate everything for you! Thank you in advance!
* First, first impressions!
I have also written my first impressions of [[{{% ref "reviews/no-mans-sky.org" %}}][No Man's Sky]]. I wanted to, once again, say that these are just the first impressions, but I /did/ put a star ranking up. I will write a full review when I have completed the main missions, but I'll leave up my first impressions too. I think it would be really good to be able to compare how my thoughts change, if they do, when I finish the main story. As always you can comment on my review using either the comment box on the page or a forum post.
* This is intentionally blank
I kid, sort of. Normally I have three heading in each news article, but I didn't really come up with three things. Thought that would make a funny heading, but than I ruined it by explaining it, huh? Or well. Let's all start looking forward to next week and may more commissions! YAY!!
