#+TITLE: A new section and a new sub-section
#+DATE: 2023-07-25T15:48:36-07:00
#+DRAFT: false
#+DESCRIPTION: Say hello to the other adventures and reviews sections!
#+TAGS[]: site forum news
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Hello everpeep, we have a couple new sections to announce, well really its a section and a sub-section. Anyway, I am adding a review section and a new other adventures section!

Hello everypeep,

I have a couple new sections to announce! Well, its really a section and a sub-section. The first is a full section completely dedicated to [[{{%ref "/reviews/" %}}][reviews]]! The other is a sub-section of my [[{{%ref "/adventures/" %}}][adventures]] section that is dedicated to [[{{%ref "/adventures/fiction/" %}}][other adventures]], or adventures that are of a more /original/ nature!

* The new section
[[{{%ref "/reviews/" %}}][Reviews]] is best seeing as a logical extension of my [[{{%ref "/guides/" %}}][guides]] section, but it is also broad enough to warrant its own section, in my opinion. It will be a collection of reviews, primarily of games that I've played, that I hope will help you decide if you would like to play them. The reviews will have different headings with relating to the strengths and weaknesses of that game and, guess what? The [[{{%ref "/reviews/stray.org" %}}][first review]] is already up!

Now I'm not saying that /my/ opinion should be bible or that it is even perfect, but its mine and I hope it will be one voice that will help you decide if you want to give your time and/or money to play the game. Keep in mind that I am a story-driven player. I play games mostly for the story, so this will be a strong draw for me in deciding if a game is worth my time. That said, graphics and gameplay are also important and will be considered.

* The new sub-section
You already get to see some of [[{{%ref "/gallery/creations/index.md" %}}][my art]], and now you /might/ just be able to read more of my original stories. The new sub-section, [[{{%ref "/adventures/fiction/" %}}][other adventures]] will collect some of these stories for you to read. Please read them if you want. I'm just putting them out there. I'm not saying I'm a good writer or anything, but maybe, just maybe I'll be a good storyteller at least.

* The forums!
Going along with this release, I plan on adding threads to the [[https://forums.onigirionegai.info/viewforum.php?f=4][my forums]] for my original adventures so you can comment on them if you'd like. I will also be adding a new forum for the reviews section and adding threads for my reviews. You can, of course, still comment on these using the comment box, but I'm hoping the forum threads can be used for my in-depth discussions.
