#+TITLE: I Hath Discovered Visual Novels!
#+DATE: 2023-10-26T16:09:16-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Just kidding, I discovered those a long time ago 😝 Actually, what's funny is that some of my favorite JRPGS are also marked as visual novels, at least according to Steam. For /some/ of them I can actually see that. Like Hyper Dimension Neptunia, or Fairy Fencer. Those do have some RPG elements to them, like building and leveling your characters and exploring dungeons, but most of the story is delivered in the same fashion as a visual novel. In fact, I can kind of even see it with the Persona series since much of that story is delivered in the same fashion. Sure both 4 and 5 also had some full motion scenes too, but those were kind of few. So, I guess I kind of like visual novels, though I am a bit disappointed in how similar say Neptunia and Fairy Fencer play even though the stories are so different.

* Some ADVENTURES in VNs!
You maybe have noticed that the past couple of weeks these were actually written a day early! I was kind of proud of myself for that. Of course you /might/ also notice that this one is *not* being written a day early 😅 Well that's because I found a translated VN that I've always wanted to get my hands on and may, or may not have, started playing it late at night when I should have been sleeping.

This VN is ひぐらしのなく頃に (officially translated as Higurashi When They Cry). When I was attended my first year at university, I discovered the anime adaptation and downloaded the entire series fansubbed. I still have those fansubs. This was before an official translation was even announced. Naturally, I discovered this was originally a visual novel, but, at the time, that was obviously not translated. You should know, by the state of the Japanese version of this site, that I'm not very good at Japanese, and this would have required a LOT of reading, so I just stuck to my fan translations of the anime.

Fast forward to two days ago and I was looking to see what kind of visual novels were available on Steam. I was just curious, wasn't looking to buy anything. I came across one though that caught my eye as it had "When they Cry" in the title. I looked, and it was by the same developer of Higurashi. That's when I decided to have a look at their developer page on Steam and discovered that they had translations up for what appears to be most if not all of the VNs of Higurashi! I was very excited, but even more excited when I found out that the first chapter, just like when they first released it, was still free. I downloaded it and started playing it late a few nights ago and may have stayed up a little late last night playing it too. Even better than it being free is that it has entirely new character sprites, which appear to be drawn by the character designer from the latest anime OVAs!

I may have also downloaded and started playing a few more...embarrassing VNs that were floating around my library already and may or may not have also started playing those a little late at night too 😅

* Episode 4!
Of course I /did/ managed to wake up at some pretty okay times even though a stayed up late and I wasn't too tired yesterday. The day before was a bit rough though, not going to lie. I also didn't have much to do after school hours, so I started Episode 4 of RE[BASE]. I plan on releasing it when this comes out, but, as I am writing this, I'm not quite done with it and it still needs proofing. If it isn't there now, looked forward to it next week. If it is, then I'll take my head pats please!

This episode is inspired by a kind of lonely weekend I just recently had, but also a bit of what I went through during COVID times. Don't worry though, RE[BASE] is still pretty lighthearted, at least it is for now. I can promise things will be different, just don't know when. Actually, that is something RE[BASE] has in common with Higurashi, they both start lighthearted, and then change. I can't say if RE[BASE] is going to get nearly as dark as Higurashi, but it will be different than it is right now, right now!

* There can be only one!
I don't know if I mentioned this before, but I usually let one game consume everything I play until I finish it. I would like to be able to play more than one game at-a-time and praise myself when I'm able to hold two or more games at once, but that usually doesn't last long. Hopefully, I'll get back to Persona 4 soon even though I do now have three VNs that I am working through again. I am only about halfway through Persona 4 Golden and would like to finally finish it soon. There will be an update to the walkthrough this week though, and with any luck, there will be one next week too!
