#+TITLE: A Little Tumble
#+DATE: 2025-12-04T09:37:27-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Maybe a lotta a tumble 😅 It was a tumble though that's for sure! I smacked my head super hard and ended up with a concussion as well as some new bandages. Am doing okay now, but am still being careful.

Ya'llo Kittens! 💜

I'm writing this in a different style. It's less typical blog post and more of a letter to you, my fans, my kittens. So I wanted to use this format to informally and candidadely tell you what happened this week. At around one in morning 1 December 2025 I had gotten up to go used the toilet when I look a tumble in the bathroom. I don't really remember what happened exactly. To me, one minute I was walking out the door of my room and into the hallway and the next I was on the floor of the bathroom crying out in shock and pain. With blurry vision I unlocked the door and ya-pa rushed in to help me. I remember being embarrassed because I was half out of my onesie. I also remember seeing my head covered in blood and freaking out a lot.

After ya-pa calmed me down, ya-ma helped me get dressed and also cleaned my head and did a bit of first aid. I was than taken to the emergency room. The staff there were really nice and helped me understand what may have happened. I got an EKG, CT Scan, and some blood work done. I didn't have any brain bleeding or swelling, but was diagnosed with a concussion. They had to run blood a couple more times just to be sure that I hadn't tumbled from a heart attack. That was ruled out, fortunately.

At around six in the morning I was released from the ER and taken home to rest. Ya-pa and ya-ma monitored me while I tried to sleep. I didn't get much sleep, but was able to wake up normally. I spent the first day trying not to look at screens at all, but I did send a few messages out on Twitter and Bluesky. I also let my Discord community know that I would not be streaming that day.

Tuesday I was able to use my phone a little bit more and let my YouTube kittens know what was going on. I even managed to keep my collab with B on Wednesday, but had to cut it a bit short so I could rest. I am doing much better now. I had a bath yesterday and my bandages were changed. I don't have the giant one anymore and just a few band-aids. The major cut did need stitches which still have to be removed.
#+begin_export html
<div id="salutation">Thank you, and remember I love all my kittens,</div>
<div id="signature">
Yayoi 「やよい」
</div></p>
#+end_export