#+TITLE: Becoming a PhD Candidate
#+DATE: 2025-07-13T14:18:27-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: A long while ago I happened upon an anime entitled Candidate for Goddess. To be honest I don't remember much about the anime only that it was kind of like a mech anime but it had some cute girl or something that got me interested. Now though I'm reminded of my vague memory of this anime as I make a very important transition from doctoral learner to PhD Candidate.

A long while ago I happened upon an anime entitled Candidate for Goddess. To be honest I don't remember much about the anime only that it was kind of like a mech anime but it had some cute girl or something that got me interested. Now though I'm reminded of my vague memory of this anime as I make a very important transition from doctoral learner to PhD Candidate.

* The journey so far
Another part of the anime was that pilots of these mechs trained for years just for the opportunity to pilot one. In a way my journey is very similar. I spent over ten years learning and training in the field of developmental psychology starting back in 2008 as an undgergrad taking basic psychology courses often with an emphasis on development to a Master's degree I earned in 2022 specializing in Child and Adolescent Development and Educational Psychology and culminating in doctoral level studies in mental health, public health policy and development over the lifespan.

* The next milestone
Just as the pilots in this anime trained for all these years just for the chance to become a pilot I have been training and learning for the chance to become a PhD Candidate. It has all come together for the opportunity to take a comprehensive examination where I will not only demonstrate what I have learned but also the skills necessary to design and lead research studies.

Passing these exams, which I intend to do on the first try, does not grant me a degree as it did in undgergrad it merely proves that I have what it takes to be a PhD Candidate. Once I prove I have the knoweledge and the skills to design and lead research studies I will need to do that in the form of a dissertation, only after that and defending it, will I earn the degree. Nevertheless this is an important step, a transition from learner to candidate.

* The effect on everything else
In the anime, as I recall, if I pilot failed to resonate with his mech, he would be removed from the academy. I have the same stakes in this transition. If I failed these exams, that's it my journey to PhD ends. Now, I have been assured by advisors, mentors, and the faciliator that I have the skills and knoweledge I need to pass. However, these are high stakes! Due these high stakes I have made the decision to focus almost exclusively on my exams until I pass!

This means that starting Monday and for *at least* 28 days after there will be /no/ stream schedules! In fact, I may put limits on how much I stream entirely to ensure that I take the time I need to research the questions and write my responses. It also means that I will not have weekly stream recaps for this period. If I do stream I will still take notes and will have summaries ready for one giant recap after I pass, but you will not see this site updated as much.

If you want notice of when I am going live I highly encourage you to join my [[https://discord.gg/3qW8efhqBH][Discord]] or subscribe on [[https://www.youtube.com/@yayoi-chi][YouTube]] where you'll be able to see waiting rooms as they go up!

* I will see you at the end...
I'm still here and, even if I won't be streaming as much I still love all the kittens who support my streams. You make it all worth it and I wouldn't even stream if it wasn't for you. I appreciate your understanding and patience during this time. When I pass we'll celebrate me becoming a PhD Candidate together!