#+TITLE: Initial Exam Report
#+DATE: 2025-08-10T09:39:44-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Hello every kitten! It has been four weeks since I started exams and I think its time  for an update. I know I've been giving little mini-updates on stream, but thought maybe something a bit more formal would be nice. Also, some changes are coming!

Hello every kitten! It has been four weeks since I started exams and I think its time  for an update. I know I've been giving little mini-updates on stream, but thought maybe something a bit more formal would be nice. Also, some changes are coming!

* Week 1
The first week of exams was a bit tough. I had made a plan to write for at least 30 minutes per session. So I would sit down and focus solely on writing for at least 30 minutes. If I was still in the middle of a thought or didn't feel like stopping I would keep going. The idea though was to then take a break and write some more, which I wasn't so good at, but that's not exactly why the first week was so hard.

This week was hard because it was shorter than I expected. You see I had opted to start the exam on Monday. So I /should/ have received questions then. Monday came and went and there were no questions. Monday night I e-mailed the exam facilitator and told her I did not receive my questions. Tuesday morning came and went. Tuesday afternoon came and went. Finally on Tuesday evening I received two e-mails. One was from the facilitator who stated their was some sort of technical glitch that prevented some of us from receiving our questions on time. The other e-mail, however, had my questions!

So I got my questions a day and a half later and had to scramble to try and get more writing in so I could be on time. Fortunately, I did get a day extension on my due date so I wasn't too worried about it. I also managed to keep a good pace though the answer to this first question is a little shorter than I wanted. I'm not sure what more I could add though, so I moved on to the next question.

* Weeks 2 & 3
Monday I finished proofreading the first question so I didn't start the second until Tuesday. This question was a long one and it was very easy to write a lot. There was so much to cover that it was almost overwhelming. The first week some of my "writing" sessions were actually library sessions, but this time I spent a lot more time writing and less time at the library. I guess I just didn't have any trouble locating citations in references I already have. The next week was really just more of the same only I did have to spend one day at the library. By the end of the third week though I had all three questions finished and proofread.

* Week 4
Up until this point each of my answers were in a separate document in Apple Pages. I prefer Pages because I know where everything is, but no one outside of the Apple Cult really uses it so Pages isn't a good format to put documents into that you need to submit or collaborate on with others. Now I had been exporting each one to a Word document at the end of each writing session, so that wasn't a big deal, but the readers want one document to review not three!

I started this week by reviewing everything and making sure that all parts of the questions were answered. Once I was satisfied, each answer was copied into a new Word document only one question wasn't fully answered and stayed where it was until Tuesday. On Tuesday I added the new information I believe I forgot and it was added to the document. I then put the questions in the right order and added the title page the university requires. I was almost done, but still had a bit of work left.

Now it is Sunday of this fourth week. I have uploaded the document to our plagirism tool to make sure I have properly cited and paraphrised everything. Tomorrow is submission day. I technically have until Tuesday, but, as I mentioned, I don't have much to change or add at the moment so I figure I can submit a day early. Can't hurt anything. Once I submit it though, its just a waiting game.

* Week 5
Now I will be waiting. The readers have up to 7 days to review my submission. It'll be in their hands now. I'll have to trust in myself that I answered everything. Rather than think about it though, I think we'll go back to a somewhat normal stream schedule. Speaking of streaming though, its time for me to change up my branding again!

* Changes?
Now that I am free of exams (unless I have to do a rewrite 🤞🏻) I think its time for me to evaluate my branding and make sure I am consistent across my channels, this website, and my socials. I will be unveiling a new color pallet that I plan on using for all sites that allow me to as well as in my profile pictures, banners, and overlays. You will also potentially see a new PNGTuber for this week's art stream and a new position for my model (which technically already debuted Friday). The rest of the changes will be discussed after I pass my exams!

I wanted to take this time to thank all my kittens. Streaming during my exams has kept me centered and helped me refocus when I needed to. It has been fun to explore Blue Archive with you as well Stardew Valley. Above all, chatting with you is so nice. Thank you for your support and hope you enjoy my streams!