#+TITLE: Stream Recap: Exam Mega Recap
#+DATE: 2025-08-24T17:46:14-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: stream recap news
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: For the past four weeks I had to focus on my comprehensive examinations. I had managed to stream pretty regularly even during the exams, but didn't update this site much. So, I have a lot to update you on!

* Art Streams
Yep I kept up with my Maker Monday streams even during exams! Actually I think I was very productive with them. We finished page 7 of our comic and that means we finished the first chapter too. I didn't have time to work on finding a way to get them up here yet nor work on the motion comic I have planned for YouTube. I have a feeling I'll be able to at least get that started soon though. Of course I also have other things planned, but I'll get into that later.

We didn't just finish that chapter though! I also started something special, a new character design. Over the majority of my Maker Monday streams during this part I worked on the base character design for Yayai, a magical construct that indexes my spell book (grimoire) and helps me recall and cast spells. I still have her outfit to design, but that will come soon.
* Game Streams
And we had many a game stream during this time too. I debated for a bit how I wanted to organize this section, but ultimately I decided that it would be best to go by game rather than date. I hope that isn't to disorienting for you. Also, because there are so many streams here, I won't embed them. Instead I'll link you to them. Thanks to my astute note-taking abilities though, I have summaries for each one!
** Blue Archive
A new game for the channel! I was really excited that it came to Steam so I could share it with the kittens!
*** [[Let's explore together!][https://youtube.com/live/VrPkulQ-LcY?feature=share]]
Wanted to try this game for the kittens before, but was trapped on mobile. Fortunately, it is now on Steam and now it works on the Steam Deck! It doesn't appear to support controllers, but that's not a problem. We managed to get through to prologue and a good chunk of the Foreclosure Task Force story. Maybe there will be more soon!
*** [[Ya Sensei is here to help!][https://youtube.com/live/wg0f7kgKnhc?feature=share]]
The story is crazy! I mean, the Foreclosure Task Force ended up looking for intel in the black market, where they met a girl who seems to know quite a lot about the black market and even found a bank which appears to be handling their payments, but in order to find out for sure they decide to rob the bank to steal transport logs. Then Hoshino goes missing and the Prefect Team attacks and...it was just a lot. Lots of fun though! Crazy over-the-top stories are something I kind of miss these days 😆
*** [[Ya Sensei "helps" more cute girls!][https://youtube.com/live/WaNAABr2674?feature=share]]
The silliness continued for a bit, but then things got serious! Hoshino was given an offer and things have begun to spiral out of control for the Foreclosure Task Force! We don't know yet what they're going to do, but we do know they are not happy and are prone to doing rash things so it'll probably be big. Maybe they'll force Hoshino to come back? However, just what is going on with Kaiser?
*** [[Ya Sensei looks after wayward students][https://youtube.com/live/cqJeGMMqLM4?feature=share]]
Haha Hoshino I never signed your withdraw papers! You're still my student and I'm going to bring you back. So I did. We even managed to pull together a few interesting groups to help pull it off. Sadly, not much changed for them even after we exposed the Kaiser PMC director, but they still have hope and maybe, just maybe, things will get better with time!
** Xenosaga Episode III
We finished it! We finished Episode III and that means we also finished the Xenosaga series. Now, we are far from 100%, but we finished the story. I may revisit Episode I and III and some point and see about getting everything. I'm satisfied for now though!
*** [[Where's my father?][https://youtube.com/live/tc9uIWPATNs?feature=share]]
Well, we found Jr's father. He was playing with toys he shouldn't be playing with. Fortunately we managed to take those toys away and we sort of saved Nigredo, maybe. It's kind of hard to tell in this game where people who die don't stay dead while people who should be alive are somehow dead. Much has been revealed, but much is left to be revealed yet!
*** [[What did Zarathustra say!?][https://youtube.com/live/sPQQF4RwEes?feature=share]]
We had some unfinished business with the Miyuki Special, but I ironed it out. Also got Jin's best sword while I was at it. Tried fighting Erde Kaiser Sigma, but quickly remembered I needed all the previous robots and well, things didn't go well there. We did do some more story and that worked out much better though!
*** [[The secrets of Michtam][https://youtube.com/live/9UKx8bKLDF4?feature=share]]
The secrets of Michtam have led us to Mary, or at least Mary's will. It is time for us to find out what will happen when she awakens. Will the universe survive? Will Shion survive? Most importantly, will Shion stop being so selfish and rude? We stopped in the middle of a fight so we'll find out next time!
*** [[KOS-MOS, Mary, T-elos just who's who?][https://youtube.com/live/E6LGLQCzSo4?feature=share]]
T-elos was very patient waiting a week to die...or cease to exist, or merge with KOS-MOS or whatever the beep just happened. We even managed to convince Shion that we love her. Well, Allen did most of the talking, but it worked. Kevin didn't wanna give up so easily and put up a bit of a fight. We took care of that for now though. Next time we take him on it'll be the last time...I hope.
*** [[Zarathustra...fights!?][https://youtube.com/live/VUjb8Ihzeug]]
We finished Xenosaga! It has been a great time and I loved getting to share one of my favorite games with all of my kittens. Honestly, I didn't think I would finish the final boss in one try, but I did, it took forever, but I did it. We started a new game that will be our game for Throwback Thursday as well. I hope you enjoy that one too!
** Wuthering Waves
Mostly shifted focus a bit. I decided to focus on events and companion stories. I think we got a few done including Roccia! I also managed to lure her into my team!
*** [[The Continued Journey of Yayathyia!][https://youtube.com/live/aUAubyziOjs]]
Managed to make it to Septimont, but we only had an hour to play Wuthering Waves. Still, we met Lupa and continued our search for Cartethyia! I started a few missions in Blue Archive once I got kicked off Wuthering Waves when disaster struck and we lost the network! Hopefully we'll see more of both games soon!
*** [[The Road to Champion!][https://youtube.com/live/Y51KxzPG8YM]]
Following Cartethyia's trail led us to some interesting places. The Septimont we arrived in was not really Septimont. We had to uncover the tale of the girl we knew as Lupa as well as another named Mya while figuring out what was real and what was fiction. In the end we were reunited with Cartethyia though! Overall, great story! I hope the kittens enjoyed it too.
*** [[Yaya learns more about her companions][https://youtube.com/live/tKLxGQvVEvE]]
It was about time I took a break for main quests. We took care of a few tutorial quests and got our bottoms handed to us in Septimont banner thingy so I switched to some companion stories. Remembered that Brant's story was silly so we started there and well we had to do Roccia after because she's his first mate, makes sense right? We completed both stories too. Roccia's was a little sad, but mostly sweet! I'm going to try to pull her again, I just have to at least try now.
*** [[Yayoi needs more time with her companions][https://youtube.com/live/koKjHRs_rDM]]
I lured Roccia with pasta, and it worked! Spent some time leveling her a bit and also poked some colors. In hindsight that's probably why we weren't able to quite finish Carlotta's companion story. We did some and uncovered some family drama and a mirror version Carlotta and a lot of other cwazy things. It was all a bit too much to keep track of. It was fun though!
*** [[Must poke all the colors before they're gone!][https://youtube.com/live/CuKPgUpO7Yw]]
I poked all the colors! Also finished Carlotta and Zhenshi's story quests. A very productive stream and a lot of fun. I had fun sharing these with the kittens, but there are still more quests for us to do. I gotta get Zani soon! There's some permanent events to unlock first though. Hope you have lots of fun with me!
** Stardew Valley
I have played this before, but that was co-op with friends. This is my first time going through it with my own farm. I just kinda do my own things, but I like it. Nice and chill.
*** [[I have no idea what I'm doing][https://youtube.com/live/KHut6QyLygY]]
Wanted a nice chill time and I think we go it! Started the Kitten Cove farm and met most everyone in Stardew Valley. I also started exploring the mines. We're at level 20. Lots of skill leveling too. Let's see if I can git gud at this game!
*** [[Do you think I have plan now?][https://youtube.com/live/b-xE61706zg]]
Wondering around may have been a good plan. I guess there isn't so much to do when you first get started. We have to meet the wizard and then we get some stuff to try and find. I spent a lot of time fishing, mining, farming, and just leveling up skills. Maybe we'll have more of a plan next time!
*** [[Exams over, but I still want to live on the farm][https://youtube.com/live/tPQCUrPo51g]]
Another few days on the farm. I completed my map. I completed a bundle in the community center. I even leveled up a few skills. Just another cozy stream. I think that's why I like Stardew Valley. So nice. So cozy!
** Persona 5 Royal
After my real exams I decided, why not take fictional exams too? I thought the fictional ones would be easier, but, I was wrong. Real exams definitely turned out easier than the fictional ones!
*** [[From exams to exams?][https://youtube.com/live/wiZHBPx0Hx0]]
After completing my real exams I thought, chu know what would be fun? Playing a game with fictional exams 😆 So I did! We got passed those exams and I think I'd rather take the real ones. I missed two pretty easy questions in the fictional ones. Also, at least the real ones were on a topic I know 😅. Other than that, we opened a new area in Mementos and potentially located a new target! Things are going to get interesting soon!
*** [[@MEDJED am coming for chu!][https://youtube.com/live/-uAQbfenlhQ]]
We may not have found out who Medjed is, but we did uncover the identity of another hacker who seems to desire a change of heart all her own. She's a girl my age and is apparently the reason I have to live in an attic. Am not bitter about that, just wish I didn't have to find out this way. Even though she wants a change of heart though, it looks like this is going to be one of our most difficult heists yet!
** A couple others
I did two other games, but only one stream each, so I'll put 'em here. I did one Genshin stream and I started Dark Cloud. Technically, Dark Cloud started at the end of the last Xenosaga Episode III stream, but I only had one full Dark Cloud stream.
*** [[The truth is still out there!][https://youtube.com/live/MxxnQj1A2Jo]]
Learned all we could about Furina and the people of Fontaine. I didn't expect the story to be so sad. We got through it though. I do have to say all the archon in the game have some pretty tragic backstories and it is very good pulling at your heartstrings. We still have somethings to do here and then maybe we'll be off to Natlan!
*** [[It's cave. It's a divine beast cave][https://youtube.com/live/GVVHjnfBE0A]]
We found the cat girl. Chat has officially named her Neko and she was very helpful taking care of pesky bats and giant FEESH. We also got the town basically finished, but I'll have to chat with everyone again because one of the requests wasn't met. We'll get it though. Off to the next village next time!
* Special Announcements!
First, I want to thank all the kittens that continued to support me during the last month. It was really nice being able to focus on my exams and not have to worry about stream, but also nice that I was still able to spend time with my kittens and have lots of fun with you!

I will be back to a normal stream schedule starting Monday (25 Aug 2025 PT). For the next week at least, there will be no official, set schedule. I encourage every kitten to check either my [[YouTube Live Tab][https://www.youtube.com/@yayoi-chi/streams]] or my [[Twitch Schedule Tab][https://www.twitch.tv/yayoi_chi/schedule]] throughout this week for exact days and times. Also tune in Monday for a special celebration stream and for more news on things coming to the stream as well as potential changes. If you are not able to make the stream, don't worry, there will be a blog post next week as well and it will detail some of those changes. Also, with exams now behind me, there will be stream recaps every week again! I will, however, be getting them out by Monday instead of Sunday. Thank you again for all your support!