#+TITLE: Cave Raiding Tips
#+DATE: 2023-03-12T17:57:06-07:00
#+DRAFT: false
#+DESCRIPTION: Cave raiding is not an easy profession and there are certainly a few things you'll need to consider when making a dive. Here are just a few.
#+TAGS[]: guide rpg jrpg survival tips mia
#+TYPE: guide
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Some tips to help you survive your next cave raid!

Hello fellow cave raiders! My name is Yayoi and I am a moon whistle who has learned a thing or two about cave raiding. I'm writing down some of the things I've learned in hopes that it may help you out (and me 😜) out on your next cave raid! We'll go over a few general tips here, nothing too specific, because, well, you know everything is limited. Speaking of limited, that this first thing I think you should remember about cave raiding.
* Know your limits!
As a cave raider who have to be mindful of your limits. How long can you run? How far can you climb? (stamina) How long can you survive without food or water (hunger)? How much pain can you endure (HP)? How much can you carry? These are all very important things to keep in mind. As you get used to cave raiding you're limits will increase, but you have to always be aware of this, because, if you forget you could easily find yourself in a very irredeamable situation.
* Know your purpose!
Because every resource is limited each cave raid should have a purpose, a reason you going down that day. That reason could be just to explore, it could be to complete a specific request, or it could be to get new experience, hunt relics, or gather resources. A specific purpose, however, helps you to limit how far you'll go and what exactly you should bring with you.
** Exploration
If you are diving solely to explore The Abyss you have to be the most careful. You don't want to starve before you can go very far nor nor you want to be killed because you found a new creature you don't have the means to fight. If you decide go down for exploration focus on bringing weapons, ammo, and food. You may want to focus on bringing ingridients for cooking rather than buying and carrying cooked dishes. However, you may need to bring a few big dishes with you depending on how far your initial dive will be.

Bringing ingrdients with you as well as plenty of weapons and ammo means you can hunt while you explore. Cooked dishes are heavy, but ingredients for dishes are relatively light, meaning you can carry more ingredients, but don't take /every/ ingredient you can buy or carry. Focus on dishes you know you can get some of the ingredients for as you explore. For example, if you are in second layer, you know you can get plenty of eggs and bird meat as well as a lot of various herbs, so focus on bringing things like salt or spices that you can use with these ingredients to cook bird meat and eggs. There are only a few dishes that you can cook just by gathering ingredients in The Abyss, so keep this in mind when exploring.

Finally, while exploring, only attack things you can cook and avoid attacking or being attacked as much as possible. You'll bring a lot of weapons and ammo, but you'll want to save these for things that you can kill to help you survive and not for defense if possible. Also don't go to far at once. This goes back to knowing your limits. Know how far you can go with the supplies you have and only go about half that far so you have enough supplies to get back to the surface.
** Requests
This is similar to exploration in that you will want to focus on weapons and ammo. Depending on how far you have to go to complete a request you may decide to bring less food or focus on pre-cooked dishes rather than ingredients. My one piece of advice for you though, is don't take on too many requests at once! Focus on one request at a time unless you have requests that are both short an not far from each other.

If you come accross a request while you are exploring this is where you have to make a potentially difficult dicision. Take a look at your current supplies, decide how far you could go, then decide if you should return to the surface before completing the request or try to complete it with the resources you currently have. Some short requests can easily be done while your exploring, but don't forget your initial purpose and don't be mindful of what you can do with the supplies you currently have.
** Relic Hunting and Gathering
If this is the reason you want to cave raid today, than you'll want to keep as much room available for gathering or carrying relics as you can. Some advice, however, decide where you want to relic hunt or gather resources and take only the weapons and food that you'll need to get to that location plus at least one extra weapon to defend yourself if you need to. If you are relic hunting, remember that cooked food is heavy and so are relics, so make sure you balance this well and focus on ingredients. Most things you'll be gathering are fairly light so you can bring some cooked food with you if you want. If you want to do both at the same time then start by gathering as this lighter and move on to relic hunting as you use resources and weapons.
* Know Where Your Going and Where You've Been
Take this from a cave raider who has gotten lost more than her fair share of times, you'll /always/ want to know where you are, where you're going, and where you've been. You'll want to know these things for two reasons, to help you know how far you've gone and to know how to get back to the surface once you need to. No one wants to starve because they got lost!

Its for this reason that I have begun putting together some [[{{% ref "guides/mia/maps" %}}][maps]] to help you (and me) navigate The Abyss. So far I have mapped out all the various section of the first layer and how to traverse to and from each area. You can use these maps to help you navigate to specific areas and back in the first layer so you don't get lost, like I have.

Another thing to remember is that it is far easier to decend in the abyss than it is to ascend. To put it another way going down is easier than going up. This is not just because climbing is harder than jumping down, but also due to the curse! If you go up to fast you'll feel its effects and you'll need to rest and get used to the new depth. I advice that you always take the time to do this when ascending because you don't want to be blinded by the curse while creatures are near you or lose your lunch!
