#+title: Yaya's World: Powered By Hugo!
#+author: Yayoi

Hello everypeep!

Since I have created by own GitHub account, I have decided to take over the repo for my website. Apparently, a README, which "helps people interested in this repository understand your project" was never created! I guess I never understood the importance of having a README until I took over the repo, so I make one now. Also, I suppose I /should/ talk about what this repo is. I'm sure no one is really interested in collaborating on it except maybe the person who is kindly hosting this on their server, but I'll explain what this is.

* What is Yaya's World?
Put simply, that's my personal website and blog. I originally created it to share guides for video games that I was playing. Guides I made myself...well, if I'm honest, it was originally only going to be one game, but....it exploded a bit. Now it has guides, even some finished one, reviews, and artwork. All of it is made by me. That's really all there is to it. Nothing fancy.
* So wuts with all this code?
Well, you see, most of this is Hugo-related shtuff. Configuration and raw web page like shtuff. The website itself is really only storied in the ~public~ directory. Hugo allows me to write web pages in a more comfortable mark up language. Which is a combination of Markdown and Org-mode, and then deploy a static HTML site based on those pages. The ~content~ folder contains the actual raw pages.
