#+TITLE: Walkthrough
#+DATE: 2024-03-19T10:59:52-07:00
#+DRAFT: false
#+DESCRIPTION: A walkthrough for Persona 3 Reload
#+TAGS[]: guide walkthrough p3 persona
#+TYPE: guide
#+WEIGHT: 1
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: This will walk you through everything that is available to you in your every day life in Persona 3 Reload

Welcome!

This is designed to help you figure out what you can do each day of Persona 3 Reload! This is designed to give you a heads up on events happening each day, I will not be telling you what to do each and every day, instead I favor telling you what will happen and how to prepare for each day.

* First Block
** 4/6
Your story begins! You'll be given an opportunity to learn some of the games controls, but that's the most control you'll get during this day.
** 4/8
Quiz: *vivid carp streamers* (already a difference!)
** 4/9-4/17
Like in the original P3 and P3P a powerful shadow attacks the dorm on 4/9. The encounter is only slightly different and is still a bit limited. Focus on what you're told you can do during the fight and just basically let it play out. You'll be out cold after this fight until 4/17.
** 4/18
Quiz: *middens*
** 4/21
You'll learn where you can buy equipment today and then your after school hours become free, for the most part, from here on out. I'll let you know when this changes. Kind of the point of this walkthrough.
** 4/22
Forced to spend time with a classmate named Kenji. He'll open an S-Link for you though. Oddly his S-Link is Junpei's archon in P3P, just another thing that's different.
** 4/25
Bookworms opens! Not a place to shop really, but you can open another S-Link and work on it here.
** 4/27
Quiz: *A*

The student council wants you! Well at least the president does. This will give you access to the student council room and open an S-Link so might as well.

** 4/29
You can use this day off however you want, including opening a new S-Link for playing an online game. You'll also learn a bit more about the shared computer before you evening starts.

** 5/1
You'll lose this afternoon to a brief after school scene. You're evening isn't affected.

** 5/3
You'll be introduced to Tanak's shopping channel. Check this each week for some good deals.

** 5/6
Quiz: *a pantograph*

You're told about the lonely girl, but won't be able to open this S-Link just yet.

** 5/9
You'll skip straight to the /Dark Hour/ today. You'll be introduced to a new kind of mini-dungeon and the games first major boss fight, if you don't count the very first shadow you fight.
| Name      | Archon | Lvl | Slash | Strike | Pierce | Fire | Ice | Wind | Lightening | Light | Dark |
|-----------+--------+-----+-------+--------+--------+------+-----+------+------------+-------+------|
| Priestess | ?      | ?   | -     | -      | -      | -    | -   | -    | ?          | -     | ?    |
There is a time limit for this fight! It seems like it's plenty of time as the clock starts at 30 minutes, but the Priestess as a skill that will speed up the clock and shave several minutes off at one time. In my play I didn't see a single weakness. Try attacking with everyone's best skills and only healing when it is absolutely required!
