#+TITLE: A Commission! A Friend's ADVENTURE!
#+DATE: 2023-08-03T14:11:07-07:00
#+DRAFT: false
#+DESCRIPTION: I'm being commissioned to design a vTuber avatar! Oh, and a friend wrote a very cute story that I wanted to share here!
#+TAGS[]: site news friends
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Hello and welcome to another update!

I like that I have time now to do more frequent updates to the site. This update is going to be a pretty small one. I have more time for sure, but not so much time that I can do big updates every time. I am trying to focus on good updates, so more frequent, but quality updates is what I'm trying to achieve. This week, there is no new review, but I plan on writing one for Little Witch Nobeta fairly soon as I just completed that game. I didn't do everything, but I did finish the main story so I feel qualified to review it now. You can look forward to that review in next week's update!

* A friend's ADVENTURE
For this week, we have a new [[{{%ref the-ultimate-yolk %}}][ADVENTURE]] added to the [[{{%ref adventures %}}][ADVENTURES]] section only I didn't write it. That's right I got permission from a friend, [[https://www.instagram.com/michelle.bsparkx/][michelle.bsparkx]] to use a story she had posted on Discord. I really like the story and thought it would be a good fit for my ADVENTURES, it even inspired to write more short-form stories. I was suuper glad she let me post a copy for everyone here. I hope you like it.
* A commission
Yep, this week's news is all friend-related 😆. A different friend of mine is planning on streaming soon and would like an avatar to use during their streams. They asked me to design the a vTuber and I have started that right away. I was really excited to get commissioned and want to do my best. I just hope they like what I come up with for them. I will not be posting all of the drawings I come up with here, but I will, with their permission of course, be posting some of the completed designs. I hope I do a good job, there is one thing I'm a little worried about though, but hopefully it will be fine 😅.
* Support?
I was asked if I would like financial compensation for the above commission, for me a commission is any request where I get some form of compensation and there are other forms than just money, but this did get me thinking, I don't like taking money from people directly, but maybe I can take money through donations or something. What do you think? I've put [[https://forums.onigirionegai.info/viewtopic.php?t=21][a poll]] up in my forums. There you can answer and give me comments and reasons that support your answer, thank you for helping!
