#+TITLE: A Little Too Much Gaming?
#+DATE: 2023-10-18T19:03:09-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

I guess I'll start with a confession. There will be no episode of RE[BASE] this week. I'd like to point out that I said that I won't necessarily be trying to maintain the once-a-week pace for episode releases. I also mentioned that releasing the first three episodes on that schedule was more because I was on break and had a lot of time. So, I would like to say its because I started back in classes so I don't have the time I did when I was on break, but that's not really true 😅

* This week, in school, I did...
Nothing! Okay not /exactly/ true. I did things. I read and I participated in discussions, but the reading was pretty light week one, and almost non-existent this week. Technically, I'm in week two, by the way. So, my school work really didn't get in the way of my writing. In fact, I probably spent about three hours on school work last week and maybe two and half thus far this week 😅 Now it's not that I'm not as diligent as I was and I'm certainly not feeling lazy, but I just don't have much to do in school. That's just the fact thus far. Maybe things will pick up in week three or four, but so far, not much going on.

* This week, in gaming...
I've been playing [[{{% ref "guides/p4g" %}}][Persona 4 Golden]]! In fact, I've been playing that a *LOT*. Like maybe a bit too much. All that time not working on school work, yeah I spent that playing Persona or watching other people play games, like my friend on Twitch. Oh I've also been leveling a new character in Fiesta and working on some of my other characters, so yeah this is probably where /most/ of my time is spent 😅

* Balance
In short, I'm still having a little bit of trouble finding balance in my life 😅 I'm much better than I was a few weeks ago and I'm still taken time to write this article and plan on spending time working on episode four of RE[BASE], that might not be until the weekend, but I've gone from being lazy to just redirecting my energy to games. I will say one thing though, I know my creativity suffers if I try to force myself to work on a project, so I'm not going to do that. I will need to find other ways of motivating myself to actually get it done. Mayhap the first step will be to ensure I know what the next episode will be about. Having a clear idea of how I want to start it, I think, will really help get things flowing and make me /want/ to write. Anyway, I am still a work in progress, so bear with me. Also, I plan on starting some illustrations the weekend. Hopefully you'll see them in a few weeks!
