#+TITLE: Busy Week
#+DATE: 2023-09-14T15:46:47-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site news
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Hello!

I come bearing some bad news. There will be no content update this week. I am, as you can read, still writing a news article, but there will be no further updates. I am pleased enough that I have not forgotten the site for several weeks straight now. I still count this week since you are seeing this. Maybe I should start putting a counter in 😆 Just kidding, I think that would change my mindset and I would end up breaking the streak and then saying "Why can't I keep it going!?" and get all depressed, so I won't do that. I'll just continue to be happy that I make an effort every week to at least post a news article!
* Sleeping Habits!
Yep I'm just going to jump over here without a single transition sentence cuz, weee, it's fun! So sleeping habits, mine suck! I don't know why. I think sleep is important and I know I feel much better when I get at /least/ seven hours of actual sleep, not just laying in bed. I even went through the trouble of getting an Apple Watch SE so I could track my sleep more accurately. Guess what? It works! But, remember that sentence in the other paragraph about me saying "Why can't I keep it going!?" Well, that applies to my sleep too.

When I was working part time /and/ going to doctoral-level classes at full time (I don't suggest doing that, especially if your part time job is very demanding and you end up with almost full time hours), I always said, oh I am working to much, that's why I'm not getting enough sleep. So I quit my job and everything worked out. All done! I get good girl head pats now, right? Wrong!

Oh, I was doing suuuper good for awhile. Yep always getting at least seven and a half hours of sleep and feeling great. Went from needing a energy drink in the middle of the day to not needing anything. Unfortunately, it didn't last. At some point I noticed that, although I was getting enough sleep, and it felt great not waking up to an alarm, I was starting to get up later and later. I totally didn't want to be one of those who didn't wake up until noon, even if my school schedule would allow it. So I threatened to set myself an alarm again. Now I have been waking up no later than eight, which is kind of good, except for the fact that I have been getting less than seven hours and feeling sluggish and needing energy drinks again 😔 Now I feel dejected because I am not getting enough sleep and asking "Why can't I keep it going!?" again. This time with no answer. Actually, I'd say, because I played over three hours of Holocure and didn't get to bed until one, I'd say that, except that was last night and I actually was only minutes from my goal that night. Anyway, I'll try to do better, but that is not why there is no content updates this week 😝
* Signature Assignment
At the beginning of this quarter I started my first of three virtual residencies to prepare for my doctoral dissertation. This has been an interesting course and has helped me a lot in settling on a actionable research topic for my dissertation. In the course of this course I have done a lot of research, to the point that, I think I know just about everything you can know about one specific topic 😆 I also did a *lot* of writing. This week has been, and continues to be, very busy as it is the last week of this residency. That means I have a signature assignment due that goes over the particulars of my topic and outlines the research I plan on doing. At the time I'm writing this, it is about 77% done. Just a few finishing touches, really. I have spent my week on it though. This is the main reason there is no content updates this week.
* How About Next Week?
Well, there is a big chance there will be more content updates next week. I have an idea for another short story that I would like to write and, as I said, this is the last week of my first residency. I get a short break between this and my next course, so I'll have time to work on more creative things. Maybe I'll also finish another drawing. Either way you'll have some thing to look forward to next week. For now, I hope you are satisfied with this one, rather long, news article!
