#+TITLE: Feeling a Little Lazy
#+DATE: 2023-10-05T16:48:13-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

I am feeling quite lazy, have been for the last few days. To be fair to myself, I have made progress on all of projects and completed many a to-do item, but I really had to force myself to do some of them. I actually finished episode two of RE[BASE] sometime just after I published the first episode so that will be going up this week. I even started episode three, but I didn't make as much progress as I wanted and I haven't played the games I wanted to play this week either. I still need to finish my Persona 4 playthrough so I can get the guide done. I'm only halfway through, I think.

* I can do it!
First, I think I should acknowledge that I did things! I /might/ be feeling lazy, but the truth is I didn't just sit around like a sloth. I mean, I did spend far too much time in/on my bed, but I got out of it and worked. So I have to acknowledge that things got done, and that's good. Hey, I'm even writing a new article so my streak isn't broken, that's something right?

Let me also list other things I did:
+ Started episode 3 of RE[BASE]
+ Published episode 2 of RE[BASE]
+ Finished a lot of paper work for work
+ Finished Allana's character design
+ Started an outfit design for Allana so I can post her
+ Finished a 100 follower special outfit for Jade

See, I was actually quite productive this week!

* Not everything that glitters is gold
Sadly, I also have to admit that, thought I was productive this week, I wasn't as productive as I could be. I could have finished both Allana's design /and/ her first outfit. I could have made more progress on episode 3 of RE[BASE] and I could have written a longer news article. I also could have worked a little bit more on the Persona 4 guide. These things didn't happen this week.

I don't really know why I have been wanting to stay in bed more. Maybe its the cooler temperatures luring me to stay under the warm, cozy comforter, or maybe its that I've had a lot on my mind and its been weighing on me too much. Either way I've not been wanting to get out of bed and start working and that as pushed a lot of things around to where they shouldn't be. I've kept myself in check so far, but I'll have to keep monitoring myself and making sure things get done. I can do it!
