#+TITLE: Fun Art Is Fun
#+DATE: 2023-11-16T18:29:07-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site news commissions
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

This week has been pretty busy. Been working in a new position and attending lots of meetings and training seminars. I got another commission. On top of everything I'm still working toward my degree as well. So yeah been busy, but its also been mostly fun...as long as you ignore the last heading that is 😜

* New Position
As many of you should be aware, I am a PhD student looking to become a professor of psychology. Previously I was working as an ABA therapist. This work was fun, but it was also beginning to be too much. I was having difficulty focusing on my client's needs /and/ my schoolwork. So, I decided to leave.

Well now I am a graduate assistant at the university and I will be supporting fellow doctoral learners. I'm excited for this position as it will give me experience teaching adults which I hope I can use in my future career as a professor. I just hope it will also help me develop a comfort for speaking and working with others, because that's a problem for me 😅 Of course I get to work in the comfort of my room, with all my stuffies, so I think that'll help to get me started.

* New Commission
During this transition I had, sadly, lost some income. That was the really nice part of working where I was working. Fortunately, I have a very understanding friend who helped me by commissioning me. Sadly, this isn't finalized yet so I was not able to publish it here before this update. It'll be up by the next update. I actually did two pieces that I hope they can use for streaming.

I always seem to do better when I'm drawing for someone then when I'm drawing for myself 😅 I'm more motivated not just to draw but to draw well. Its also a lot of fun, so I'd like to get more. If you have any thing you want me to draw just head over to my [[{{% ref commissions.org %}}][commission page]] for more information on what I'm willing to draw and how to contact me for a commission, and check out my [[{{% ref gallery %}}][gallery]] for examples of my work!.

* BTW, I Hate Windows!
I'm going to start by saying all of my work (training tasks, school work, art commissions, etc.) is done on a Mac. I mostly play games on my Steam Deck, however, I still have a Windows PC set up because of a small handful of games I can't play on the Steam Deck or the Mac. Problem is, I've been having issues with updating that system. Twice now Windows has borked itself from an update. I'm facing the prospect of having to completely reinstall Windows for a second time, and I'm not liking that. I don't have problems like this with macOS or SteamOS. Those updates usually just work. It's only Windows. I won't drop windows because I still want to play these games, but I really don't like to mess with things. I guess that's why I'm primarily a Mac gal. I'm going to ask anyone in the comments to share their Windows horror stories so I'm know I'm not alone.
