#+TITLE: Happy Turkey Day 🦃
#+DATE: 2023-11-22T14:19:17-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Spooky month is over, Christmas is not yet here, so that must mean its harvest time and that, at least for those of us living in the United States, means Thanksgiving, also known as Turkey Day. It also means I short work week and lots of time needed to prepare so not much in the way of updates this week. I picked up a new VN that I will like to review as I heard its one of the classics. I also hope to add more VNs that I have on my Steam wishlist to the reviews. I'm still working on finishing Persona 4 Golden, but I focused more on getting homework done this week so I wouldn't fall behind during the holiday. I will be putting up the commissions I finished last week though.

* The Turkey Debate
It has come to my attention, from meetings and other sources, that there are people who don't like Turkey 😲 I can see why some people wouldn't like the bird. It can be very difficult to cook because of the different meats, and it can be very bad dry. I like it though, it is a good canvas for sauces and gravy and its very versatile left over. So, I still think it is the best part of Thanksgiving. Though I will say I prefer ham on other holidays like Christmas. There's nothing quite like a Christmas ham! I'll also say I wouldn't mind trying another fowl, maybe ostrich 😆

* Expanding the Reviews
I have done a new review in a while. Mostly I've been trying to finish Persona 4 Golden, which has been a much longer endeavor than I thought. It has taken over and I haven't even been playing "No Man's Sky". I do manage to play through some VNs though and I'm hoping to finish one or two of those soon. I wouldn't mind putting up so reviews for those for you all to check out, so maybe that section will stop collecting dust soon.

I didn't do much in Persona 4 Golden yet this week, but, with the holiday coming, I'll have some more time, so maybe you'll see more in the guide. Remember, I have split it into two parts, all new stuff will go in the second part. The first part is basically done until I go back and fill in the early stuff after I'm done with this playthrough.

* Commissions
I mentioned last week that I finished a couple commissions. Because I hadn't delivered the final pieces to the client by the time that update went through, I wasn't able to put them up here yet. Well I have delivered the finals to the client and am now able to post them here. Check out my [[{{% ref "gallery/commissions" %}}][commissions gallery]] for new additions! Have a very happy Turkey Day!
