#+TITLE: Its Almost Time 🎄
#+DATE: 2023-12-14T19:08:33-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site news christmas work school
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Things were going so smoothly with all my other things that I was bound to almost forget something 😅 The thing was...this site 😆 Yeah there isn't really any updates this week. I'm trudging along through Persona 4 Golden still, but I have been focusing more on Christmas projects and less on other things as it is, as the title says, almost that time. Now, I don't really think of myself as behind right now, just on different priorities. It would be different if I had an idea for something like a new episode of RE[BASE] and was postponing that, but I just got an idea for another episode for Nagisa's story today, so not really behind yet.

* Final Week of the Quarter!
Each quarter in school seems to go by so quickly! Usually I'm like super nervous first day and the first week seems to drag on, but then, suddenly its the last week and I've already got most everything done!

Also, for the first time ever, I don't have an assignment due this week. Most weeks in the quarter are a full seven days, but the last week is always only five and it can be kind of hard when there isn't an assignment that week, but this time our last assignment was last week so don't have to worry about that now. There were some things to do, but, as I said that's mostly all done so I can look forward to a nice winter breaks starting next week!

* A lot to do at work!
Things are wrapping up in training at work and I'm about to transition into my full role. I had a lot to do to get ready for that though. Its been nice having less to do in school so I can focus my time at work! After this week though, there will be a bit less to do. Mostly I'll just be transitioning so not too much will interrupt winter break. Also, unlike my last job, I won't be working Christmas Eve, Christmas, New Year's Eve, or New Year's.

* RE[BASE]
I ran into a bit of writer's block with RE[BASE] this week, kind of. I really didn't give much thought to any of the character's story after Nagisa's debut, and I didn't really devote any time to that this week. I have a direction now, so in a week or two there will be another episode of RE[BASE] and it will be another Nagisa episode! Nagisa will also be featured in my Christmas illustration this year. Speaking of which, there is more than one Christmas project this year!

* Christmas Projects!
Every year for like over 10 years, I've worked on an illustration for Christmas. This is always my Christmas present to my parents. This year is no different an that project is already more than halfway done. I've already drawn Nagisa and just need a background, a print, and a frame. Seeing as I got that far so quickly this year, I started on two more projects. These are Christmas presents for my friend who commissioned me to design Jade. They are for them and they are both featuring Jade.

The first project is a new avatar featuring Jade in a Christmas dress. The second is going to be either a wallpaper or special cut-in for Jade, also in a Christmas dress. So that's three projects for one holiday! I think I'm doing really good this year and hope I'll continue to be able to have fun with my art as well as all the other things I have to do!
