#+TITLE: Moar Reviews!
#+DATE: 2023-08-10T19:28:59-07:00
#+DRAFT: false
#+DESCRIPTION: I wrote a thing!
#+TAGS[]: site news
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: I wrote another review. This review is about a game I played while I was playing Stray. I don't normally play two games at once, but I actually managed to just this one time. As for other news, I've mostly just be working hard on commissions and other work. This means only small updates like this week's updates, but I am still doing weekly updates so I think I'm doing fairly good!

I wrote another review. This review is about a game I played while I was playing Stray. I don't normally play two games at once, but I actually managed to just this one time. As for other news, I've mostly just be working hard on commissions and other work. This means only small updates like this week's updates, but I am still doing weekly updates so I think I'm doing fairly good!
* A little witch!
[[{{%ref "reviews/little-witch-nobeta.org" %}}][Little Witch Nobeta]] is a very good game. It is plagued with some story issues, but I did enjoy it. I also enjoyed writing my review. I hope you enjoy reading it. Don't really have much else to say, except Nobeta is suuuper kyuute! Okay I said it!
* Weekly updates
Even if it is just new content like a new review and a new news article, I am still updating this site weekly. So far I've been able to keep my deadline three weeks in a row, even though it was a little difficult this week. My commission is coming a long and its a lot of fun to draw it. I mean how many other jobs to you get to watch YouTube while you work 😜. I also enjoy drawing and I think I'm doing even better then I would if I wasn't working for someone else. It does take a lot of time and I am also still working at school so I was pretty busy this week, but I still managed and I hope to continue to manage my weekly updates for a long time!
