#+TITLE: Not Just Allana
#+DATE: 2023-11-30T12:11:42-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: rebase allana news site
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Things are progressing nicely with some of the illustrations for RE[BASE] and there are already five episodes written. Only one illustration is up so far, but I am hard at working making another one. So far all five episodes center around Allana. Obviously, she is not the only character. In fact, through her story, you have been introduced to a few others, but I am here to announce another main character who will debut (there's a pun in there for anyone reading this after her debut 😉) next week. Plus a few more announcements I'm working on!

* The Christmas Season has Started!
Every year since high school, I have been drawing a special Christmas illustration. This has served as a Christmas present for family and friends. There have been some years where this was the only present I could give out because I could not afford anything else. You can say my talents save me from not having any thing to give. So, for me, the Christmas season starts right after thanksgiving. This is when I begin the planning process for the year's Christmas picture.

This year is not different. As you know [[{{% ref "happy-turkey-day.org" %}}][Thankgiving]] is over and I have begun planning this year's illustration. The idea and pose are all ready, but I have not yet started the artwork itself. That will happen soon, but I am currently still working on another project. Specifically, and illustration for RE[BASE], however, I will not be accepting new commissions until *after* the holidays. If you want something commissioned, please contact me after 2 Jan 2024!

* Illustrations for RE[BASE]
As soon as I described Allana's Halloween outfit in [[{{% ref "allana_ep5.org" %}}][episode 5]] I knew this was going to be the first illustration. Of course I stuck it a little low on that page because I wanted it to after I described it, but its there and you can also see it in [[{{% ref "gallery/creations" %}}][my creations gallery]]. There was another scene in an earlier episode that I wanted to draw as well, so I have already started that. It will be done soon and I will add it to the story and gallery. At some point, I might have a separate gallery for RE[BASE], but we'll see. This illustration is also why I haven't started my Christmas illustration yet. It turned out the pose and angel are more difficult than I thought. Please let me know if it's worth it 😅

* RE[BASE]: Nagisa
Let's go live! I would like to officially announce the debut of Nagisa! Negisa will debut (in the world of RE[BASE]) next week. As of this posting of this article, I would have started writing her first episode. This year's Christmas illustration will also feature this new character. Look forward to see her first episode next week. Her story will run, in part, in parallel to Allana's. Allana will not be featured in her story right away, but they may meet at a future time. I hope you like her!

* VNs and Persona 4 Golden
The walkthrough for Persona 4 Golden is slowly coming along. I am approaching the end of Oct in the story and will hope to get the next dungeon up soon. While playing Persona 4 Golden, I am also playing a few visual novels. I forgot how much I enjoy these. I am hoping to finish Clannad and it will be the first review of a visual novel I put up on this. Because of the nature of VNs, I'm not going to put any guides up for them. If you really want to find secret routes or make the "right" choices, there are plenty of other places you can go. I think you should make choices the way you think would be best for you in your first play through, than try different things out as you re-play them though. That's where the enjoyment is, I think, so I won't be guiding you, but I'll let you know what I think of them as I finish them.
