#+TITLE: Ready for the New Year
#+DATE: 2023-12-20T18:37:02-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site personal news christmas work
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

I hope you all are looking forward to Christmas! If not, well maybe I can give you all something to look forward too! This year's Christmas illustration is finished and it features Nagisa. It will be your first opportunity to see what she looks like, so I hope that's enough to get you to look forward to Christmas. I mean, I /could/ release her now, but I'm going to wait just so you all have a Christmas present to look forward to. I actually had a total of three Christmas projects, but none will be leaked here early, I can guarantee that.

* Persona 4 Golden Update
As I am now on break from school, I have a /little/ more time to play games. Not a lot of time as I still had projects and work, but a little. I used this time wisely I think and have gotten up through the end of the latest dungeon on Persona 4 Golden's [[{{% ref "guides/p4g/walkthrough.org" %}}][walkthrough]]. With this I should now be nearing the end of the story and this playthrough. I have a lot of changes I would like to make to the previous part of the walkthrough and added a few additional guides so I won't be stopping my work on Persona 4 Golden just yet. If you have any suggestions you can leave a comment on this article on the guide/walkthrough pages.

* Can the Year be Over Now?
Well this is going to be a bit of a rant I guess. I'm not happy with how the holiday season is turning out this year. I mean, on the one hand, its nice that I have a pretty flexible work schedule and I'm actually being encouraged to take holidays off. This is good, but I'm still busy with other things and I keep getting sudden notices of events and dinners and family things and just too much. I've had to re-arrange a lot of things and I think it caused a bit of stress. Not enough to lose sleep over, but some.

I wanted my Christmas projects to be done yesterday. I was even on that track. The annual Christmas illustration was mostly done, just needed some finishing touches for both a physical print size and web/desktop size no big deal. The other pictures were basically done, just a few touch ups and finishing touches, but I kept having to delay those because of sudden changes. This meant I was suddenly not sure I would have things done. I even started a bit earlier and worked a bit faster than previous years! It was really frustrating.

Fortunately the one picture came together on Monday and I just finished the other one. I just need to submit the physical print-sized version for printing and pick it up along with a frame. If that doesn't happen for some reason I won't worry too much, but I'm hoping I won't get anymore surprises. If I do, I /might/ just have to say 'no' 😡

Anyway, I kinda just want all of this over now, so bring on 2024 now please and thank you! Just kidding! Hopefully the rest of the year will go much nicer now that everything is basically all done.

* A Special Christmas Message
Now that the rant is over I want to thank all of the people who have supported me over the year. I went through I lot of transitions and changes and I couldn't have done it without you. Thank you so so so much for sticking by me even when things didn't go as planned and for helping and supporting me!

I especially thank [[https://www.twitch.tv/jadeeyeddemoness][Jade]] for commissioning me and showing me that my art is worth something. I have enjoyed making things for you and I hope you enjoy your Christmas presents.

For all of you! I hope you too enjoy your Christmas presents and please keep supporting me. I love my art and want to do more of it in 2024!
