#+TITLE: RE[BASE] is Up!
#+DATE: 2023-09-28T19:31:16-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site news rebase allana
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Hello everypeep,

It's been another week and with another week another update. This time I am pleased to announce that I am releasing the first episode of a multi-part series of short stories that I am calling RE[BASE]. I've been spending most of my time working on this story and some art relating to it. Mostly trying to get character designs done. I'm also working on a secret project, shh, don't tell anyone.

* Celebration time 🥳
My friend, and first client, has just reached affiliate on Twitch! Actually, I am watching them stream as I'm writing this. They are also about to reach 100 followers and its been great cheering them on. Of course it is also great seeing my art on every stream. My little Jade is really getting out there! If you have some time why not hop over to [[https://www.twitch.tv/jadeeyeddemoness][Jade's twitch page]] and give them a follow. If I'm lucky they'll be able to commission me some more with a few more subscribers or followers, so do check them out!

* Drawing for other people
While I have also spent time working on some of my own projects, mostly just designing new characters for RE[BASE], I find it far more interesting and easier to draw for other people. I don't know if I get some sort of reward from it, or what, but I do like it. In fact I'm working on a bit of a surprise for someone. They aren't even paying me and I enjoy it far more than working on anything I started for myself. I think this is why I really want more commissions.

* RE[BASE] Update
[[{{% ref "adventures/fiction/rebase/allana_ep1.org" %}}][RE[BASE] Episode 1]] is officially out today! I have also started the second episode and it should be out next week. I'm not sure if I'm going to be able to release an episode every week, but I'll try at least during break. Should be you'll have three episodes up to read just in case things slow down during my next quarter.

Of course, the short stories aren't all I plan on releasing. I am designing the characters too and you'll see them in my peektures, but I am also hoping to illustrate parts of the story. For this I would like to incorporate them in the actual story, maybe one at the beginning and a few peppered in between paragraphs. Not really sure how I'll do it just yet, but you'll see as they come out. As I mentioned last week, I won't be waiting for these illustrations to release episodes, but its likely that they will come out fairly frequently during the next quarter. It is usually easier for me to find time to draw than write. Just check back old episodes every now-and-then to see new art.

If you have any comments on the story, don't hesitate to let me know. You can comment on the pages themselves, or use any of the links at the bottom to reach me, including the forum. Thank you! Hope you enjoy the new story!
