#+TITLE: Walkthrough
#+DATE: 2022-12-06T21:38:37-08:00
#+DRAFT: false
#+DESCRIPTION: A walkthrough for Persona 4: Golden
#+TAGS[]: guide walkthrough p4g persona wip
#+TYPE: guide
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: This will walk you through everything you need to do in Persona 4: Golden!

Welcome!

This is designed to help you figure out what to do on each day of Persona 4: Golden! This is designed to give you suggestions and hints, I will not be telling you /exactly/ what to do each and every day, instead I favor giving you the /options/ (read: things you can do) for each day, and giving you the choice of what you can do.

I'm currently working through my playthrough, and, I've started this kind of in the middle of that playthrough. So I don't have each day laid out just yet. For now I'll be pulling from things I've read and my own memory, but hope to have a better, more organized, walkthrough up in the future. For now, I'll be picking up at the second dungeon. The good news is, the first dungeon and the story to that point, is pretty straightforward. Nevertheless I will be covering that when I can.

* The hot and steamy bathhouse!
There is something just a little odd and unexpected about Kanji Tatsumi. On the third day after rescuing Yukiko, Kanji appears on the Midnight Channel. The first time the party sees this they aren't entirely sure who it is, but it becomes clear after the second viewing. Sadly, they cannot confront Kanji before he is kidnaped. He appears once more in a steamy bathhouse, only he seems a little different.
** 5/20 - 5/23
Kanji disappears around the 20th of May (5/20). The 20th is a Thursday. Even before he disappears, Dojima-san tells you to keep an eye out for Adachi in Junes. Believe it or not this is a clue, though its not really Adachi your looking for, but I digress.

You see, when Kanji disappears, you will head over to the TV world where your shocked to find that Teddy is having difficulty locating Kanji. To help him out, you need to learn more about the delinquent. To do so you need to find the young man you saw him speaking to just before he was kidnaped. Remember how I said Junes was a clue, well this young man can actually be found in Junes, but not every day. In fact, he is only there Tues., Thurs., and Sat. You need to find him, speak with him, then find Kanji's mom and speak to her, but there's a bit of a trick to this. She will only appear /after/ you speak to the young man, and never on the same day you speak to him. So you have to time it right.

After speaking to the young man, go about your day, maybe go to work or do whatever you want that day, keep in mind that your friends, and a few others won't be available yet. On the next day, go to the textile shop. Kanji's mom should be right outside, if she isn't, go about your day as you normally would, if she is, speak to her first. Finally, on the next Tues., Thurs., or Sat. Find the young man and speak with him again. He'll give you the clue you need to hand over to Teddy. You can hop into the TV right away to hand over the clue and gain access to the bathhouse, or wait until it is most convenient. You should have access to your friends and other social links once you have the clue, but I shared it with Teddy right away, so I'm not sure.
** 5/24 - 6/3
If you do the above quickly you may have a bit more time. If your slower you may not have as much time. This is the date I started and should be a good amount of time to get this dungeon done and dusted. I'm still on this date.

The first two floors are fairly easy. Keep in mind that each floor is generated randomly by the game, just like with the previous dungeon. There will be chests to open and some fairly easy shadows to beat. There is a cutscene where the party gets their first glimpse of Kanji's shadow, but this all that is of note. On my playthrough on easy I was easily able to reach this floor in one afternoon. As with all dungeons, mind your time and watch your party.

After a few days I came back and got up to floor seven. On this floor you will encounter a sub boss. He isn't too difficult. I does appear to have an instant kill skill, and my use it against your female party members. Best to have some revival beads on you. He does nullify light-based skills, and I was not able to find a weakness, though darkness wasn't tested. I'll put the output of his analysis below

| Name         | Lvl | Archon   | Full HP | Full SP | Fire | Ice | Lightning | Light | Dark |
|--------------+-----+----------+---------+---------+------+-----+-----------+-------+------|
| Daring Gigas |  24 | Strength |     928 |     100 |      |     |           | Nul   | ?    |

After reaching the 10th floor you will encounter Kanji and his shadow. Prepare for a fight! My strategy, however, was to get to the last floor by 6/3 that allowed me to take on these boss's with full HP/SP. The results of the analysis are below. Keep in mind that these guys appear to target female party members more, have opposing weaknesses, and can block each other's weaknesses. This makes for a challenging fight even on lower difficulties. The fight is far from impossible especially for a fully rested party.
| Names        | Lvl | Archon  | Full HP | Full SP | Fire | Ice  | Lightning | Wind | Light | Dark |
|--------------+-----+---------+---------+---------+------+------+-----------+------+-------+------|
| Shadow Kanji | ?   | Emperor | ?       | ?       | -    | -    | Dr        | -    | Null  | Null |
| Tough Guy    | ?   | Emperor | ?       | ?       | Wk   | Null | -         | Str  | Null  | Null |
| Nice Guy     | ?   | Emperor | ?       | ?       | Null | Wk   | -         | Str  | Null  | Null |

One final note: These bosses can cast poison and rage on the whole party. In my playthrough rage seemed to effect the female party members while males were less effected. Poison appeared to work the opposite. I'll update this when I have a chance to test it in other playthroughs

** 5/25
On this date you will get a cutscene before school introducing you to a new job, the Tutor job. This is a job that you can go to at night, tues., thurs., and sat. it pays very well (10,000 yen per day), but requires high *understanding*.

Marie is also available to go out this day.
** 5/26
There is a quiz in class today. This is a fairly easy question as long as you are paying attention. If you want to skip the dialog, however, the answer is, "attendance logs".
** 5/28
The mail order show starts. You can order things from the TV in your room. Watch for deals on Sun., Mon., and Tues.
** 5/30
There is another lecture on this day, but there is no quiz and it does not affect what is available for you to do this day.
** 6/1
Rain sets in today. This is the game's warning that you will need to hurry and save Kanji. Marie is available this day as well. Also, it is good to remember that /some/ part-time jobs and clubs cannot be done on rainy days.
** 6/4
This is it! This is your last day to save Kanji.
** 6/5
Kanji returns! You will now have a few cutscenes to go through where the party will welcome Kanji to their group and discuss the case thus far. Congratulations on finishing the bathhouse!
** 6/6
A lot is about to happen and yet hardly anything happens. Here's what I mean. Over the next several days nothing happens on the midnight channel and nothing new happens in the TV world, however, a lot of events and story notes will take place. At the moment the party will just discuss changes to the killer's MO and other notes about the case to this date.
** 6/8
There is a lecture today. There will be a question, the answer to which is "balance beam". After the lecture you will begin discussing getting a motorcycle license.
** 6/9
You'll get your license today and you are gifted a scooter. You can practice riding it and unlock other areas to travel from doing so.
** 6/13
This is the first day of summer, yay?
** 6/15
There is a quiz this day too, the answer is "cheerfulness in a group". You will have a pick up (as in pickup a girl) contest after school today.
** 6/16
The girls go shopping to prepare for the school camp out.
** 6/17 - 6/18
Camp out day one, it should be noted /none/ of your usual ways of spending time will be available, its all story at cutscenes, just sit back and let the game hold your hands for a bit
** 6/20
Rise makes a TV announcement. The party suspects she might be the next victim. There is a quiz this day to, the answer is "Meiji". There is a special boss in the bathhouse. Things are about to shift, so this may be your last chance to take care of it.
| Names              | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|--------------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| Intolerant Officer | ?   | Emperor | ?       | ?       | -    | -   | Wk        | ?    | Null  | Null |
* Marukyu Striptease
Rise Kujikawa is an idol from the small town of Inaba, where the story is taking place. As an idol, Rise has to conform to a certain personality archetype, but is actually quite different from how she appears on TV. As a result, she is struggling with her true self and the "manufactured personality" she has as an idol.
** 6/21 - 6/23
After the party begin to suspect that Rise may be the next target, she begins to appear on the Midnight Channel. Unlike before, they will immediately identify her. Like before, they will not be able to save her, so it will be off to the TV for you.
** 6/24
Like with Kanji, Teddy has difficulty pinpointing Rise in the TV world even after her program begins on the Midnight Channel. He asks you to go get more information about her. You need to ask around town to find out more about Rise. You can start with either the tofu shop she works at where the old lady tells you about the paparazzo hanging around or you can start at the school where you can speak to a chubby man at Practice Building 2F who tells you a bit more about Rise and also advises you to speak with someone in the media. Either way you will eventually have to speak to /both/ of them. Once you do, you will be advise to look for paparazzi at the flood plain. You won't find any yet, but the "kind man" there will advise you to look tomorrow.
** 6/25
Now you can head back to the flood plain and find the "photographer" (if you don't want to/can't do this today, note that the "photographer" is only there Tues., Thurs., and Sat.). Give the man two pieces of info about Rise, basically all options except that she is in town. With this, he gives you enough information that Teddy should be able to pinpoint Rise. Take this information back to the TV to unlock the dungeon.

** 6/26 - 7/9
You have a couple of weeks to save Rise from her shadow. Marukyu Striptease, like the previous two dungeons is roughly 10 floors with a final fight on the next floor after that. There are many different types of shadows and they will begin introducing shadows that nullify or even repel certain elemental attacks. Stay on your toes. Keep a full and diverse party. You can decide what role the main character plays, but I kept him as my Lightning, Dark, and Light damage dealer. Also relay on the analysis option to keep everything sraight. You don't want to accidently use a repelling element. At about 7F you will be met with a sub-boss. This fight shouldn't be too difficult, but a fresh party would be helpful as it will likely start with stagnant air (to increase suseptibility for ailments) and will attempt to poison your party. Here are its full stats as reported by analysis after scanning for weaknesses and strengths.
| Names         | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Amorous Snake |  33 | Lovers |    1012 |     148 | -    | -   | -         | -    | Null  | Null |

After this fight the floor mazes will start to get a bit more complicated, and you'll be dealing with some more difficult shadows. Be very careful as one of them will repel dark, if you aren't careful you could end up instant KOing yourself (leading to an instant game over). After completing ten floors, I suggest leaving and coming back another day so you are well rested for a two part fight.
| Names       | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|-------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Shadow Rise | ?   | Lovers | ?       | ?       | -    | -   | -         | -    | Null  | Null |
Shadow Rise has no weaknesses, but is more than capable of taking advantage of your weaknesses. She is able to use any basic elemental attack. I did not see evidence of light or dark attacks. At a certain point in the fight she will begin to analyze you (yeah I didn't see this coming at all). When this happens you will be unable to hit her. Just keep guarding for a few more turns to trigger dialog and a surprise twist.
| Names         | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Shadow Teddie | ?   | Moon   | ?       | ?       | -    | Dr  | -         | -    | Null  | Null |
It is after the twist that the real fight begins. Shadow Rise, was pretty easy actually, now its time for Shadow Teddie! This will be a real fight. Like Shadow Rise, Teddie has no weaknesses. He will also attempt to lower your party's defenses right away and inflict other ailments. Eventually he will begin charging attacks. At these points, make sure all party members are guarding when the message "Shadow Teddie is charging up" is displayed. You will block the attack fully. Careful though! Shadow Teddie will attempt to inflict dizzy on a party member, or two, before charging up.

** 7/4
There is a lecture and a pop quiz today. The answer to the question is "Pascal"

** 7/7
Another lecture and quiz this day. The answer to the question is "The Deceleration of Independence"

** 7/10
So Teddie joins the party in a new capacity and new form (yeah that was also surprising) and our super cute idol Rise will join the party. She replaces Teddie as your analyst, however, so don't expect her to be fighting alongside you. Your homeroom teacher was murdered last night and his story appears today on the news.

** 7/11
You get a new homeroom teacher. Brace yourself for that, by the way, she isn't exactly any better than your last. Also, brace yourself for a barrage of cutscenes as everyone discusses the case so far.

** 7/12
Nothing much happens now. Take a nice rest! Finals start next week!

** 7/13 - 7/16
To help you prepare for next week's finals, you will have a series of pop quizzes. The answers are relatively easy though if you pay attention in class, you do pay attention, don't you? Well, since this isn't a real school, I guess I can let you look at my answers:
+ 7/13: sphenopalatine gangloinueralgia
+ 7/14: Kuukai
+ 7/15: the equator
+ 7/16: no mustache
Enjoy your weekend! Note: Marie is available 7/13 as well

** 7/19 - 7/23
Finals week is here. Again, just because this is a game and not a real class, I'll let you look at my notes, but you really should just be paying attention in class.
+ Day 1, Quiz 1: cheerfulness in a group
+ Day 1, Quiz 2: balance beam
+ Day 2, Quiz 1: 応
+ Day 2, Quiz 2: Meiji
+ Day 3, Quiz 1: king of hearts
+ Day 3, Quiz 2: pascal
+ Day 4, Quiz 1: pis pis river
+ Day 4, Quiz 3: deceleration of independence

** 7/23
You will meet to discuss the case a bit more. Pick "formaldehyde" when asked. The Lovers arcana is opened to you!

** 7/25
You will get your test results today. How did you do? I gave you all the answers, so you /should/ have done well 😝

** 7/26 - 7/27
Time for a new midnight TV, nothing else happens. Just sit back and enjoy the story. In fact you can sit back for two days! You will meet the next day to try and figure out who the boy is. Actually you probably should sit around the second day. You /should/ go talk to Kanji real quick on the second day you'll need to do this if you want to open the next dungeon quickly.

* Void Quest
Have you found the culprit at last? Only one way to find out! Back into the TV with you! Keep in mind that summer vacation officially started 7/28, sorry I forgot to tell you. This means you will not have to worry about school or club activities. It also means those social links are blocked from progression at this time.

** 7/28 - 7/29
If you couldn't or didn't talk to Kanji, you should be able to do so now, also take his suggestion and talk to Doujima, though it doesn't seem helpful, you can actually use this to get some info out of Adachi, but not on the first day as he is probably not available. Better wait until the second, you'll learn from Adachi that the boy was a part-timer at one of the shops. In fact, it was Souzai Daigaku in the north section of the shopping district (the steak place). Once you talk to the owner there, you should see a boy with blonde hair and a school bag hanging around the tofu shop. You'll get a yearbook photo of the culprit from him. This will be all Rise needs to track him down. If, for some reason, he does not appear, the boy will appear again on 8/1, make sure you have completed all the steps above, before that time. I don't know when he'll show up again, but he does not show up on every day.

** 7/29 - 8/12
This dungeon is modeled after an old point-and-click-adventure game, or maybe an 8-bit RPG brought into a 3-D world, one of those two. If you have been leveling diligently, the shadows here will probably be pretty easy. Just, as always, watch your HP and SP and pace yourself. You have about two weeks to complete this dungeon. Chapter 3 and Chapter 7 will probably confuse you. Chapter three looks like a dead end, but you will be teleported around if you get close to some of the walls. Just be mindful of where you've been and how you got there to avoid backtracking and you should make it to the stairs. Chapter 7 will try to confuse you by moving your move direction and camera around on you. Just gotta power through that one, eventually you'll get to the stairs. There are no sub-bosses in this dungeon, but there /is/ a fairly interesting, and tricky boss fight!
| Names           | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|-----------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Mitsuo the Hero | ?   | ?      | ???     | ???     | -    | -   | -         | -    | Null  | Null |
| Shadow Mitsuo   | ?   | ?      | ???     | ???     | -    | -   | -         | -    | Null  | Null |

This dungeon is fashioned after an old-school RPG. At the beginning of this fight, Mitsuo will start by building his character. This creates the boxy shell known as Mitsuo the Hero. Mitsuo the Hero uses powerful attacks straight out of an RPG, including an old-style UI for you to enjoy. You must destroy this shell before you can hurt Shadow Mitsuo himself. Keep in mind Shadow Mitsuo a wall during the fight and will attack with the Ma-spell that matches it. Be mindful of your party's weaknesses and try to counter when you can. He will also attempt to rebuild his character, but you will have some warning when this is about to happen. Aside from being mindful of your weaknesses, there isn't much to this fight and you should not have too much difficulty winning.

** 8/3
Marie will be available for you to have a good time with 😜

** 8/7
Marie is now available again. Keep in mind that you are on summer break now. You normal activities will not be available, but you will have much more free time for some of your other S-Links, including Marie.

** 8/12
This is your last change to confront Mitsuo. If you haven't reached chapter 10 in the dungeon by now, you must do so now, at all costs!

** 8/13
Marie is also available today. Your evening, however, will be spent with a lively "victory" dinner with Doujima, Nanako, and Adachi.

** 8/15-8/19
You will be given the opportunity to work at Junes to help Yosuke out. This will earn you 40,000 yen (by the way you'll also get 40,000 for Doujima if you talk to him at the right moment before this day). It will also net you some S-Link points for Chie and Yosuke. However, this all does come with a price. That is you will skip the entire week, so you won't be able to do anything else. It is a good way to fast track some boring days though. Its up to you if its worth it or not.

** 8/20
This is a story telling day. You'll attend the first day of the summer festival with friends. Enjoy the cutscenes!

** 8/21
You can choose to spend your evening with another summer festival day, this time with your favorite girl! This will skip the whole day though.

** 8/23
You can choose to have a beach day today. Choosing this will give you a pretty funny cutscene that you have to watch at least once, but it will skip the whole day until evening. If you have anything you need to do today for any reason, maybe skip the beach for now. The evening will present another option for you. You will be able to help Nanako with her homework. This will build her S-Link rank and also those of a few of your classmates who will stop by to help. Its worth it to help you build those S-Links, but will also take up a few evenings, not just this one.

** 8/24
You remember that you have summer assignment to work on. You can choose to spend your daytime hours at your desk working on homework. This is a good way of raising your knowledge, but if you are already fairly high, than you /might/ want to skip one or more of these. At least you have the option. Also, remember, if you decided to help Nanako your evenings will be spent with her (you have no choice after the first one), so you won't be able to do anything else in the evenings.

** 8/29
This is the last day to finish your summer assignments. The game is going to force you to spend the daytime hours finishing them up. If you chose to help Nanako you will spend your evening with her, so this day will probably be a wash. Fortunately, it also happens to be the last day you'll need to help Nanako.

** 8/30 - 8/31
Prepare yourself for a lot of story scenes. First, you'll have the fireworks festival, this will take all of the first day. Second, you will have some watermelon to eat with Nanako and your friends. This takes the daylight hours of the second day.

** 9/1
School is bake in session! Welcome to your second term! Naoto, the boy detective will also come to school for the next few days, including the school trip. You'll also spend your after school hours talking with Naoto over recent events, so more story!

** 9/3 - 9/6
Nothing of particular note here. You're finally free to do almost whatever you want. On the first day Marie will be available to work on her S-Link. You will receive a quiz on the second to last day in this stretch. The answer is Brisk. The last day here will inform you of a powerful new shadow in the game that you can /optionally/ fight!
| Names            | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|------------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| Escapist Soldier | ?   | Justice | ???     | ???     | -    | -   | -         | -    | Null  | Null |

Watch out for elemental skills! Will also cast "Stagnant Air" and "Mudon". Remember, "Mudon" is an instant KO dark skill, if this hits the party leader, it will be a game over. It is best to make sure your party leader, if not the entire party, is immune to dark.

** 9/7-9/11
You will have after school on 9/7 to yourself, but your evening will be taken up by getting ready for the school trip. The school trip itself lasts from 9/8-9/10 and is all story, so just sit back and relax again. You will be home by 9/11, and Marie will be available again.

** 9/12
A special report will be shown on TV. This report talks about the case and, most importantly, about Naoto. It will take away your evening though, so plan accordingly.

** 9/14
The rain lasts well into the night today. You will use this opportunity to watch the midnight channel. If you were paying real close attention you /might/ not be surprised when a faint image appears on the TV. After all even Naoto wasn't entirely convinced that the real killer was caught.

** 9/15
Time to discuss what everyone saw on the Midnight Channel after school. You'll also get the game's first back-to-back midnight channels and discovered that Naoto has gotten themselves thrown into the TV.

* Secret Laboratory
** 9/16
Time to talk about the more clear transmission everyone got to see. Even though you and everyone else is aware of who is in the other world, Rise still has a bit of trouble discovering where they are. You'll have to look for clues. Fortunately I'll tell you the steps you need to take to find the clues you need. First you will need to head back to school. There is someone on the first floor, between classes 1-1 and 1-2 that heard a rumor about another student which had something of Naoto's. That student was spotted near the science labs, and, fortunately, is still there. This girl will tell you that she heard Naoto yelling and a police officer. Looks like you'll have to talk to one. Now there is currently one in the north end of the shopping district, but he won't talk to you. You need a reason for him to listen. Chie will give you an idea. Now I didn't know about this step on this day, so I talked to her on 9/17, but you should be able to talk to her today and then the first officer will give you your first clue, but I'll give you the events as I did them. You will also learn that another officer appears on the south end of the shopping district Tues, Thurs, and Sat, if you speak to the right NPC in the north end. They're near the police officer.

** 9/17
There's a quiz today. The answer is 40 minutes. Once school is out, head over to the flood plains (if you didn't/couldn't talk to Chie yesterday) and find Chie. She tells you what to say when you talk to the polices officers. Now you can find the officer in the south end of the shopping district. If you were able to talk to Chie already you can head directly to this officer and get your second clue. If you were not able to talk to her this is only your first clue. You need two clues to present to Rise before you can go looking for Naoto.

** 9/18
I'm going to put what you need to do to get into the next dungeon here, just note it seems its possible to do this in a different order and maybe get in a day earlier. If you only have one clue, find the other officer in the north end of the shopping district again and talk to him to get the second clue. Now head back to Junes and report to Rise. Tell her that Naoto is tired of being treated like a child and obsessed with this case. That'll be enough for you to start your exploration of the Secret Lab!

** 9/17-10/05
This dungeon is not as straightforward as the others, but doesn't present the same kind of challenge as the Void Quest. When you get to around B4F, yes in this dungeon your go downstairs instead of up, but that's not the real twist, you will come across a locked door. unfortunately something you need is behind that door. You'll have to go down a few more floors before you find a chest with an ID Card. Likely, this floor will also have a locked door but this ID Card doesn't unlock that door. You'll have to go back to the first locked door and use this item to open it to get access to a sub-boss which will have the key you need to open the second door. Yeah it's really that confusing.

| Names              | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|--------------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| Dominating Machine |  53 | Justice |    3070 |     300 | -    | -   | -         | -    | Null  | Null |

This is not a particularly difficult fight. It will buff its attack, this is usually an indicator that he will perform Herculean Strike, which is a power physical attack. I was able to freeze it up by debuffing attack after its buff. Do this a few times and follow up with your most powerful attacks and the fight should be over with out you taking much damage.

Once you have the second key and take it to the second door you'll be able to proceed again. You'll find Naoto on B9F. Enjoy learned a bit more about them before you fight their shadow.

| Names        | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|--------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| Shadow Naoto |  ?? | Justice |    ???? |     ??? | -    | -   | -         | -    | Null  | Null |

Naoto doesn't really fight fair. As seems to be the norm with boss fights now, they have no weakness to speak of, but will nullify your party's resistances as well. Furthermore, while they also don't seem to have any light/dark skills, they do still have one instant kill skill. You'll want to make sure some of your party are able to survive a death blow (usually acquired at high enough S-Rank). When their HP gets low, they will start using Mute Ray which casts silence and steals both HP and SP from a single target. This is a difficult fight, but, if you focus on your strongest party and keep everyone's HP high you should be able to win. Also watch when everyone is buffed/debuffed and plan you attacks just right for the best damage possible.

** 9/20 - 9/28
Not much happens during this time. Its the perfect chance to work on S-Links and explore the Secret Lab. 9/20 does have a quiz in PE, the answer is: nonagenarian. There is a lecture on 9/24. but no quiz. 9/28 also has a lecture and quiz, the answer is: Throat.

** 10/02
You can choose to hang out with the girls today. You don't have to, but you do get a few fun scenes while you are out shopping with them. Kanji even joins you, though Yosuke seems to have been smart enough not to show. If you do choose this, you will gain S-Link for all the girls and Kanji. Might help you with the S-Rank.

** 10/03 - 10/05
Other than 10/05 being the last day to save Naoto, not much happens during these three days. There are quizzes though. Here are the answers in order, starting with 10/04 as 10/03 is just a lecture: tug-of-war, and right edge.

* Congrats!
You have made it through the first half of the year and also about the first half of the game. There is a lot more to do though, but this walkthrough is getting long enough so I'm splitting it up. See you in part 2 (when its ready 😜).
