#+TITLE: Walkthrough (Oct onward)
#+DATE: 2023-11-15T21:39:40-08:00
#+DRAFT: false
#+DESCRIPTION: A walkthrough for the second half of Persona 4 Golden
#+TAGS[]: guide walkthrough p4g persona wip
#+TYPE: guide
#+WEIGHT: 2
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: This will walk you through everything you need to do in the second part of Persona 4 Golden!

Welcome!

This is designed to help you figure out what to do on each day of Persona 4 Golden! This is designed to give you a heads up on events happening each day, I will not be telling you what to do each and every day, instead I favor telling you what will happen and how to prepare for each day.

I've started this kind of in the middle of my current playthrough. So I don't have April included, which includes events from the first. For now I'll be pulling from things I've read and my own memory, but the good news is, the first dungeon and the story to that point is pretty straightforward. Nevertheless I will be covering that when I can.

This part is current a work in progress. I am building this as I playthrough the story myself. This is so I can give you a fresh head up on how things will go.

* Haven
** 10/06 - 10/10
This is a series of story scenes that will take your after school time. It will start with discussing with Naoto what happened when they were kidnapped. They know quite a lot of details, but you will still have wait for another victim to come forward to investigate further. After getting Naoto-kun's reports, you will be helping Yosuke and Rise with a concert. The concert is on 10/10, but you'll spend a few days preparing. Just enjoy the scenes. The event even has a nice animated scene. There is one quiz during these day, on 10/08. The answer is pretty obvious, but I'll tell you anyway, it's: chicken. It should be noted that your evenings are still free, so use this time to finish up Nanako's S-Link or spend time with everyone in the evening.
** 10/11
Your after school hours are still not yours. You agree to study with everyone. Naoto will likely ask you to go into the TV when you get back home, but that'll have to wait until tomorrow. Good news is, this means you'll be free to do what you want tomorrow. There is a quiz today too, the answer is: glass jars.
** 10/12
A nice Halloween-themed quiz. The answer is: turnips (imagine carving those!). You'll be notified that a new strong shadow has appeared in the lab. Now is a good time to go back if you don't have anything else to do.
| Names          | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|----------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| Extreme Vessel | ??  | Fortune | ????    | ???     | -    | -   | -         | Wk  | Null  | Null |
** 10/13
Everything is basically back to your normal rhythm. One more quiz, they'll be ramping up since your exams are coming up again. The answer is: ojisan.

** 10/14 - 10/20
With exception of 10/16, which is a Sunday, you will spend the next few days in school answering questions on your midterm exams. You are normally free in the evening, but may not be free during the after school hours. As such, it is a good idea to have fought the above special boss before this date. You could have 10/16. but you will be asked to join a study group, so, if you haven't fought the boss by now, it will be a toss up between enhancing S-Ranks and completing the boss. There will be sometime after exams, however. I'm not going to give you the questions on your exams as the questions and answers can't co-exist in the same area without endangering all of humanity. I will give you the answers though:
| Day | Q1 Answer             | Q2 Answer        |
|-----+-----------------------+------------------|
|   1 | Throat                | The Right edge   |
|   2 | 40 Minutes            | All of the above |
|   3 | Black and White Bears | Ostrich          |
|   4 | ??*                   | Glass Jars       |
|   5 | Fall                  | Plan Resin       |
(* Day 4/Q1 I got wrong in this playthrough, you'll still get top marks for this, but I can only say Wasan Shoujo is not the right answer)

The last day has no questions. You'll be given a general sense of how you feel you did and the day will end. Your exams on now over, hope you did well. You will receive a mysterious letter, which gives you something to talk about with your friends in the morning, but that is it.

** 10/22
You will be given an opportunity to vote for an activity for your class to host during the culture festival this weekend. As this is the first time I played this far, I'm not sure if your choice actually matters. To be funny, I just chose the "group date cafe" let me know if you picked something different and how that turned out!

** 10/24
You get your test results today. If you answered all the questions with the answers I gave you, then you'll get top marks and all of your school friends will be impressed. This will increase all their S-Ranks.

** 10/27 - 10/28
The culture festival will be starting at the end of this week, and guess which class completely forgot about it? Yeah, yours! So, now you'll be spending a few days, including after school hours, preparing for the culture festival. If you have anything you want to get done in the TV do it before now, or you'll have to wait until next week.

** 10/29 - 10/30
The culture festival itself. This is just a compilation of some really fun scenes. You will lose more time and you'll want to be prepared for a long set of cutscenes. There will not be many opportunities to save once the culture festival starts. In fact, your next chance will be after the hot springs visit on 10/30. Make sure you block out plenty of time to get through these scenes!

** 10/31
You'll get an extra day off. You can save and do whatever, but, if you want everyone's Halloween costumes, you're going to have to help Yosuke out and Junes. This whole thing is a wash and all you get are the outfits though, so its up to you.

** 11/01
Nothing of note really, just a quiz, the answer is: geometric shapes

** 11/03
You'll get an extra day off, just don't count on school activities this day.

** 11/04
Another quiz (the answer is: Cuckoo), another person on the midnight channel. Though no one is certain yet, it is pretty clear who the next victim is going to be.

** 11/05 - 11/20
The story is beginning to reach its climax! There are a lot of scenes this day and little else. However the culprit of all the murders (save one) as well as everyone being thrown into the TV world is identified during these scenes. The culprit also kidnaps his next victim. With all this happening so quickly there is no need for any further investigation. Head into the TV and begin your search for the culprit and his next victim! Starting now, Nanoko will no longer be available, be sure her S-Link is maxed by now.

Once you reach Paradise #7 you will encounter your first sub-boss. This is not a difficult fight, but be prepared nonetheless!

| Names         | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| World Balance |  63 | Justice |    1200 |     100 | -    | -   | -         | -    | Null  | Null |

You will confront the culprit on Paradise #10. This fight is a bit more tricky. The main boss has a full range of elemental attacks, so be mindful of everyone's weaknesses and do your best to cover them with shields or items. It appears the "atmosphere" will change before the boss switches elemental attacks. He also has a very power physical attack and can control your party members. Be careful!

| Names         | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Kunino-sagiri | ??  | ????   | ?????   | ???     | -    | -   | -         | -    | Null  | Null |

** 11/07 and 11/10
Not much happens at school during this time. If you have any job or club S-Links to finish now is a good time to do this, especially if you aren't having any difficulty in the dungeon. It is also an excellent time to work on skills. On these two day, there are two quizzes, the only thing you have to worry about until 11/20. The answer to 11/07's quiz is "no country" while the answer to 11/10's quiz is "Namib".

* Magatsu
** 11/21 - 11/26
You can now visit Nanako. The culprit is also up, and a new mystery fills the town, literally. There are a few quizes during this time as well. I'll give you the answer by day in a moment. First, I wanted to note that every day during this range gives you the opprotunity to visit Nanako. You can choose not to at any point, but visiting her will raise several S-Links and visiting her at least three time will earn you an achievement. It might be worth it to visit her at least those three times. You have to talk to different party members in order to visit her though. The table will tell you the quiz answer and/or who to speak to to visit Nanako (if applicable).
| Date  | Quiz Answer            | Who will send you to visit Nanako |
|-------+------------------------+-----------------------------------|
| 11/22 | a book of maps         | Yosuke (in your classroom)        |
| 11/23 | N/A                    | Chie (Shopping District - North)  |
| 11/24 | the Fibonacci sequence | Rise (Third Floor)                |
| 11/25 | Khufu                  | Not known yet                     |
| 11/26 | Mochi                  | Not known yet                     |
** 11/28 - 12/03
Time for another finals week and another table! Two tables back-to-back must be a record for this guide! This will hold the two answers you need for you finals by date.
| Date  | First Answer | Second Answer      |
|-------+--------------+--------------------|
| 11/28 | Italian Food | Geometric Shapes   |
| 11/29 | Khufu        | Atlas              |
| 11/30 | Bridal       | Cuckoo             |
| 12/01 | No Country   | Fibonacci Sequence |
| 12/02 | Namib        | Mochi              |
This is the last day of exams so there are no questions, you just get a general feel for how you did. Your afternoon, however, will be taken up by several scenes. *A Warning*: You can end the game right now if you are not careful. There is, however, many days left in the game, so be careful, unless you want to see the bad endings. To continue the story make sure you select the following:
1. Wait a second here...
2. We're missing something.
3. Namatame's true feelings.
4. Something's bothering me
5. We're missing something...
6. Calm the hell down!
This will buy you at least a couple more days. You will have no choice but to sleep this evening, so go to your room. You'll be warned that tomorrow is a day of reflection.
** 12/04
And today is that day of reflection. You'll meet with your friends to discuss the case. Here you can kind of just go with the flow. After the scenes, you will go home and be forced to sleep again.
** 12/05
Now that your caught up on the case again. It is time to gather some more information. Ask around town about the two murders. First speak to a woman by the shrine. She mentions something about a suspicious person. You can now ask around about suspicious people. Go Junes and talk to a student there who mentions her friend may have saw someone suspicious. Go back to the shopping district and talk to the student in front of Yosuke. Nothing happens! Keep asking everyone else about suspicious people and the murders. The game pretty much forces you to talk to /everyone/ available in town before everyone gathers to go over the case again.

Once again, you'll have to be careful! As you talk with Naoto, you'll be able to drop a name. The game gives you literally everyone you know as an option. All but one of these name is wrong and may lead you to another bad ending, so pick Adachi, come on, he's the only one that really fits all the criteria. Picking him will let the story continue again.

** 12/06 - 12/07
More days taken up with story and evenings where you can only go to sleep. While there isn't much to do for the first two days a lot does happen. The path forward becomes quite clear, literally.

** 12/08 - 12/24
It seems that the deadline for this dungeon is given to you during one of the scenes. This dungeon, as you can imagine, won't be like any of  the others thus far considering who created it. For me, I got to a dead end around the second level and ended up having to fall down a hole. I'm sure this will happen to everyone, I just can't guarantee it will happen on the same floor for everyone 😅

After jumping down the hole, you will be in a new area. At some point you'll have to avoid all encounters with Shadows. This is a requirement, if you do start an encounter, you will be sent back to the starting room, so just don't do it! If you do manage not to encounter any Shadows, you will have to fight your first sub-boss, though I'm not really sure I should call it that, it really isn't that hard. The stats table is still provided, and I should note, they it does tend to summon new mobs, including lesser copies of itself.

| Names         | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Chaos Fuzz | 70 | Magician | 600 | 124  | -    | -   | -         | -    | Null  | Null |

Shortly after this you will encounter another sub-boss.

| Names         | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Envious Giant | 74 | Magician | 3333 | 3333 | Str | Str | Dr    | Str | Null  | Null |

After this encounter, you'll be notified that it looks like something changed in the other area. Go back to the Inaba section and continue on to the floor with the hole. Don't jump back down the hole! You should be able to access the exit now. This will take you to the final floor and your next boss fight. Now /might/ be a good time to leave the TV world to regroup and resupply. This is actually a two-phase fight and you will want to make sure you are prepared!

| Names        | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|--------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Adachi       | ??  | ?      | ????    | ???     | -    | -   | -         | -    | Null  | Null |
| Ameno-sagiri | ??  | ?      | ????    | ???     | -    | -   | -         | -    | Null  | Null |
So, Adachi has a persona! This surprises the party, but shouldn't be much of a surprise to you, right? Anyway, this does mean that he can use a lot of the skills and powers that your party members can use. Be mindful of your weaknesses. Also, Mundo, is one of those skills! Remember, this is an instant kill, dark skill (if you're anything like me it and Hamon have been your bestfriends up until this point). This isn't a huge problem as your should have someone who can revive your part members, but, be very careful with the MC, his death, as always, results in an instant game over! If you have worked on some of your S-Links and chose your party well, he /might/ survive, but if you have a persona that nullifies dark, this is the best insurance.

Amano-sagiri seems to use mostly fire and wind attacks, but he does have a fully upgraded fire attack that is quite devastating. Also, watch out for the confusing fog. This singles a series of buffs followed by a powerful party attack. If you are caught unprepared, you may lose your entire party. I always just guarded whenever I saw the fog and kept guarding until the attack was launched.

** 12/09 and 12/10
Just a couple pop quizzes here. The answer for the first is: transparent. While the answer to the second is: the cross-section

** 12/23
This seems to be effectively you last day to take care of Adachi. In the evening, your girlfriend (if you have one) will invite you to spend Christmas Eve with her.

** 12/24
You can spend Christmas Eve with your girlfriend. This will replace all other activities this day.

** 12/25
Now you its time for more story scenes. You'll spend Christmas with your family

** 12/26
Watch the Midnight Channel again on this rainy day. If all went well, nothing will be on!

** 12/31 - 01/03
Some more scenes as you visit the shrine for the end of the year. You will also be able to choose a girl to visit the shrine with (this appears to come from anyone your dating, so, depending on how much of a player you are, you /might/ get multiple invites). The next day is for spending with family and you'll be tasked with going around for your New Years greetings. You'll basically have to go around and talk to /everyone/ you've connected with, except Marie. Something different happens when you visit the velvet room. You also start feeling under the weather through all this and will collapse on the last day. Teddy moved in with you and will take care of you.

* Golden Content
** 01/09
You get a few more scenes then your told to work on you S-Links to prepare to locate/rescue Marie. You'll be over your cold by this date.

** 01/10
Just another quiz. The answer is: an orange.

** 01/11
Teddie will come to school during lunch today. This is optional, but it will result in an upgrade for his Persona and a little scene, so why not?

** 01/14
There is a quiz today. The answer is: bury the demons.

** 01/18
This is another update on Marie. You will also have clues has to why Marie might have disappeared.

** 01/20 & 01/22
Nanako comes home and you will spend one day picking her home and another celebrating her return. This will limit your actions on these days.

** 01/25
Another update about Marie and another quiz. The answer to the quiz is: red.

** 01/28
You can choose to help Nanako catch up with homework for the next few evenings. This will eat up your evening time for the next *three* weeks! There isn't much benefit to this other than always having something to do during the evening, but will limit your choices. The scenes are kind of cute though. Up to you!

** 01/30
Just another quiz today. The answer is: petabyte

** 02/01
Another one! The answer is: white

** 02/03
Another update on Marie, you're getting closer!

** 02/04
This will be the last evening you help Nanako, if you chose to help her earlier.

** 02/06 - 02/10
Your advancement exams start today. Like all other exams, you will spend these days answering questions. Unlike those exams this one has questions from the /entire/ last year! Don't worry though, there in the table below along with their answers. You're welcome!

| Date  | Answer 1 | Answer 2                       |
|-------+----------+--------------------------------|
| 02/06 | Beta     | Attendance logs                |
| 02/07 | Toso     | Sphenopalatine gangioneuralgia |
| 02/08 | Rabbit   | Turnips                        |
| 02/09 | White    | Desert Sand                    |

* Hollow Forest
** 02/11 - 02/12
Now that placement exams are over, time for a trip! These two days are filled with story scenes. Just sit back and enjoy everyone spending time with you before you leave. Also Marie is finally found and a new dungeon opens!
