#+TITLE: Walkthrough
#+DATE: 2022-12-06T21:38:37-08:00
#+DRAFT: false
#+DESCRIPTION: A walkthrough for Persona 4: Golden
#+TAGS[]: guide walkthrough p4g persona wip
#+TYPE: guide
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: This will walk you through everything you need to do in Persona 4: Golden!

Welcome!

This is designed to help you figure out what to do on each day of Persona 4: Golden! This is designed to give you suggestions and hints, I will not be telling you /exactly/ what to do each and every day, instead I favor giving you the /options/ (read: things you can do) for each day, and giving you the choice of what you can do.

I'm currently working through my playthrough, and, I've started this kind of in the middle of that playthrough. So I don't have each day laid out just yet. For now I'll be pulling from things I've read and my own memory, but hope to have a better, more organized, walkthrough up in the future. For now, I'll be picking up at the second dungeon. The good news is, the first dungeon and the story to that point, is pretty straightforward. Nevertheless I will be covering that when I can.

* The hot and steamy bathhouse!
There is something just a little odd and unexpected about Kanji Tatsumi. On the third day after rescuing Yukiko, Kanji appears on the Midnight Channel. The first time the party sees this they aren't entirely sure who it is, but it becomes clear after the second viewing. Sadly, they cannot confront Kanji before he is kidnaped. He appears once more in a steamy bathhouse, only he seems a little different.
** 5/20 - 5/23
Kanji disappears around the 20th of May (5/20). The 20th is a Thursday. Even before he disappears, Dojima-san tells you to keep an eye out for Adachi in Junes. Believe it or not this is a clue, though its not really Adachi your looking for, but I digress.

You see, when Kanji disappears, you will head over to the TV world where your shocked to find that Teddy is having difficulty locating Kanji. To help him out, you need to learn more about the delinquent. To do so you need to find the young man you saw him speaking to just before he was kidnaped. Remember how I said Junes was a clue, well this young man can actually be found in Junes, but not every day. In fact, he is only there Tues., Thurs., and Sat. You need to find him, speak with him, then find Kanji's mom and speak to her, but there's a bit of a trick to this. She will only appear /after/ you speak to the young man, and never on the same day you speak to him. So you have to time it right.

After speaking to the young man, go about your day, maybe go to work or do whatever you want that day, keep in mind that your friends, and a few others won't be available yet. On the next day, go to the textile shop. Kanji's mom should be right outside, if she isn't, go about your day as you normally would, if she is, speak to her first. Finally, on the next Tues., Thurs., or Sat. Find the young man and speak with him again. He'll give you the clue you need to hand over to Teddy. You can hop into the TV right away to hand over the clue and gain access to the bathhouse, or wait until it is most convenient. You should have access to your friends and other social links once you have the clue, but I shared it with Teddy right away, so I'm not sure.
** 5/24 - 6/3
If you do the above quickly you may have a bit more time. If your slower you may not have as much time. This is the date I started and should be a good amount of time to get this dungeon done and dusted. I'm still on this date.

The first two floors are fairly easy. Keep in mind that each floor is generated randomly by the game, just like with the previous dungeon. There will be chests to open and some fairly easy shadows to beat. There is a cutscene where the party gets their first glimpse of Kanji's shadow, but this all that is of note. On my playthrough on easy I was easily able to reach this floor in one afternoon. As with all dungeons, mind your time and watch your party.

After a few days I came back and got up to floor seven. On this floor you will encounter a sub boss. He isn't too difficult. I does appear to have an instant kill skill, and my use it against your female party members. Best to have some revival beads on you. He does nullify light-based skills, and I was not able to find a weakness, though darkness wasn't tested. I'll put the output of his analysis below

| Name         | Lvl    | Archon   | Full HP | Full SP | Fire | Ice | Lightning | Light | Dark |
|--------------+--------+----------+---------+---------+------+-----+-----------+-------+------|
| Daring Gigas | 24 | Strength |     928 |     100 |      |     |           | Nul   | ?    |
** 5/25
On this date you will get a cutscene before school introducing you to a new job, the Tutor job. This is a job that you can go to at night, tues., thurs., and sat. it pays very well (10,000 yen per day), but requires high *understanding*.

Marie is also available to go out this day.
** 5/26
There is a quiz in class today. This is a fairly easy question as long as you are paying attention. If you want to skip the dialog, however, the answer is, "attendance logs".
** 5/28
The mail order show starts. You can order things from the TV in your room. Watch for deals on Sun., Mon., and Tues.
** 5/30
There is another lecture on this day, but there is no quiz and it does not affect what is available for you to do this day.
** 6/1
Rain sets in today. This is the game's warning that you will need to hurry and save Kanji. Marie is available this day as well. Also, it is good to remember that /some/ part-time jobs and clubs cannot be done on rainy days.
** 6/4
This is it! This is your last day to save Kanji. You have not made much progress in his dungeon by this point it will be a fairly difficult fight. My strategy, however, was to get to the last floor by 6/3 that allowed me to take on these boss's with full HP/SP. The results of the analysis are below. Keep in mind that these guys appear to target female party members more, have opposing weaknesses, and can block each other's weaknesses. This makes for a challenging fight even on lower difficulties. The fight is far from impossible especially for a fully rested party.
| Names        | Lvl | Archon  | Full HP | Full SP | Fire | Ice  | Lightning | Wind | Light | Dark |
|--------------+-----+---------+---------+---------+------+------+-----------+------+-------+------|
| Shadow Kanji | ?   | Emperor | ?       | ?       | -    | -    | Dr        | -    | Null  | Null |
| Tough Guy    | ?   | Emperor | ?       | ?       | Wk   | Null | -         | Str  | Null  | Null |
| Nice Guy     | ?   | Emperor | ?       | ?       | Null | Wk   | -         | Str  | Null  | Null |

One final note: These bosses can cast poison and rage on the whole party. In my playthrough rage seemed to effect the female party members while males were less effected. Poison appeared to work the opposite. I'll update this when I have a chance to test it in other playthroughs
** 6/5
Kanji returns! You will now have a few cutscenes to go through where the party will welcome Kanji to their group and discuss the case thus far. Congratulations on finishing the bathhouse!
** 6/6
A lot is about to happen and yet hardly anything happens. Here's what I mean. Over the next several days nothing happens on the midnight channel and nothing new happens in the TV world, however, a lot of events and story notes will take place. At the moment the party will just discuss changes to the killer's MO and other notes about the case to this date.
** 6/8
There is a lecture today. There will be a question, the answer to which is "balance beam". After the lecture you will begin discussing getting a motorcycle license.
** 6/9
You'll get your license today and you are gifted a scooter. You can practice riding it and unlock other areas to travel from doing so.
** 6/13
This is the first day of summer, yay?
** 6/15
There is a quiz this day too, the answer is "cheerfulness in a group". You will have a pick up (as in pickup a girl) contest after school today.
** 6/16
The girls go shopping to prepare for the school camp out.
** 6/17 - 6/18
Camp out day one, it should be noted /none/ of your usual ways of spending time will be available, its all story at cutscenes, just sit back and let the game hold your hands for a bit
** 6/20
Rise makes a TV announcement. The party suspects she might be the next victim. There is a quiz this day to, the answer is "Meiji". There is a special boss in the bathhouse. Things are about to shift, so this may be your last chance to take care of it.
| Names              | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|--------------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| Intolerant Officer | ?   | Emperor | ?       | ?       | -    | -   | Wk        | ?    | Null  | Null |
* Marukyu Striptease
Rise Kujikawa is an idol from the small town of Inaba, where the story is taking place. As an idol, Rise has to conform to a certain personality archetype, but is actually quite different from how she appears on TV. As a result, she is struggling with her true self and the "manufactured personality" she has as an idol.
** 6/21 - 6/23
After the party begin to suspect that Rise may be the next target, she begins to appear on the Midnight Channel. Unlike before, they will immediately identify her. Like before, they will not be able to save her, so it will be off to the TV for you.
** 6/24
Like with Kanji, Teddy has difficulty pinpointing Rise in the TV world even after her program begins on the Midnight Channel. He asks you to go get more information about her. You need to ask around town to find out more about Rise. You can start with either the tofu shop she works at where the old lady tells you about the paparazzo hanging around or you can start at the school where you can speak to a chubby man at Practice Building 2F who tells you a bit more about Rise and also advises you to speak with someone in the media. Either way you will eventually have to speak to /both/ of them. Once you do, you will be advise to look for paparazzi at the flood plain. You won't find any yet, but the "kind man" there will advise you to look tomorrow.
** 6/25
Now you can head back to the flood plain and find the "photographer" (if you don't want to/can't do this today, note that the "photographer" is only there Tues., Thurs., and Sat.). Give the man two pieces of info about Rise, basically all options except that she is in town. With this, he gives you enough information that Teddy should be able to pinpoint Rise. Take this information back to the TV to unlock the dungeon.

** 6/26 - 7/9
You have a couple of weeks to save Rise from her shadow. Marukyu Striptease, like the previous two dungeons is roughly 10 floors with a final fight on the next floor after that. There are many different types of shadows and they will begin introducing shadows that nullify or even repel certain elemental attacks. Stay on your toes. Keep a full and diverse party. You can decide what role the main character plays, but I kept him as my Lightning, Dark, and Light damage dealer. Also relay on the analysis option to keep everything sraight. You don't want to accidently use a repelling element. At about 7F you will be met with a sub-boss. This fight shouldn't be too difficult, but a fresh party would be helpful as it will likely start with stagnant air (to increase suseptibility for ailments) and will attempt to poison your party. Here are its full stats as reported by analysis after scanning for weaknesses and strengths.
| Names         | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Amorous Snake |  33 | Lovers |    1012 |     148 | -    | -   | -         | -    | Null  | Null |

After this fight the floor mazes will start to get a bit more complicated, and you'll be dealing with some more difficult shadows. Be very careful as one of them will repel dark, if you aren't careful you could end up instant KOing yourself (leading to an instant game over). After completing ten floors, I suggest leaving and coming back another day so you are well rested for a two part fight.
| Names       | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|-------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Shadow Rise | ?   | Lovers | ?       | ?       | -    | -   | -         | -    | Null  | Null |
Shadow Rise has no weaknesses, but is more than capable of taking advantage of your weaknesses. She is able to use any basic elemental attack. I did not see evidence of light or dark attacks. At a certain point in the fight she will begin to analyze you (yeah I didn't see this coming at all). When this happens you will be unable to hit her. Just keep guarding for a few more turns to trigger dialog and a suprise twist.
| Names         | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Shadow Teddie | ?   | Moon   | ?       | ?       | -    | Dr  | -         | -    | Null  | Null |
It is after the twist that the real fight begins. Shadow Rise, was pretty easy actually, now its time for Shadow Teddie! This will be a real fight. Like Shadow Rise, Teddie has no weaknesses. He will also attempt to lower your party's defenses right away and inflict other ailments. Eventually he will begin charging attacks. At these points, make sure all party members are guarding when the message "Shadow Teddie is charging up" is displayed. You will block the attack fully. Careful though! Shadow Teddie will attempt to inflict dizzy on a party member, or two, before charging up.

** 7/4
There is a lecture and a pop quiz today. The answer to the question is "Pascal"

** 7/7
Another lecture and quiz this day. The answer to the question is "The Decleration of Independence"

** 7/10
So Teddie joins the party in a new capacity and new form (yeah that was also surprising) and our super cute idol Rise will join the party. She replaces Teddie as your analysist, however, so don't expect her to be fighting alongside you. Your homeroom teacher was murdered last night and his story appears today on the news.

** 7/11
You get a new homeroom teacher. Brace yourself for that, by the way, she isn't exactly any better than your last. Also, brace yourself for a barrage of cutscenes as everyone discusses the case so far.
