#+TITLE: Walkthrough (Oct onward)
#+DATE: 2023-11-15T21:39:40-08:00
#+DRAFT: false
#+DESCRIPTION: A walkthrough for the second half of Persona 4 Golden
#+TAGS[]: guide walkthrough p4g persona wip
#+TYPE: guide
#+WEIGHT: 2
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: This will walk you through everything you need to do in the second part of Persona 4 Golden!

Welcome!

This is designed to help you figure out what to do on each day of Persona 4 Golden! This is designed to give you a heads up on events happening each day, I will not be telling you what to do each and every day, instead I favor telling you what will happen and how to prepare for each day.

I've started this kind of in the middle of my current playthrough. So I don't have April included, which includes events from the first. For now I'll be pulling from things I've read and my own memory, but the good news is, the first dungeon and the story to that point is pretty straightforward. Nevertheless I will be covering that when I can.

This part is current a work in progress. I am building this as I playthrough the story myself. This is so I can give you a fresh head up on how things will go.

* Haven
** 10/06 - 10/10
This is a series of story scenes that will take your after school time. It will start with discussing with Naoto what happened when they were kidnapped. They know quite a lot of details, but you will still have wait for another victim to come forward to investigate further. After getting Naoto-kun's reports, you will be helping Yosuke and Rise with a concert. The concert is on 10/10, but you'll spend a few days preparing. Just enjoy the scenes. The event even has a nice animated scene. There is one quiz during these day, on 10/08. The answer is pretty obvious, but I'll tell you anyway, it's: chicken. It should be noted that your evenings are still free, so use this time to finish up Nanako's S-Link or spend time with everyone in the evening.
** 10/11
Your after school hours are still not yours. You agree to study with everyone. Naoto will likely ask you to go into the TV when you get back home, but that'll have to wait until tomorrow. Good news is, this means you'll be free to do what you want tomorrow. There is a quiz today too, the answer is: glass jars.
** 10/12
A nice Halloween-themed quiz. The answer is: turnips (imagine carving those!). You'll be notified that a new strong shadow has appeared in the lab. Now is a good time to go back if you don't have anything else to do.
| Names          | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|----------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| Extreme Vessel | ??  | Fortune | ????    | ???     | -    | -   | -         | Wk  | Null  | Null |
** 10/13
Everything is basically back to your normal rhythm. One more quiz, they'll be ramping up since your exams are coming up again. The answer is: ojisan.

** 10/14 - 10/20
With exception of 10/16, which is a Sunday, you will spend the next few days in school answering questions on your midterm exams. You are normally free in the evening, but may not be free during the after school hours. As such, it is a good idea to have fought the above special boss before this date. You could have 10/16. but you will be asked to join a study group, so, if you haven't fought the boss by now, it will be a toss up between enhancing S-Ranks and completing the boss. There will be sometime after exams, however. I'm not going to give you the questions on your exams as the questions and answers can't co-exist in the same area without endangering all of humanity. I will give you the answers though:
| Day | Q1 Answer             | Q2 Answer        |
|-----+-----------------------+------------------|
|   1 | Throat                | The Right edge   |
|   2 | 40 Minutes            | All of the above |
|   3 | Black and White Bears | Ostrich          |
|   4 | ??*                   | Glass Jars       |
|   5 | Fall                  | Plan Resin       |
(* Day 4/Q1 I got wrong in this playthrough, you'll still get top marks for this, but I can only say Wasan Shoujo is not the right answer)

The last day has no questions. You'll be given a general sense of how you feel you did and the day will end. Your exams on now over, hope you did well. You will receive a mysterious letter, which gives you something to talk about with your friends in the morning, but that is it.

** 10/22
You will be given an opportunity to vote for an activity for your class to host during the culture festival this weekend. As this is the first time I played this far, I'm not sure if your choice actually matters. To be funny, I just chose the "group date cafe" let me know if you picked something different and how that turned out!

** 10/24
You get your test results today. If you answered all the questions with the answers I gave you, then you'll get top marks and all of your school friends will be impressed. This will increase all their S-Ranks.

** 10/27 - 10/28
The culture festival will be starting at the end of this week, and guess which class completely forgot about it? Yeah, yours! So, now you'll be spending a few days, including after school hours, preparing for the culture festival. If you have anything you want to get done in the TV do it before now, or you'll have to wait until next week.

** 10/29 - 10/30
The culture festival itself. This is just a compilation of some really fun scenes. You will lose more time and you'll want to be prepared for a long set of cutscenes. There will not be many opportunities to save once the culture festival starts. In fact, your next chance will be after the hot springs visit on 10/30. Make sure you block out plenty of time to get through these scenes!

** 10/31
You'll get an extra day off. You can save and do whatever, but, if you want everyone's Halloween costumes, you're going to have to help Yosuke out and Junes. This whole thing is a wash and all you get are the outfits though, so its up to you.

** 11/01
Nothing of note really, just a quiz, the answer is: geometric shapes

** 11/03
You'll get an extra day off, just don't count on school activities this day.

** 11/04
Another quiz (the answer is: Cuckoo), another person on the midnight channel. Though no one is certain yet, it is pretty clear who the next victim is going to be.

** 11/05 - 11/20
The story is beginning to reach its climax! There are a lot of scenes this day and little else. However the culprit of all the murders (save one) as well as everyone being thrown into the TV world is identified during these scenes. The culprit also kidnaps his next victim. With all this happening so quickly there is no need for any further investigation. Head into the TV and begin your search for the culprit and his next victim! Starting now, Nanoko will no longer be available, be sure her S-Link is maxed by now.

Once you reach Paradise #7 you will encounter your first sub-boss. This is not a difficult fight, but be prepared nonetheless!

| Names         | Lvl | Archon  | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+---------+---------+---------+------+-----+-----------+------+-------+------|
| World Balance |  63 | Justice |    1200 |     100 | -    | -   | -         | -    | Null  | Null |

You will confront the culprit on Paradise #10. This fight is a bit more tricky. The main boss has a full range of elemental attacks, so be mindful of everyone's weaknesses and do your best to cover them with shields or items. It appears the "atmosphere" will change before the boss switches elemental attacks. He also has a very power physical attack and can control your party members. Be careful!

| Names         | Lvl | Archon | Full HP | Full SP | Fire | Ice | Lightning | Wind | Light | Dark |
|---------------+-----+--------+---------+---------+------+-----+-----------+------+-------+------|
| Kunino-sagiri | ??  | ????   | ?????   | ???     | -    | -   | -         | -    | Null  | Null |

** 11/07 and 11/10
Not much happens at school during this time. If you have any job or club S-Links to finish now is a good time to do this, especially if you aren't having any difficulty in the dungeon. It is also an excellent time to work on skills. On these two day, there are two quizzes, the only thing you have to worry about until 11/20. The answer to 11/07's quiz is "no country" while the answer to 11/10's quiz is "Namib".
