#+TITLE: Eri Minami (Temperance)
#+DATE: 2024-03-12T18:33:48-07:00
#+DRAFT: true
#+DESCRIPTION:
#+TYPE: guide
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

I won't give too much information about Teddie. Teddie is Teddie and Teddie is a party member and persona-user, somehow. You'll automatically start and rank this social link during the story.

* Availability
Depending on how you look at it Teddie is not really ever available. You don't get the option to hang out with him outside of story events and other S-Links. This isn't a bad thing because it is actually one of the easiest S-Links to rank as it happens automatically during normal story events.

* Dialog Options
None of the dialog options will give you extra points or rewards since all ranks happen automatically. Again this makes it easy to rank up as it requires no interaction from the player. You will automatically rank up this S-Link on these dates:
- Rank 1: 4/17
- Rank 2: 4/30
- Rank 3: 5/18
- Rank 4: 6/6
- Rank 5: 7/10
- Rank 6: 7/10
- Rank 8: 10/6
- Rank 9: 11/6
- Rank 10: 12/3

* Rewards
As well as unlocking the ability to Fuse Helel, Ranking up this S-Link grants new skills for Teddie. As this happens automatically, this is mostly just for information purposes.
- Rank 1: Protect
- Rank 3: Follow Up
- Rank 5: Assist
- Rank 7: Recover
- Rank 9: Endure
