#+TITLE: Am Not Lazy Am Busy
#+DATE: 2024-01-18T18:54:47-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: news personal
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

I am committed to making sure there is something new on this site every week even if there isn't much! There will probably be some things coming up next week, but this week was quite a bit busier than it appeared on screen, particularly today. I still have a few things to finish, but at least work is over 😅

* Only a News Article?
Yes, I have to apologize, I had a lot to do this week for work and school and those are all just a bit more important than this site. I did /start/ a few things that will hopefully make it up next week, but they are not in a completed state so you won't see them this week. There is this article though so at least I have something. At least I can be here to tell you what happened.
* Busy Week is Busy
We are in the second week of courses at the university for this term. I have an assignment to finish this week, plus a lot of reading. The reading took a lot longer than I originally thought and I fell behind in readings pretty quickly. I managed some leisure time, but that went out the window today. Still, I was able to get a few things started for a new section detailing a character that I am working on with friends in a D&D-like campaign. Unfortunately that content quickly fell aside as I fell behind in my readings this week and, there is, of course, still the matter of the assignment, so they weren't ready by today.

Work was also very busy. I had a total of four meetings during the week and *two* of them were today. This made for one heck of a work week, plus the last one today went over! So yeah very busy. I hope next week will be a bit lighter in terms of both work and school.
* Meet Keyrie
Keyrie is a noble wood elf from a low noble house. She has led a privileged life, but wants to prove that she can be independent so she sets out on adventure to prove she can take care of herself. Without actually knowing some basic things, like how much things cost and how much her money actually worth. You'll see more of her once her section is up in [[{{% ref "adventures" %}}][Adventures]], but she is a character I'm running as part of a D&D-like campaign with my sister and her girlfriend. I had fun creating her and ran one chapter already. I haven't finished putting the summary together yet. I also starting drawing a portrait of her. I'm hoping both will be up next week, so look forward to that!
