#+TITLE: A Case of the "Mehs"
#+DATE: 2024-04-25T16:03:18-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Do you ever just have times in your life, or maybe just a day or a few hours, where you just don't want to do /anything/? Like no matter what it is you are doing, even if its something that usually brings you a lot of joy or something you're normally really passionate about, you just can't seem to enjoy doing it. I'd honestly like to know if I'm the only one 😅 Well this has happened a few days this week and rather than coming up with something to update the site with, I decided I'd talk about this a little and the struggle with this one is so real for me.

* The Sims 4 and "Burnout"
One of the games I have played is The Sims 4. I'd love to say that [[https://onigirionegai.info/~miu/][one of the members]] of our little group here at Onigiri☆Onegai introduced me to the game, but, to be honest, my sister introduced me to The Sims 4 much earlier and I had played The Sims 2 a long time ago. Also I don't have any guides on this game, and don't plan to. There are already a lot of [[https://www.carls-sims-4-guide.com/][The Sims 4 Guides]] already out there and I don't see how I can add anything there. One of the way people would play the game would be just grind skills or job tasks out. This cannot be done effectively any more thanks to "burnout".

So Why I am talking about The Sims 4's "Burnout" this week? Well, its kind of because of the way it works. When you try to grind a specific skill or task a moodlet pops up depending on the type of skill or task your grinding. This moodlet is "Creative/Mental Fog". If you don't do something to change up your sim's life, this will eventually lead to "Burnout" which will prevent your sims for gaining any new skills or performance in their jobs. I'm not sure about how accurate the game is to real life burnout, but this first moodlet might be what I experience that I call the "mehs"

* Mental/Creative Fog = The "Mehs"
The moodlet's descriptions are kind of spot on for what I'm feeling. It is kind of like my mind is in a fog and I feel distant from whatever it is I'm interacting with. This could be my website (I'll talk a little bit more about that later), my work, or even live streams, or games. In fact, I think the first time I noticed this was that I felt distant from all the people I had managed to socialize with during COVID. Some of these people are people I would lose contact with, but others, I still sometimes feel distant from even when I'm regularly talking or chatting with them. I even feel what I would call "Dazed" at times and this is how The Sims 4 categorizes this moodlet.

* The "Mehs" and This Site
You'll see that, once again, this is the only update I have this week. I apologize, but I think this is needed. When I get into this state, I have a hard time focusing and creating something good. Maybe I'm the only one who will ever read this or see it, but I want to make sure that whatever I put out is good. That said, I have some news that is kind of painful and sad for me to admit. That is I don't know if I can keep making sure that the site is updated every week 🥹

For the past several months (over a year really), I have ensured that /something/ within the site was updated every week. Sometimes that meant literally just a new blog/news post, but I tried to make sure at least one /other/ thing was updated too. I am proud that I had kept that going over those several months. It was not easy sometimes, and because of this I have decided it is okay to skip updating the site when I absolutely need to. I'm still going to keep my usual todo list for the site and have it "due" every week, but, if I really can't bring myself to update it or if I honestly think I need to skip it, I will do so from now on. So, all I'm really saying is, don't expect an update every week anymore. I'll try, but I'm not guaranteeing it.

Thank you!
