#+TITLE: End of Year Announcements
#+DATE: 2024-11-03T15:40:42-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site stream news
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Last week I [[{{% ref 'news/2024/announcing-announcements.org' %}}][announced some announcements]], well it is finally time to actually make those announcements. Technically, I already made them they were in a stream that is available on the YouTube channel, but I thought I should also right them out here and in the Discord. Though I already wrote them out in the Discord. It's much easier to post things quickly there, which I may have also mentioned last week. Anyway what I announced was:
1. New Emoji available on Discord and Twitch
2. A new outfit is coming!
3. Fantasy Friday is going away for now
4. A new motion comic!

* New Emoji on Discord and Twitch!
I made affiliate just before Spooky Month started! As affiliate I can now offer everyone cat tweats on Twitch, but I also got access to emote slots. If you have followed by art streams during Spooky Month, you may be aware that I was working on these. Well they have been approved and are now available on Twitch and Discord. I thank everyone who has supported me in making it to affiliate!

* New Outfit!
Yep I know I literally just banished Ghost Cat, but she was never going to be the only outfit I make for my model! I'm not going to release too many details now, but I will say the outfit is going to come out 3 Jan, so maybe that will give you a hint. I'm sure you'll also love it!

* Fantasy Friday is Going Away, For Now
I need more time to focus on other projects so I made the difficult decision to cut back on streaming just a little bit. Basically you will now only be guaranteed two streams on Twitch (Maker Monday, and Throwback Thursday) and two random game streams on YouTube. That isn't to say that I won't ever stream five or more days again and it doesn't even mean I won't bring back Fantasy Friday at a later date, but, for now, it's gone 🥲

* The BEEG Announcement
These weren't even the huge announcements. I mean making affiliate is pretty big, but still not BEEG, if you know what I mean! I'm making a motion comic to go over my backstory and give you all an idea of who Yayoi Shizumi is!

This motion comic is first going to be released as a YouTube video, as I also mentioned last week, but we'll be exploring other places and ways of releasing it, including right here on the website!

I'll be devoting my next several art streams as well as some additional time off stream to making panels for the comic. I'm really excited to branch out in this fashion and hope you will enjoy the story and support me in telling it! 💜
