#+TITLE: Little Update for Now
#+DATE: 2024-02-01T18:36:39-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Yep just a little update this week, but at least I have some actual new content. It has been awhile since I updated any of my stories, but hopefully I'll get something up soon. With all that has been going on, I really haven't been in the mood for writing. In fact, if Keyrie wasn't something I had already started and nearly finished I wouldn't have finished that either. I do have another project I had started, but haven't worked on because I haven't felt like working on it much either.

* Drawing and My Mood
There /used/ to be a time when I would force myself to work on a drawing everyday once I started until it was finished. I look back at some of those pieces, which are now locked in an archive somewhere, and I hate them. I can see where I got bogged down into having to work on 'em even if I really wasn't in the mood and how that really affect the end product and not in a good way either.

Now I don't draw when I don't feel like it. I /might/ force myself to finish something if its really close to being done. This is because I'm usually just finishing up details or probably just compiling the final image. I don't need to focus much on that, so it usually can't be impacted by my mood. Any other time, even if I'm getting paid, I won't work on something unless I feel like working on it.

I don't want to sound greedy, but money does help keep me in the mood. I use it more as a reminder that I'll be rewarded at the end which can help motivate me even if I'm not otherwise in the mood. So, I'm likely to keep working a bit more on an illustration if I'm getting paid.

* Writing and My Mood
Writing is kind of the same though I often get legit writer's block when I'm really not in the mood for writing. Of course I mean like fiction writing when I say that. I usually don't have the same problem with mood when it comes to academic/non-fiction writing. It does make it so I actually can't write unless I'm in the mood because nothing will come or I'll write just a couple of sentences and forget where I was going assuming I even remember anything if I'm reading back from where I left off.

* It's Keyrie!
If you've been lurking in my adventures section, first get out of there. It isn't safe! Just kidding. Second, you probably noticed the [[{{% ref "adventures/keyrie/" %}}][Journal of Keyrie Cildor]]. If not check it out! She's a character I'm playing D&D with and there will be journal entries that summarize the D&D story. I'm still working on finishing up the first one, but it'll be there shortly. We are also still in the middle of Chapter 2, so I have to wait until we move on to chapter 3 before I write that one up. I'm taking more detailed notes now, so it shouldn't take as long and I don't have to worry as much about writer's block or whatever for that.

Well, aside from that, her portrait is up! Check it out! It's in my [[{{% ref "gallery/creations" %}}][creations]] gallery. She came out really cute. I'm still playing around with my new art style. Not sure I'll keep doing the eyelids the same way but they look good for her.

* Other Things
I'm sorry to say, it's been over a week since I touched Persona. I'll try and get back into it soon. I wanted a bit of break, but I think that's gone on long enough, more than long enough in fact. I know I'm basically on the Golden content and its extra dungeon now, well not quite. You see they gave you all this time to work on SLinks, and well, that means there's not much to do every day. That's why I wanted a break, but I really should get past that part so I can move on.

Aside from that there is Clannad and my VNs. I've still been playing those, but not quite as much. Mostly just sticking to Clannad at the moment. I don't play them every day either. I think I'm getting to kinda a sad part of the story, but we'll see how it plays out. Just started that part.

Anyway, doing much better since my rant. This site is still on my mind and I'll do what I can. School work is a bit more intense this quarter. I'm really looking forward to my next break!
