#+TITLE: More Commissions Please
#+DATE: 2024-02-29T17:59:28-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

No, this isn't a call for you to commission me more, though I wouldn't mind if I got more commissions. I just wanted a funny title for this week's news article and I do you have another commission done so, yeah let's just have some fun! Of course you can still give me more [[{{% ref "commissions.org" %}}][commissions]] 😆

* I Haz DA SNACKS!!
Yes I do love snacks! I usually have nuts, or pocky, or Swedish Fish, or even Skittles Gummies to snack on throughout the day. Snack list day is my favorite day. It's where I go and take inventory of my snacks, make a list of what I need, then go and buy them. I'm a sucker for snacks, but that's not what I'm talking about here.

What I'm talking about is the [[{{% ref "gallery/commissions/" %}}][commission]] I just finished! Jade, a vTuber I worked on, needed a start card to display before the stream actually began. In reality, we both like snacks so we came up with the idea of having us getting snacks before the stream started. I think it turned out pretty good and my avatar is just sitting there in haven holding (and eating) too much pocky. I'd be in heaven too. This was a lot of work, but also a lot of fun.

* The Persona 4 Walkthrough
I'm finally through all the annoying S-Link building sections of P4G before the Golden dungeon. In fact, I've been working my way through it now. Not sure how big it is yet so I dunno how long it will take, but I think I'll be moving on to Persona 3 soon. Still don't have Persona 3 Reloaded though so it will probably be P3P. Anyway the walkthrough it up to the point where the dungeon starts. I'll have the information on the dungeon itself up soon, probably will wait until I finish it, but as I don't know how long it is, I /might/ have it up before that. I'll say right now though, it is different than the other dungeons.

* Keyrie's Journal
Just wanted to point out that I have started the second chapter of Keyrie's journal. This chapter was done over multiple sessions and is rather large so there's a lot to go through. I'll try to get as much of it done as I can before this goes up, but, as you can see, I don't really have a lot of time before it does. Still I'll do my best, but it may be next week or the week after before it shows up here as I will have to finish and proofread it before that happens. Just wanted to update you and say I am working on it!
