#+TITLE: Moar Persona News
#+DATE: 2024-04-18T18:03:05-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

After finishing the easiest S-Link guide ever, I have to admit I have not really gone back 😅 I have mostly been playing through Persona3 Reload and P3P. Of course I still have work to do. Fortunately, it seems that the amount of work as decreased a bit since I am more used to the new processes. I also am still working on some stories and ADVENTURES, but most of that work isn't seen until I'm ready to release it 😅

* Persona 4 Guides
So Teddy, Marie, Nanako, and Rise were the four S-Links I focused on most. Okay, I should say that Marie, Nanako, and Rise were the three S-Links I focused on most because you don't really do anything with Teddy. Now I'm at a loss as to where I should go next. I might look at doing some of the jobs-related S-Llinks and maybe put together a list of jobs and clubs, the rewards for each and the like for the next update. Let me know if you have any suggestions though. I am planning on working on that instead of my DnD adventures next week so there should be at least /something/ up for P4G next week.

* Persona 3
Well I have some interesting observations about Persona3 Reload and P3P. I'm thinking that I might do a comparison page for them instead of a review when I'm finished. My first thought though is that my Persona3 Reload is a lot more fun to play than P3P. I don't know if its just the way the story is told, or the lack of some of the modern gameplay elements that Persona3 Reload introduces, but I like the time I spend in Persona3 Reload while P3P seems a bit less enjoyable. I hope I'll have a more concrete comparison for them when I'm done and can really discuss why I feel this way, but that's the observation I have about the difference between the two.

Also, I wanted to say, I don't know if its the way I'm taking notes for the guides or if its just a straight fact, but it seems like less noteworthy things happen in P3 in general than in P4. Like P4 seems to bombard you with quizzes for example while P3 had like four so far, or something like that. Also P3 had the gatekeepers, which are like sub-bosses kind of like those you would find in some of the dungeons in P4 before getting to the end, but they. This could just be the fact that I am playing on easy mode and need to up the difficulty, but it doesn't seem to have the same challenge. I don't know, maybe I'll look into the harder difficulties and see if they're more challenging. Its almost to easy to win and I don't want to not include their information (because I haven't been as the seem so easy) just because I'm playing on easy mode. Let me know what you think though.

* Work is Less Worky Again
I still have more to do for work than I did last quarter, but it is a lot more doable than I thought. I kind of figured that I was just not used to the new procedures and I think that's the guess. This week was definitely easier than last. It isn't as easy as it was last quarter, like I said, there is still more to do after all, but it isn't as bad as I thought last week.

There is more time involved though. This has left me with little time for my other things. You'll see I wrote this kind of late compared to the last few posts because I had extra work and extra meetings. I don't have as much time to work on stories and art as well. Hopefully I'll find a way to balance everything, especially since I didn't manage to watch my anime the past two days! I'll get there, still some adjusting to do I think!
