#+TITLE: Needing Support is Not Being Lazy
#+DATE: 2024-01-25T18:24:44-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site personal news rant
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

This is going to be a bit of a rant. If that is not why you're here and not the type of content you want to see from me, I fully understand. Please feel free to skip this article, even if it is still the only update this week. Before you do that though, I'll let you know a little about what happened and why this is, yet again, the only thing updated this week.

* Another Week, Another Update (or lack there of)
I will apologize. My goal was to always have an update for the site ready every Thursday. Now, technically, there has always been an update because, at the very least, there is a new article here so that counts, but it doesn't really reflect what I intended. I wanted to make sure there was real content too, that has been lacking lately. If you read my post from [[{{% ref "news/2024/am-not-lazy-am-busy.org" %}}][last week]] you'll know I was quite busy, well this week was kind of some fallout from that. I won't get into details here, because that is where the rant will begin. So I'll save that for the next section for anyone who wants to skip it.

Now I will say this. I want to try and make sure I have some real content up every week too. I'll be doing that next week. I am almost done with Keyrie's portrait so, baring any more unexpected fallout, I should have that up at least, but I will re-double my efforts to have more content up. I still have Persona 4 Golden to finish and Persona 3 Portable and/or Reloaded to start.

* RANT (Start Skip Here)
So I'm going to say this. While a majority of professors I've worked with are great, there are some who don't seem to understand what it means to teach. Here's my teaching philosophy for some context.

Every learner has unique experiences and go through unique transitions throughout their lives. I trust that each learner is doing there best within their unique circumstances in life. Each leaner is capable of excelling and no one should be compared to others or should have to prove themselves to their instructor. An instructor's job is to instruct, and support the learning process. If the learner fails to learn, than the instructor has failed. Learners and instructors work together to ensure the learner's success throughout a course.

What grinds my gears is when I work with an instructor that has the exact opposite philiosphy and thinks that each students needs to prove themselves worthy of their grade and often without help or support. Like the learner is unworthy of their time and attention. I am dealing with one such instructor at the moment and it is making things very difficult for me in terms of my school work. I am a doctoral student I have already proven myself, thank you, also I shouldn't have to prove myself to you or anyone, your job is to help and support me. I am a hard worker and no one's /burden/!

* END RANT (You Can Start Reading Here Again If you Want)
So that's what I've been dealing with and yes I am using it as an excuse for not updating this site much this week. I hope you will all forgive me. I take my education very seriously and hope to use it to be a much better professor than the one I am dealing with right now. I think every needs help and support and, if you give them I chance, they'll succeed it what ever you they want.
