#+TITLE: New Quarter More Work
#+DATE: 2024-04-11T12:37:30-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

I think they underworked me last quarter and now this quarter they decided to overwork me 😆 I'm kidding though, but only a little. I /do/ have a lot more work to do this quarter each work than I did last quarter, but its not a terrible amount. I am hoping it gives me a little bit more hours and more money though. I'll find this out on my next pay check.

* More Work
Aside from the meetings and sessions I led last quarter I now take attendance and fill out reports this quarter. This is helpful for both myself and my supervisors, but it is a lot of work that I'm not exactly happy about. I mean it isn't like the documentation and reports I had to fill out in my last job, but its still like busy work and not fun. I guess work isn't supposed to be fun, but I did like what I did last quarter.

I'll say I might not like some of the reports and busy work, but I still like the job overall. Hopefully I'll be able to get more students to come to my sessions though, cuz I only had one consistent one last quarter and its looking to be the same this quarter.

* Still Have Time for Some New Content!
Okay, not much this week, but I /did/ do something I probably should have just started with when I decided to do Social Link guides for P4G. Teddie's guide! Teddie turned out to be easiest because, everything happens automatically, so I should've just started there cuz there isn't much for me to write about 😆 Anyways, its done now so now that's four guides. Still many more to go.

As for as Persona3 Reload and P3P, I do have a few new things in my notes but, I was trying to get P3P caught up a bit so I haven't written them in the walkthrough yet. I'll do that next week though.

* Next Week
Hopefully I'll have P3P and Persona3 Reload walkthroughs up-to-date next week, but I'm not sure. I'm hoping that, now that I have a feel for the reports and other busy work that I have to do that they won't take quite as much time. I'll let chu know next week 😉
