#+TITLE: On Localizations
#+DATE: 2024-02-08T18:15:42-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site news rant p4g anime
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

I have 10 max S-Links in Persona 4 Golden \ ( ^ o ^ ) / Just had to say it, lol. That should give you an indication that I have started playing it again. which I have. I'm mostly just working on my S-Links and trying to get through some of the extra post-game content while I wait for things to pick up again. You would think I'd be used to this kind of thing knowing that I also like visual novels, but, for some reason this sort of thing is just not so fun in Persona. Its a big part of it and part of the appeal for some, I suppose, but, in this quantity not so fun. Actually Persona got me thinking about something else lately. So I guess it's time for another Yaya rant 😅 Feel free to skip the first heading if you just want the site updates. Though I promise this rant will be less angry.

* Localization, what is it and why should we care (Mini-RANT)
So right off the bat I'm going to say something, localization is /not/ translation. I think a lot of people are a bit confused as to that fact. Translation is where someone who speaks and/or understands two languages tries to do their best to interpret the meaning of someone speaking or writing one language into the other language. The focus is on capturing as close to the exact meaning as you can and communicating that to someone who does not understand the language.

I did this when my parents came over to the Philippines. They speak a language called Tagalog there and my parents only knew English. I would do my best to interpret what they were saying in English and communicate that to people who only spoke Tagalog, or spoke Tagalog better than they spoke English. I also did it in reverse. This was a daunting and difficult task, but it is not the same as localization. While localization often require translations they may make changes so that their target audience is more able to understand the situations and dialog of a game or show.

As a translator if I came across a world or phrase that had no bearing on the conversation and no direct translation. I would leave that alone. In Japanese this would often mean that nicknames, honorifics, and the like would just be left as is. So in Persona 4 we had the character Rise. Rise was an idol before she enters the game and her name as an idol was Rise-chi. I would leave this alone as a translator, but a localization might change this. -chi isn't really an honorific, but kind of a cuter version of -chan. It has the affect of making the name sound cuter. A localizer might want to duplicate this affect for a more main stream audience and one did, that localizer chose to change this from Rise-chi to Risette. Risette keeps the name Rise, but makes it sound cuter to a Western audience just like Rise-chi keeps the name but makes it sound cuter to a Japanese audience. They serve the same purpose.

The question that people might raise is, is this okay? I think, to some extend it is, but it really depends on who you think will be consuming the localization. Is it going to be mostly mainstream watchers or players in a Western audience or is it going to be fans? Is it going in a dub or in text? Western anime fans who might want to consume the content because they like Japanese culture might not appreciate even such a subtle difference and this is why I don't think it has a place in either unofficial or official subtitles. This is the audience that is probably going to be consuming the media in that fashion. However, maybe its okay to do these changes in a dub because more mainstream fans are likely to watch it and might be confused.

Of course this is referring to relatively minor changes that don't really affect the overall meaning of the conversation. More major changes would need to be even more carefully considered and one should consider the intent of the original artists. Original artists also should not feel they have to cater to an audience that they are not targeting. Large changes especially ones endorsed by the original artists risk damaging the identity of the original content and diluting the original culture. That's just my take on this though. Feel free to give your opinion as well. END RANT!

* Persona 4 Golden guides
As I mentioned the guides are going a little slower because I'm just not enjoying the game as much right now. I'm sure that will change soon and I do look forward to starting Persona 3 Portable. Still waiting to see if Persona 3 Reloaded will be put on sale, but it was just released, so probably not. Also, apparently AAA games are not $70 😱I won't rant about that though, because one rant is enough for a post, but dangit! I did manage to get a hold of Persona 5 Royal though. I already owned the game (the original Persona 5 release) on PS4 so I didn't want to spend full price for it just because it was Persona 5 /Royal/ now and available on PC so I waited until it was like half off and bought it then. I'll start that one again and go through the Royal content for the first time after P3P.

The guide is up to date though. I brought it up to where I am now even if it is only a few days from where I left it. Made a typo correction too so check it out.

* New Commission Coming Soon!
I started another commission. I don't have much more to say about it. You'll be able to see it within a week or two in my gallery. Until then it'll be a secret 😉 Sadly, it is taking over right now so it'll be another few weeks before I work on my other projects, including episodes of RE[BASE]. Hang in there on those. Worse case is I'll work on them a lot during my next break from school!
