#+TITLE: Persona 4 Golden Finale
#+DATE: 2024-03-07T18:48:09-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Its almost official. I am just about done with Persona 4 Golden. The walkthrough is up to the point just passed the Golden dungeon and that is the last dungeon I will be including in the walkthrough. I hear tales of a hidden dungeon, but I will not be testing those tales just yet nor will that be included in the walkthrough. So basically, the walkthrough is done. There is maybe a day or so left and that will be uploaded next week, but this begs the question of what is happening next.

* After Persona 4 Golden
So now that I am basically done with Persona 4 I'll be looking at how I can finetune the walkthrough. My goal will be to get it down to one page and remove anything in the guide that is not strictly part of the main story or the dungeons. Anything about the availability of characters or jobs or skills or any of that will be in their own sections instead. I hope this will be enough, but will also be looking at what other information could be removed, moved, or condensed as I go. I will also be using this to inform the next game walkthrough I write, particularly the next /Persona/ game!

You can also look forward to a review. I'll start writing a review of Persona 4 Golden very soon and it should be up by next week. Even though the guides are up I want an opportunity to give my opinion on the game and its story, so a review will also be out. As usual you'll also be able to discuss the review on my discussion area!

* The Next Game
It is looking like Persona 3 Portable will be the next game I start and the next walkthrough I write. I still don't have a copy of Persona 3 Reload, and, unless something changes before I put the finishing touches on the P4G walkthrough, I won't be able to play that version of the game, so I'll play P3P instead. In the future, maybe I'll at least make notes as to what is different between P3R and P3P, but, for now, it will be just P3P.

* Some Life Stuff
Yeah this is a little later than I like. I have had a busy week this week and wasn't able to do much other than work and school. I still have not quite made the progress I wanted to on the assignment for this week in school, so I have a lot of work left to do. Hopefully taking the time to write this won't hurt that much.

Also, next week will be just a busy, but it isn't as important. Just know if I somehow don't have an article out next week there will still be updates, like the Persona 4 Golden review and finishing up the walkthrough. Its like I will just be a bit too busy to write a news post too. I hope you'll forgive me, but, who knows, maybe I'll still get it all done.
