#+TITLE: 2024 Annual Recap
#+DATE: 2024-12-29T11:51:20-08:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]: site news stream recap reviews guide D&D school
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: As the year comes to a close, Yayoi Shizumi, your fairy cat princess, looks takes a chance to look back and see where she has grown, opportunities she's had, misteps, and more! What will she learn to help her in 2025!?

Has it actually been three years since I started this site? The oldest article seems to be dated 12 Oct 2022, so it hasn't been three years, at least not in this form, but it we're it /is/ over two years old!! I've been fairly deligent at updating this site weekly for that entire time and that has generated over 8 pages of articles! What did I feel those pages with this year? Well, a lot happened!

* Reviews and Guides
I started this as a place to post my thoughts on some of the video games I play as well as helpful (at least I hoped they were helpful) guides for some of the more complicated games. This year hasn't seen much new content in this area. I did complete the Persona 4 Golden walkthrough and /some/ of the social link guides. I also started Persona 3 and Persona 3 Reload guides, but than I got a brillient idea, which I don't think is actually very brillient ( ^ ^ ;

* Galleries
My second goal was a place to showcase my art. I am off deviantART and I didn't want to start another gallery on some other service, so I made galleries right here!

This year I was not so diligent at updating the galleries. I think it is mostly due to forgetting what I have and have not put in them. Fortunately, if all goes well today, they should all be up-to-date now!

Over the next year I plan to add a lot more to my creations gallery as I work on artwork of Yayoi for thumbnails and schedules. I still have a comic I am trying to get out sometime next year too, but I really want more Yayoi art!

* D&D and Stories
Speaking of Yayoi, well, that's me, but that's also a vTuber model that I stream with. Its me, in digital form. Did you know there was a fictional vTuber I made? Her name is Nagisa and she was part of a large story called Re:BASE. I haven't done much work on this story this year. I did kick it off. The story was supposed to be a series of short, mostly self-contained stories that would build into a larger narrative, think something like old serialized TV shows. The reason I did it this way was in case a forgot about it for awhile. It wouldn't matter, because the stories /could/ stand on their own for a bit.

I also started a D&D compaign with Ya-nee, but, well, that kind of fizzled out. Things on both ends got busy and the compaign wasn't working. Ya-nee was going to re-work it, but we never got back into it. Maybe I'll poke her next year and see if we can get back on it. Nevertheless, I did start Keyrie's journal, which is a new addition to the site this year!

* Streaming!
The biggest part of this year was that I started streaming. Yeah, with that vTuber model I mentioned. In fact, I made that model! My art has grown a lot as I'm mostly an art streamer, but I also had the idea (the maybe not so brillient one) to stream some of the games I wanted to make a guide for so I could just go back to the archive and right the guide as I review instead of as I play. Now I have several hours of archives to watch to make the guide though ( ^ ^ ;

I did go pretty hard at streaming in the beginning, but now have slowed down a bit. I made affiliate on Twitch and started streaming on YouTube as well. I enjoy streaming my art and playing games on stream too. If I were to pick a platform to focus on it would, probably be YouTube as I prefer it to Twitch. Twitch is where I make money though, and that's a concern at the moment, so I'm not leaving Twitch anytime soon, but that leads us into next year.

* 2025!
A new outfit is coming! Actually, I'm planning four new outfits for 2025 for my vTuber model. The first one is basicall already done and will be released soon. The other three will be released throughout the year.

I am also looking to streamline my streaming operations. I am not leaving Twitch, but my Maker Monday art streams are. To make things easier on myself, and you, my kittens, I will be streaming on YouTube, Monday and Tuesday and Twitch Thursday and Friday. Wednesday and Saturdays are wild cards. I could take the day off, or stream on either platform. Saturdays will be reserved of collabs, as all the people thusfar who have expressed interest in collabs stream o Twitch that means they will likely all be on Twitch for now.

In non-streaming news, I am hoping to revisit some of the dead sections of this site, including the *entire* japanese version! I want to breath new life into every part of the site! I'm hoping I can! I do still work part time and I do still go to school (almost at the dissertation proper!), but I'll make the effort! Here's hoping 2025 is even better than 2024!
