#+TITLE: Spring Break Over
#+DATE: 2024-04-04T12:22:45-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Forgive me for not having much to update this week. We did have a little fun with April Fool's Day this year and that's good enough for me, but I need to put out a bit of an update to see if I can clear that and I /do/ have a few things to talk about so I figured I'd put out a small news article this week and focus on getting my work and shtuff ready for the next quarter.

* April Fool's Day
Nope we are not a Chimkin store! We wanted to do something to the site to celebrate April Fool's and I came up with the idea of putting up a fake storefront. Sadly, we had a few time constraints and it didn't exactly come out the way I was hoping, but it worked for a first run. I said I would be willing to do it again next year, if we can come up with something that works and/or looks a lot nicer. I don't know if any of you saw it, but, if you did, just look forward to it again next year.

* Break is Over!
Yeah I did get a few things done over break that I wanted to, but not everything. This is really nothing new, as I mentioned, I usually over estimate my feetime on break 😅 Its over now though an I've been hard at work setting things up for next quarter both for work and for school, but mostly for work. I was given some extra tasks to work on this quarter to get ready, but was only given them this week so I had to spend a bit more time working than I usually do. The fortunate thing is that all my tasks are done and I'm ready to get things started next quarter.

I didn't manage to do one thing I wanted to do to get ready for this quarter for school, but I will have some time this weekend and I'm not sure I really need to accomplish it. I keep going back-and-forth trying to decide if it would really be helpful. I /might/ not do it during break and just work on it during my first week of the quarter. I guess we'll see how busy I am with work after the quarter officially starts on Monday.

* RE[BASE]
I did try to go over some of the RE[BASE] episodes over break and try to remind myself where I was, but I had a few busy days because of last minute schedule changes. I know it sounds like an excuse, but it really happened and RE[BASE], sadly, isn't a big priority right now. I sort of wanted it to be something I worked on in my spare time and designed it like that. I do have some general ideas of where the story should go, but if it doesn't quite get there or it changes, that's okay to. I will try to set apart some more time next week to at least finish some artwork for it if not start a new episode. Just don't expect a new episode next week or even the week after. I /will/ try to keep you up-to-date on where I am on it though.

* Guides
I'll update the Persona 3 and Pesona 4 guides next week. I'm getting into some of the good parts in Persona 3 Reload, but am not having quite as much fun playing P3P. I'll have to see if I want to continue working on them side-by-side, but for now I'll keep trying. As for Persona 4, I /might/ be simplifying the Job/Clubs guides as they are linked to S-Links so much of the information would be redundant. Bascially I'll just make a list of them with the skills they help you build, money you make from them (for jobs), and their availability. I'll start putting that together soon before I finish the S-Link guides.
