#+TITLE: RE[BASE] Allana: Spooky Nite!
#+DATE: 2023-10-31T21:31:06-07:00
#+DRAFT: true
#+WEIGHT: 5
#+TYPE: story
#+TAGS[]: allana tabitha momo rebase original adventure
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Allana is missing out on all the Halloween fun! Neither Momo or Tabitha will stand for that! Will Allana really appriciate their efforts though?

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Allana, and not those of the author, Yayoi. Thank you!

* It is Halloween Nite!
It happened suddenly. Artemis was up late. She loved watching the sun rise on occasions just like this one. Event if Tabby or Momoko weren't around, she would sometimes come to Ordin just to see the sight of the first rays of sunlight glistening off the many windows of the city. She looked at the large clock at the center of town. Surely it was about that time, yet there was no hint of sunlight. It was simply not possible that sunrise could be /this/ far off. Was it?

Instead of the first rays of the sun greeting her a loud explosion echoed through the sky followed by another and then more. The sky was set ablaze in various colors. /What is going on?/ Artemis asked herself as a voice chimed in over her hearing stone, which now glowed bright yellow. This meant a general announcement to all adventurers. "/Hello citizens of Gaia/" the voice stated. "/welcome to this year's All Hallow's Eve event. Let the eternal night begin!/"

"What?" Artemis gasped. She tapped her hearing stone until it was green. Hopping she reach someone in her guild, she said. "What do they mean by an eternal night?"

* Should I Change Plans?
I started at the message in guild chat for a few minutes. ~Didn't you check the event logs in the launcher?~ someone had replied. I rarely paid any attention to the launcher unless the big "Enter Gaia" button was grayed out. Seeing as Tabitha and Momo weren't on and I really was just waiting for a sunrise, I deiced to log out and take a look.

"Allana," my sister said, knocking on my door, "you up for breakfast today?"

"Come in here!" I cried. I think I may have sounded a little more desperate than I meant too as Tabitha throw the door open and ran in.

"What's wrong?" she asked.

"Look at this!"

"Oh, its just that. They're starting the Halloween event, huh?"

"Yeah, why didn't I hear about it? I went to Ordin to watch the sunrise and everything."

"I don't know, but I'm sure they announced it. What's the problem with the event? Is it bugged?"

"I don't think so."

"Come on, we'll explore it later, why not have breakfast, it /is/ Halloween after all."

"Don't you still have school?"

"Kind of, the high school is making a hunted school for the elementary school kids. I told them I'd rather stay home with my sister and they said it was okay since we won't have classes today."
