#+TITLE: RE[BASE] Allana: Foreach Friend as Adventurer
#+DATE: 2023-10-01T20:10:53-07:00
#+DRAFT: true
#+DESCRIPTION:
#+WEIGHT: 3
#+TYPE: story
#+TAGS[]: allana tabitha momo rebase original adventure
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Allana convinces Momo to help her and Tabitha with a vital quest in FantasyQuest Online...

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Allana, and not those of the author, Yayoi. Thank you!

* Its Dangerous to go Alone
By now you met Momo and discovered how I, one of the most adorably shy people in the world, managed to fall in love with MMOs, but did you know those two things combined? I didn't think so. I'm getting a bit ahead of myself though. Let me first start with some things that happened more recently.

Just last quarter, I was a normal middle school girl, okay, I was still a very shy middle school girl, but I was attending normal classes, but I passed out during second period. Not long after I was diagnosed with severe anemia. Fearing my safety at school, Tabitha begged for me to be allowed to stay home. She volunteered to help me get assignments and supervise me during the day. My doctor agreed with keeping me at home in bed, but not so much with Tabitha missing her own classes. Instead, I would stay home and Tabitha's only job was to make sure that she collected any homework assignments I had and give them to me at the end of the day. The doctors all thought that, with some medication, and supplements, I would be back in school in a few weeks. It has now been months. My teachers have all about given up on me. Most of them just say I've missed so much class that I would probably have to make up the grade anyway so that stopped sending homework home with my sister.

Now I just lay around in bed most of the day. I play games on a handheld, but, when I feel up to it, I'll get up and log into FantasyQuest Online on my laptop. Oh, yeah! When I started FantasyQuest Online I was playing on my sister's laptop and she would log in downstairs on a family computer, but that quickly changed when she got a part time job and a new laptop. She gave me her old one and we played together with each of us in her room. She would play at her desk, and I would sit on the bed. We still did that sometimes, when she was back from school, even though I had my own desk now.

On this day, I was sitting on the edge of my bed, I just grabbed my laptop (I usually kept it on my nightstand unless it needed to be charged or I was well enough to sit at the desk). I contemplated opening it and logging into FantasyQuest Online. Tabitha would be home soon, but I usually didn't play without her. Only, we were at a particularly difficult part and I wanted to grind a bit so I could get more levels and farm better gear to help out more. I thought it couldn't hurt to log in without her if I was planning on doing something so boring, so I opened the lid of the laptop. That's when Discord went off. I unlocked the screen. There was a message from Momo, "/Hey!/" it started. "/I haven't seen you at school. You okay?/"

"/Been super tired lately/," I answered, "/doctors want me to stay home./"

"/Bummer/," Momo responded, "/I really miss you. School isn't the same without the most adorable girl./"

"/Awww/ 😊" I said, "/Thanks, I miss you too./"

"/What have you been doing?/"

"/Playing FantasyQuest Online and Dragon Ember./"

"/Just playing games? Lucky./"

"/I dunno about lucky,/" I said. "/Actually, do you want to play with me?/"

"/I'm still in class, silly,/" Momo responded.

"/I mean, when you get home,/" I added. "/Tabitha and I can help you start a character if you don't have one already./"

"/Sure./" Momo agreed. "/That'll be helpful./"

"/Okay. I'll talk to you after class?/"

"/Sure./"

With new purpose I logged into FantasyQuest Online and opened the character information window. Since I started this character, she was now level 60 is several jobs and classes. Of course, gunner was her highest class because I worked on it the most, but I wasn't sure how helpful my level 90 gunner would be to a new player. I had a level 60 white mage and a healer might just help Momo's new character a lot more than a damage dealer, but I also had a level 20 priestess, which also had a few healing spells, but also had buffs and a summon, plus the closer a party's levels are to one another the more evenly exp is distributed among the party. You see, when doing quests or killing mobs in FantasyQuest Online, players earn exp, these experience points help level your classes (and jobs, but exp is earned differently for jobs). When a player is in a party, experience from quests and mobs are shared by the party. The player who has the quest earns 50-90% of its experience depending on the level of the other party members, and they gain 5%-95% of exp from mobs. If the other party members are really high they'll gain much more experience than the lower level characters. A lot of player say this is to discourage power leveling, which is when a high level character carries a lower level character. If that is the reason I think it works really well.

"Allana," I heard as I was still debating which class would be most helpful for Momo. "I'm home!" it was Tabitha, "and I'm not alone!"

* Take me!
Standing just over four feet tall with beautiful, majestic, dewy, butterfly-like wings each almost as long as she was tall, the young fairy priestess stood in the middle of a black sand beach surrounded by blue and purple slimes mingling with both large and small crabs. Her robes billowed in the wind. She looked like an angel with long blond hair and a purple eyes. All she was doing was waiting, waiting for the arrival of the one who was prophesied. "Artemis," the priestess heard.

The young fairy turned and brushed her hair aside. The human called Tabby Kat, one of her trusted friends and companions stood less than a meter away. The fairy waved a dainty arm. "Tabby," she called back with a smile.

"She's going to be a little late," the tall figure replied. She had the build of a fighter, but the most gentle green eyes.

"That's perfectly alright," Artemis replied. "I've waited this long, I'm certain a few more minutes won't hurt."

"MAGIC MISSILE!" someone cried. A bolt of energy shot just passed the small fairy, impacting a purple slime behind her.

If the fairy was at all surprised, one wouldn't be able to find it on her face. "She went with a mage, I see," she commented.

"Looks like she did," the human replied.

Just as the slime lost its shape another girl appeared. She had dark purple skin, shoulder length black hair, and two small, red horns. "And a devil at that," Artemis added.

"What!?" the newcomer questioned.

"Nothing," Artemis replied, "I just can't say this was expected."

"Doesn't my character look cool though?"

"She does."

"You're so adorable!" the girl stated, picking up the fairy in her long arms and giving her a bit of a squeeze.

Artemis blushed, "Thanks," she said, "I spent a lot of time getting her just right."

"Hours," Tabby elaborated, Artemis turned a few more shades of red.

"Hey," the newcomer said, "I understand. After all, you're going to look at her a lot, right?"

"So," Artemis said, "what should we call you?"

"Oh, you mean like my character name?" Artemis nodded. "It's Momoko, because I'm very good at naming things." The girl replied with a sarcastic chuckle.

"Momoko works," Artemis replied. "I mean my sister is literally TabbyKat, so..."

"Hey!" Tabby exclaimed.

"You're Artemis though, huh?" Momoko said.

"Its not all that creative either," the fairy admitted. "Artemis is literally a summon from FantasyQuest II. I'm lucky no one else had the name."

"Well we did start during open beta, but yeah, that was some luck," Tabby noticed.

"So, do we just sit here and talk?"

"I mean, Tabby and I do that a lot, kind of like role-playing are specific characters, but that's probably going to be a bit boring for your first run, so what kind of quests do you have?"

"Don't you know already?"

"The first few levels of quests are based off your class and race. I've only played Fairy and Tabby's only been a human so we don't know anything about devils. Tabby tried mage, but you probably won't get those quests for a couple levels."

"Well, I only killed one slime, I need 15 purple and 10 blue." Momoko explained.

"Any greens?" Tabby asked.

"No, I don't think so," Momoko answered.

"Maybe later," Artemis guessed. "Any drop quests?"

"Need some crab meat," Momoko stated.

"Oh good," Artemis said, "I need some crab meat too. Let's start there."

"Okay!"

* Friends who ADVENTURE together stay together
The trio spent the next few minutes gather crab meat and several hours helping Momo with quests and getting used to the game. Momo had brought over her brother's old laptop, but it was in great shape, and she sat on the Allana's bed. Allana, who normally tried to play at her desk these days, sat on the bed with Momo. Tabitha was in her room, but, aside from chatting in-game would occasionally shout things at the group until both Allana and Momo told her to just come over to them. "There's room at my desk," Allana reminded.

With the trio in the room, it was much easier for everyone to coordinate and they started trying a few of the lower level dungeons. Soon it was approaching midnight. Allana yawned. "Tired?" Momo asked.

"I little bit," Allana admitted.

"Her anemia has given her a weird sleep schedule," Tabitha chuckled.

"Yeah," Allana replied, "we'll blame the anemia."

"I mean, its not far from the truth."

"For sure," Allana replied. "Its really because I don't go to school anymore so I just sleep whenever I'm tired. Sometimes I stay up until dawn and then sleep until afternoon, and other times I don't sleep for like a whole day and pass out around eleven or ten."

"Wow, really?" Momo asked.

"Yeah and then there was the day she slept the whole day and didn't wake up until five the next morning," Tabitha added. "That was rough, I wasn't sure she was going to wake up. I kept checking on her to make sure she was still breathing."

"That's sounds rough for you," Momo stated.

Allana blushed. "How has school been?"

"A lot more difficult without you there," Momo answered.

"I'm sorry," Allana said.

"Don't be, you didn't choose to get sick," Momo said. "Besides, I think I'd rather you be here resting then have to deal with all that's happening right now." Allana looked confused, but Tabitha just waved it off. There was definetly something the pair of them were trying to keep from her. She wondered what it could be, but decided not to push it just yet. She yawned. She was far to tired to care right now.

"Want to call it a night?" Tabitha asked.

Allana turned to Momo, "Come and play again?" she asked.

"I don't know how often I'll be able to come over," Momo replied, "but we can always play together, just shoot me a message and I'll be on...as long as I'm not in school that is." Momo winked.

"Okay!" Allana beamed. "I'll keep my priestess at your level so we can level together!"

"Thanks!" Momo responded.

"Alright!" Tabitha interjected, "time for Momo to go home."

"Why don't you just stay over?" Allana asked, "It's already pretty late."

"Sure," Momo said, "a sleepover sounds nice."

Tabitha closed her laptop. "Well," she said, "/I'm/ going to bed. Don't stay up too late, Momo still has school in the morning."

The two did stay up for a bit. The both logged off from the game, but spent several minutes talking. Eventually sleep won though and Allana was taken to dream land.
