#+TITLE: RE[BASE] Allana: Entertainment++
#+DATE: 2023-12-21T10:51:53-08:00
#+DRAFT: true
#+WEIGHT: 6
#+TYPE: story
#+TAGS[]: allana tabitha momo rebase original adventure
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Allana begins to understand how boring and lonely her life is becoming and begins to look for something to fill her time...

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Allana, and not those of the author, Yayoi. Thank you!

* Empty
When I first got the news that I would not be able to go to school, I was excited. I would be able to do what I wanted and no one could tell me to study or pay attention. For a thirteen year old rebel without a cause, this seemed like great news. Here I was though, the house was empty. Tabitha had gone to school. Momo was also at school, even Coco wasn't home. I looked at Discord, everyone was offline or invisible. I tried poking a few of the friends I knew were always online, but no one replied.

I lounged around the living room. I didn't even get dressed, and all I was wearing was an over-sized sweater I had pulled from the hamper after a quick shower. I grabbed my handheld and tried opening a VN, only to find that I had finished the route I was on. In fact, I finihed most of the routes.
