#+TITLE: RE[BASE] Allana: Entertainment++
#+DATE: 2023-12-21T10:51:53-08:00
#+DRAFT: false
#+WEIGHT: 6
#+TYPE: story
#+TAGS[]: allana tabitha momo rebase original adventure
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Allana begins to understand how boring and lonely her life is becoming and begins to look for something to fill her time...

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Allana, and not those of the author, Yayoi. Thank you!

* Empty
When I first got the news that I would not be able to go to school, I was excited. I would be able to do what I wanted and no one could tell me to study or pay attention. For a thirteen year old rebel without a cause, this seemed like great news. Here I was though, the house was empty. Tabitha had gone to school. Momo was also at school, even Coco wasn't home. I looked at Discord, everyone was offline or invisible. I tried poking a few of the friends I knew were always online, but no one replied.

I lounged around the living room. I didn't even get dressed, and all I was wearing was an over-sized sweater I had pulled from the hamper after a quick shower. I grabbed my handheld and tried opening a VN, only to find that I had finished the route I was on. In fact, I finished every route I knew about. I'm sure there were more, but I would have to look them up at this point and my handheld didn't have a browser, so I would have to find my phone or go get my laptop, which I didn't want to do, so I looked for something else to play.

I looked and looked, but everything on that handheld, which wasn't much, was already played. Some I had finished and others I didn't care to finish. I resigned myself to the fact that I would probably have to go to my room either to look for more routes in the VN on my laptop or to look through my cartridges or other consoles for something else to play. Either way, I couldn't just lounge around in the living room any longer.

I won't lie, since I was back in my room I did think about changing, but the sweater was very soft and I was super comfy, so all I really did was throw on a pair of shorts and my fluffiest socks. I set up the laptop on my desk. I was feeling pretty good so I thought maybe I didn't have to lay down today. I opened the lid and sat down. First I just stared for a bit at the icon on my desktop for FantasyQuest Online, but I knew no one would be on today and I really didn't have anything to do solo, so I eventually just opened a web browser.

My intent was to just look up a guide on the VN I playing to see if I missed a route or something, so I had started by typing its title into a search engine along with the word "~guide~". The first few results were kind of broad and mostly just things I already knew, then I saw something about a secret ending. I opened the game on my handheld and looked at my save file. It tracked all the endings, but the total didn't match the one in the description. "There's a secret ending?" I asked.

I clicked the link and it took me to a video on a popular website. There are girl with a cute anime avatar was playing the game and talking about the choices she was making and why she was making them. I watched the whole video and took notes, but something in the back of my mind was nagging at me. "Just what is a Virtual Idol?" I wondered.

* Virtual Idols?
After the video I went back to the search engine and typed "~virtual idol~". I didn't know what to expect, but it wasn't literally hundreds of girls with cute anime avatars playing games, chatting with fans, and singing, yet that is exactly what I got.

"They're all so cute!" I exclaimed to myself.

I completely forgot about the VN I was going to play and the notes I had just taken and spent several hours watching these girls play games or even just chat with people. I wasn't a member and I didn't subscribe to any of them, but I watched and lurked for now. At first there wasn't any one idol that I liked, but I liked the idea of them. They were all really cute, had adorable avatars, and sweet voices. It was so pleasant watching every single one of them, but, as I was scrolling through I noticed a new one was just about to debut. Nanako! Of all the avatars hers had to be the cutest and she looked like she was someone close to my age. I took note of when her debut was and even put it in my calendar. I was lucky, because it was tonight, though I'd probably not be able to have dinner with my sister if I watched her. Maybe Tabitha would be late tonight. I couldn't believe that was something I was wishing for.

The time got closer to when Nanako would be debuting. So far Tabitha was still not home. I knew she helped out with one of her school's clubs, I don't remember which, today, but figured she would probably still be home for dinner, except I was wrong. "/Sorry,/" she said in a text message that I just saw. "/I won't make it home for dinner today. The club's taking everyone out to dinner and they insisted I come because I helped out so much. If you get hungry, I left some extra lunch for you in the fridge./"

Normally I would have been heartbroken from a text like that. Today was an exception though. Now I was still a little disappointed. I had been alone pretty much all day and I wasn't really happy about being alone even longer, but I at least had something to look forward to.

Time passed and I opened my browser again. I was entreated by a very cute transformation sequence and the introduction of a new Virtual Idol named Nanako who sang very beautifully during her debut. She never said her age and I got the feeling she was actually older than I thought especially since she kept mentioning how she is shorter than most her peers, but I didn't care. Nanako was cute and she distracted me from the fact that Tabitha wasn't home. That's all I could ask for.

The debut stream was just over half an hour, but Nanako promised she would be back tomorrow and I added another event in my calendar. After that I went to heat up some left over lunch. I never did change out of that weird, but overly comfy outfit I had put together earlier, so I went and took a bath. I was changing into my pajamas when the door finally opened. I quickly finished and rushed back into the living room.
"Sissy!" I exclaimed as I ran right into her, throwing my arms around her.

She patted me on the head before wrapping her arms around me. "All clean, I see," she said. "Did you eat anything?" I nodded while burying my head in her chest. "Good girl," she patted my head again. "Sorry I'm so late, were you lonely?"

I let go of my sister, took one step back, and triumphantly declared, "I'm fine! I found something new online!"

"A new game?"

"Nope, something even better!" I grabbed her by the arm and escorted her back to my room. By now Nanako's debut VOD would be out, so I watched it one more time, this time with Tabitha.

* I am a Nanako Fangirl!

Nanako's next stream would happen right when Tabitha was supposed to get home from school. She promised to try to get home early so she could make dinner while we both watched it. I warned her that it would probably go for a few hours and she said that it was fine. If she wasn't home on time she would just drop out to cook us dinner and we would watch it together when she was done. That's the plan I went with.

Tabitha did get home a little early. I set up my laptop in the living room with a cable running to the TV. I made sure I could put the stream on the TV with the chat on the laptop screen. This took a bit of work because the site didn't really want to let me do that, but I managed it. Tabitha went to start dinner. Our kitchen was just behind the living room with a breakfast bar, so she could see the TV while she got her ingredients ready. Before she got home I subscribed to Nanako's channel so I could send a chat if I wanted to and we were all set to start.

Nanako started playing a racing game. She said that, for this game, she was just playing against the computer to practice, but she would like to race against her fans soon too. I was excited for that, and so was Tabitha. I don't really play racing games, but Tabitha used to play some pretty old ones when she was small so she was excited to try a more modern one. I was only excited to play with this girl. "Think we'll both get a chance to play next time?" Tabitha asked. We were munching on our dinner.

"I hope so," I said after a bite.

We watched her play. She wasn't really that good, but blamed it on just getting back into the game and saying things like "This is why I need to practice against the computer first." I understood, and it seemed like everyone else was understanding too.

A few hours passed. Dinner was all done, Tabitha had even snuck away and washed the dishes while I kept watching. We even moved on to a few snacks before the game finally came to an end for the day. Nanako began reading some of the chat messages and thanking everyone for watching her stream. This entire time I hadn't said a single thing, despite having already subscribed so I could, but now I felt like I had to. "/Thank you Nanako/," I typed, "/I'm usually alone and it was really fun to watch you play. I hope you play loooots more games and that you keep having fun, because, when you're having fun, I can have fun too!/"

Nanako read my message and paused. I was so touched she actually read it, and Tabitha just kept nudging me saying "Look, she read your message."

"/I'm glad you had fun/," Nanako said.

"Look, she's replying to your message!" My sister interjected.

"/I hope to continue to have fun with all of you too./"

I just sat in silence as Nanako read a few more messages and ended the stream. "That really happened, right?" I asked. My sister nodded. And that is how I became the biggest Nanako fangirl right after her debut!
