#+TITLE: RE[BASE] Allana: Party is Null
#+DATE: 2023-10-22T11:47:55-07:00
#+DRAFT: true
#+DESCRIPTION:
#+WEIGHT: 4
#+TYPE: story
#+TAGS[]: allana tabitha momo rebase original adventure
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Allana convinces Momo to help her and Tabitha with a vital quest in FantasyQuest Online...

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Allana, and not those of the author, Yayoi. Thank you!

* Is Soloing Fun?
I have to say, school may have been very nerve-wracking, but at least I always had a way to pass the time. Whether that meant studying, classes, or homework. Of course, I had less time to play games, but I don't think that was always a bad thing.

On one day in particular, I was lounging around the house by myself. I had gotten out of bed and even managed to get dressed, but I was still not allowed to go to school, so I loaded up a handheld with a new visual novel and just lounged on the couch with it.

I was about two hours into the new story when I sat up and glanced around. I don't know what exactly I was looking for and I don't know exactly what got me to sit up, but I heard myself say, "I'm bored." Of course, I was the only one around to hear it. Maybe the new VN was not as interesting as some of the others I played, or maybe I was just tired of lying there pressing one or two buttons over-and-over again. Either way I saved the game and closed the handheld. I looked over at the clock on the wall above the living room TV. "It's a little too early for lunch," I said. Of course, I hadn't even had breakfast, but I usually didn't these days. I still didn't want to eat too early. "Why did I even bother getting up so early?"

I paced for a bit then went into my room. I sat the handheld down and grabbed my laptop from the drawer in my nightstand. I set it up at my desk and stared at my wallpaper. I don't know what I was thinking. There wasn't much I could do on my laptop except watch videos on a larger screen or play FantasyQuest Online. I mentioned this before, but I usually waited until Tabatha got home before I played FantasyQuest. Of course, because of the time we spent playing with Momo, there were still some grinding that I wanted to do on my main class. I could just do that.

I opened the FantasyQuest Online launcher and just stared at it for a bit again, not sure if this is really what I wanted to do. Without my sister I'd be soloing, and I wasn't sure if that would be all that fun or if someone in our guild would make fun of me for being on so early or try to party me and get me to help them. I didn't mind helping out, when my sister was with me, but I wasn't sure I could handle it on my own.

A notification went off on my desktop as I stared at the launcher window, breaking me from the trance it put me in with a start. "/Hey, what are you doing online? Shouldn't you be in school?/" it was a Discord message from my programmer friend.

"/Shouldn't you be at work XD/" I replied.

"/I am at work XP/"

"/Durn/," I typed. "/Was hoping you could hop one FantasyQuest with me./"

"/Sorry, its crunch day so I really need to focus on my work./"

"/It's okay./" I said. It was impossible for him to tell from just the words typed on the screen, but I was genuinely disappointed. I wanted something to do, but I didn't want to be alone. "/I'll let you get back to work then./"

"/We can play together later,/" the man responded.

"/Have fun at work,/" I wished. I decided to open FantasyQuest Online after all. I was desperate for something to do.

"/Have fun too,/" the man sent. We exchanged a couple more smiley faces as the game loaded and that was the end of that conversation.

* Soloing is not fun!
