#+TITLE: RE[BASE] Allana: Spooky Nite!
#+DATE: 2023-10-31T21:31:06-07:00
#+DRAFT: false
#+WEIGHT: 5
#+TYPE: story
#+TAGS[]: allana tabitha momo rebase original adventure
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Allana is missing out on all the Halloween fun! Neither Momo or Tabitha will stand for that! Will Allana really appriciate their efforts though?

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Allana, and not those of the author, Yayoi. Thank you!

* It is Halloween Nite!
It happened suddenly. Artemis was up late. She loved watching the sun rise on occasions just like this one. Even if Tabby or Momoko weren't around she would sometimes come to Ordin just to see the sight of the first rays of sunlight glistening off the many windows of the city. She looked at the large clock at the center of town. Surely it was about that time, yet there was no hint of sunlight. It was simply not possible that sunrise could be /this/ far off. Was it?

Instead of the first rays of the sun greeting her, a loud explosion echoed through the sky followed by another and then more. The sky was set ablaze in various colors. /What is going on?/ Artemis asked herself as a voice chimed in over her hearing stone, which now glowed bright yellow. This meant a general announcement to all adventurers. "/Hello citizens of Gaia/" the voice stated. "/welcome to this year's All Hallow's Eve event. Let the eternal night begin!/"

"What?" Artemis gasped. She tapped her hearing stone until it was green. Hoping she could reach someone in her guild, she said. "What do they mean by an eternal night?"

* Should I Change Plans?
I stared at the message in guild chat for a few minutes. ~Didn't you check the event logs in the launcher?~ someone had replied. I rarely paid any attention to the launcher unless the big "Enter Gaia" button was grayed out. Seeing as Tabitha and Momo weren't on and I really was just waiting for a sunrise, I decided to log out and take a look.

"Allana," my sister said, knocking on my door, "you up for breakfast today?"

"Come in here!" I cried. I think I may have sounded a little more desperate than I meant too as Tabitha throw the door open and ran in.

"What's wrong?" she asked.

"Look at this!"

"Oh, its just that. They're starting the Halloween event, huh?"

"Yeah, but why didn't I hear about it? I went to Ordin to watch the sunrise and everything."

"I don't know, but I'm sure they announced it. What's the problem with the event? Is it bugged?"

"I don't think so."

"Come on, we'll explore it later, why not have breakfast, it /is/ Halloween after all."

"Don't you still have school?"

"Kind of, the high school is making a hunted school for the elementary school kids. I told them I'd rather stay home with my sister and they said it was okay since we won't have classes today."

"Oh," I replied. I don't think I sounded as enthusiastic as I really was. Though the word may have been kinda of flat and maybe a bit terse, I was actually really happy that my sister would be able to stay with me the whole day. "Hey," I wondered, "do you think Momo has classes?"

"I'm not sure," Allana replied. "I didn't hear what the middle school was doing today. Why not ask her after breakfast?"

"Okay," I said. I changed into a comfortable outfit and headed down to the dining room. Tabitha already had a cozy breakfast of rolled omelets, rice, and natto set out for me. I ate while I sent a text to Momo.

"/Sorry/" she answered. "/School is still going on like normal until last period. Don't think I can sneak away./"

"That's okay," I sent.

"So," Tabitha asked as I finished my breakfast. She was gathering my plates. "What did Momo say?"

"She still has school," this time I'm not sure if the disappointment in my voice was enough.

"Well, that's a bummer," Tabitha said, "but I do have an idea!"

"You do?"

"Yep, how are you feeling today? Energetic?"

"Pretty good actually, why?"

"We're going shopping!"

"Shopping! I don't know!"

"Don't worry, we're not going to buy a lot," Tabitha said. "In and out and you'll really like the result."

"I don't know," I repeated.

"I'll be fun!"

"What about FantasyQuest?"

"We'll have plenty of time to check out the event! Come on!"

* Its a Party!?
I was almost literally dragged out of the house. I was very happy that I had decided to get dressed before breakfast. I'm not sure what I really expected when my sister said we were going shopping either. Maybe I figured we would go get some things for dinner or maybe she wanted to get me a new outfit or something. The second part wasn't too far from reality though. She did have an outfit of sorts in mind.

Once out of the house, she let my arm go and we walked over the mall. I expected, at this time, that we would head over to a department store, maybe a bookstore, but nope, there was a Halloween shop in the mall, and that's where we were heading. "I hope they haven't sold all the good costumes," Tabitha said.

"Costumes?"

"Come on you used to love dressing up on Halloween!"

"I also used to be five! Why do I need a costume!? I don't have anyone to show it off to!"

"That hurt," Tabitha remarked.

"I meant anyone else," I added.

"Well you have Momo, right?"

"Sure, but..." I started. Then something clicked in my head. "What are you planning?"

"You'll see, but you'll need a costume first! What do you want?"

"Fine." I picked something that I wouldn't mind wearing, but also, didn't expect they'd have in my size. "A fairy."

"Oh, like Artemis, that's cute!" Tabitha replied.

Little did I know this shop not only carried fairy costumes in all sizes, and many of the adult one's weren't even overly sexy, but they still had one that was exactly my size. I was doomed. Well, first I was shoved into a changing room. I wouldn't be doomed until after I walked out.

When I did I heard the loudest shriek from my sister I'd ever heard. Her eyes were locked on me. "Cuuuute!!" she exclaimed. I'm sure, if this was an anime or a VN, she would have hearts in her eyes or something. "That's the one!"

"I don't know, it's a little short don't you think?" I was referring to the skirt. I mean I knew most fairies in movies and anime had short skirts, but I've never been forced to wear one myself.

"Don't worry, sis," Tabitha said with a wink, "you have nice legs and I'm not planning on inviting boys." So she was planning on inviting others. Just what was happening?

I quickly changed back into the outfit I came in before she could tell me to wear the costume out of the store. The costume was begged back up, but Tabitha snatched it from my hands before I could even think of putting it back and took it to the counter.

I don't know if she was trying to placate me, but, after returning home with her catch, Tabitha sent me to my room and instructed me to get on FantasyQuest. I wasn't going to say no.

Before long she was there too. We looked around the various maps and did a few fun event-themed quests and dungeons. After our third dungeon, Tabitha slipped the costume into my room. She instructed me to change because, "it would be starting soon." I still had no idea what she was talking about, but, for some unfathomable reason, I did what I was told. I left the wings off while we worked on a few more quests. Oh, and I added a pair of white tights to the costume, because the skirt really was short.

We were working through a special event dungeon when I heard the door bell ring. "/Bad timing/," Tabitha sent in party chat. We got to a quiet part of the dungeon and Tabitha asked me to hold the fort for a bit while she answered the door. There wasn't much for me to worry about.

I heard more than one new set of footsteps, but they didn't come up the stairs. "We'll get started in a minute," I heard my sister say. "Just let us finish something I promised my sister."

"No problem," I heard Momo reply.

We finished the dungeon and my sister, dressed in an old black cat costume from two years ago that still managed to fit her, came and fetched me. "You ready?" she asked. "Where are your wings!?" I pointed to the pair of fairy wings on my bed. "Put them on, we have guests!"

I was both embarrassed and nervous as I slipped the wings on and followed Tabitha down the stairs.

"Happy Halloween!" I heard. Momo was dressed as a warewolf and there were a couple of other girls, which I'm guessing were friends of my sister. One of them was dressed as one of my favorite magical girls. She spoke next "We heard you had to spend Halloween alone, and we couldn't have that, so we're having a party!"

"Don't be shy," Tabitha said. "They are all friends."

"Yeah," Momo added.

It took me a few minutes to get comfortable with everyone, but they brought me candy and snacks so they couldn't be bad, right? We enjoyed watching movies together and hanging out. In the end I think I may have made a few new friends. The girl who was dressed up as a magical girl was named Carol, but my sister just called her Coco, for some reason. She also played FantasyQuest Online and promised to add me as a friend when she got home.

All in all, thought I didn't play all the event content today, I really enjoyed spending time with everyone. I was happy to have new friends and everyone was super nice and didn't mind that I struggled to talk sometimes. Coco, like Momo, thought it was cute actually. Quoting a character from a VN I played, she even said. "I want to take you home!"

"Over my dead body," Tabitha joked. "She's /my/ sister!" With that she squeezed me tightly and I just beamed in her arms. Don't think I would have minded if Coco took me home though. She liked a lot of the same anime, VN, and other games that I liked. I kind of wonder if she had any magical girl figurines or plushies. I wouldn't be finding that out right away though.

The evening ended with me heading to bed and everyone else saying goodbye before remarking that it was a school night still and they should go home and get some sleep. We all said good bye and I had great dreams that night.
