#+TITLE: RE[BASE] Nagisa: More Than a Voice
#+DATE: 2023-11-30T12:50:00-08:00
#+DRAFT: true
#+WEIGHT: 2
#+TYPE: story
#+DESCRIPTION:
#+TAGS[]: nagisa original adventures rebase
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Nagisa is a little nervous about her online debut. Hopefully everything goes well.

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Nagisa, and not those of the author, Yayoi. Thank you!

* But I'm Not a Gamer
When I interviewed for this company as a virtual idol I thought it meant that I would just be singing with the added bonus that no one would see who I was. After the interview I got a bit of a bigger picture. Idols did more than sing!

It was about an hour before my next scheduled live stream. I sat in front of the computer. The new desk chair the company had sent over made me feel like a little kid who still had to sit in daddy's lap just to see the monitor. I tried to adjust it so it would sit just a bit higher, but, seeing as I was just four feet ten inches tall, this would almost leave my feet dangling. /If only they sent a shorter desk too,/ I remember thinking to myself.

I managed to get the chair adjusted to where I could see the screen and decided to try and tuck my legs up on the cushion. I would be setting up to play a racing game and I knew that I could play it with a controller, so reaching the keyboard or the mouse wasn't a high priority right now. Still, I wasn't really able to find a comfortable position. I thought about just getting my old chair, the one I during debut, but that was just a folding metal chair with almost no padding and management was expecting me to stream for at least a few hours.

"/Any chance of getting a shorter desk?/" I joked in a message to my manager.

"/I could look into it/," she replied.

"/I'll manage,/" I sent back.

"/If you're uncomfortable, it won't be good for you or your audience./"

"/Okay, look into it please. No rush though, I'll manage for today 😉/"

"/Okay, just remember, we discussed going for at least three hours today,/" the manager said.

"/I know./"

"/But its about you so make sure to pace yourself and don't go too long. If you have to end stream a bit early then do so./"

"/Thank you 😄/" I sent.

After trying again to find a comfortable position, I decided it wouldn't hurt for my feet to dangle for a little bit, at least while I got the game up and the streaming software started. I set up my scene, launched the game, resized the window to fit in the little frame the company had sent over for me to use for playing games and got the controller ready.

Today wouldn't just be my first time playing games on a live stream, but it was also the debut of a little version of my model that held a little light blue controller. The controller was just a generic looking one. Due to the angle the viewer wouldn't see the main face buttons, just the sticks and the triggers, so it could almost be any controller.

The little frame was also a first. It was cute with stars and a baby blue and white color scheme. The frame around the window looked a little like a TV and was a darker blue. I like this frame and approved it right away. Management wanted a few tweaks, like adding a spot for the title of the game I was playing and place to put chat on screen.

"Oh!" I gasped to the empty room as I waited. I forgot to type what I was playing. I put the game title in the box then continued to look at the clock before pressing the "start stream" button.

* I am Your Gaming Idol!
"Hello everyone!" Nanako appeared front and center on the screen. White stars sparkling on a light blue background behind her. "I hope you all are doing well."

Messages from fans zipped passed next to her. "Zemi2341! Hello, 'are you going to sing again?' Nope, not today. I'm going to play a game for you all! Its a racing game and I hope we can all play together someday! Right now I'm going to be practicing against the computer though because I haven't played a racing game in ages!"

Nanako read a few more of the chat messages and asked her fans if they remember what she likes to play. She briefly mentioned a few things during debut, but no one seemed to guess any of them. "Definitely not horror!" Nanako cried. "I like visual novels and RPGs mostly," she reminded, "but I'll play almost anything...except horror!" she added.

Nanako excitedly went over her schedule again and reminded her fans she'll go over it once more at the end of stream before she switched scenes. She moved over to the side of the screen and a large TV screen appeared next to her. It showed the title screen of the game she was playing. "Who's ready for me to start?" she asked. There was a flood of excited messages saying they were ready and even a few begging her to just start. "Let me get my controller," Nanako said. With that, the petite girl's once empty hands suddenly held a controller that was just a few shades darker than the background she stood in front of and she winked. "Let's start!" she said before pressing a button on the controller. The title screen suddenly displayed a menu.

* Its About More Than Having Fun
Nagisa put down the controller, turned off the controller on her model and declared the end of the gaming session. Even though she did end up tucking her legs up on her chair as she played, it was still not the most comfortable position so she dropped them several times. This had led to a few bad mistakes. On the advice of her manager, she just laughed each one off and said that she was out of practice. It seemed as though everyone just believed her.

The reality of the matter was, Nagisa had never played this game, in face, though she had told everyone in her debut that she like RPGs and would play just about any game, the truth was she only really played visual novels before.

Nagisa read through some chats and replied then something unexpected happened. "/Thank you Nanako/," one of the chats read, "/I'm usually alone and it was really fun to watch you play. I hope you play loooots more games and that you keep having fun, because, when you're having fun, I can have fun too!/" Nagisa had a hard time getting the last few words out as she read the message into the microphone. She hoped her voice was less shaky on the other end then it sounded to her in the room.

"I'm glad you had fun," Nagisa said. She watched her avatar's mouth move and made sure Nanako still looked just as happy and excited as she had been this entire almost three hour stream. She paused for a moment. "I hope to continue to have fun with all of you too." She wanted to direct the words specifically to the fan who wrote that message, but she was warned about singling anyone out. If the fan was not happy, they didn't let her know yet and she took that as a good sign that they understood the type of person Nanako had to be. Nagisa, on the other hand wished she could reach through the screen and give that fan a hug.

After a few more chats, Nagisa reminded her fans of her schedule again and signed off. Almost immediately after ending the stream, she got a message. "/Great job!/" it said, "/You handled that well./"

"/Thank you,/" Nagisa replied. "/Anyway we can send something to that fan?/"

"/Right now, I'm afraid not,/" the manager replied.

"/Why not!?/" Nagisa said.

"/We don't have any of their information./"

"/Oh, I see./"

"/We have their user name, if they become a member we might get more, just keep an eye out for them, but don't draw too much attention, okay?/ It's fine to have your favorites or to want to help your fans, but, as an idol, you can show your preferences, okay?/"

"/I got it, thanks./" I typed. It was late, so I signed off of work and the company's messenger app. I had classes tomorrow, so I changed and went straight to bed.
