#+TITLE: RE[BASE] Nagisa: Debut!
#+DATE: 2023-11-30T12:50:00-08:00
#+DRAFT: true
#+WEIGHT: 1
#+TYPE: story
#+DESCRIPTION:
#+TAGS[]: nagisa original adventures rebase
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Nagisa is a little nervous about her online debut. Hopefully everything goes well.

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Nagisa, and not those of the author, Yayoi. Thank you!

* Just Press "Go Live!"
I stared at my screen. My heart was racing. Management had given me a checklist of things I needed to do before now and they sent over all the files and assets I needed. Yesterday I had updated my streaming software and linked it to my online account. I put together a little script of what I would do and say about myself, or rather, little Nanako (the character the agency had assigned me), and submitted it to my manager. She approved everything this morning and said all I had to do was get everything set up and press "Go Live". Yeah that was easier said then done. First of all the software didn't have a "Go Live" button, it said "Start Streaming". I knew that already though, but that wasn't the problem.

I know just enough about computers to get by, but setting up the scenes and everything was a bit more difficult. You see Nanako, my little live avatar, was supposed to animate based on my head movements and my lip movements, but that wasn't working at first. The sent me over a few streaming backgrounds and frames I could use, but the software wasn't displaying those right and I had to do an update before it would work. I'm also not sure how to show my screen. That last part isn't important right now. I won't need to do that for debut, but the contract says, under the heading "engagement" that I was supposed to play games on stream for my fans, which I was not sure how to do. I even had my first one already scheduled. I took a breath. I already e-mailed my manager about that and she's looking into it. Right now, I just need to focus on debuting Nanako.

The background was set up now. Nanako moved when she was supposed, she even blinked with me now. I took a deep breath and watched the clock. "Three minutes to debut!" I told myself. I quickly sent a text out to my parents and brother reminding them that I had work and not to bother me. I checked the pickups and gates on the microphone to make sure that only my adorable voice would be heard and checked off the second to last item on the checklist. "Two minutes" I updated.

I took one deep breath than began tracing my figures. I breathed in as I went up one side, breathed out as I went down the other and repeated it for all five figures. "Everyone is nervous when they start," my manager had told me in my last virtual meeting. She told me about the technique just after that. "They're here to meet Nanako," I reminded myself. That's right, no one cared about Nagisa, they wanted Nanako, and Nanako had no background or baggage beyond the brief blurb some agency writer just put together for me to read during the debut. Those on the other end of the screen, they had no expectations for me. "Just have fun," my manager had added before logging off of that meeting.
"Just have fun," I repeated now.

A message popped up. It was from my manager. "Good luck!" she said. "You got this!"

"Its time!" I said. I pressed "Start Stream". After a little wait connecting I played the first asset my manager sent over, and opening animation.

* Hello Nanako!
A young girl smiles back at the audience. She stood, just under five feet tall, on the center of the stage, a starry background behind her. She closed one eye and tilted her head. Anyone who say the petite frame on stage and paired it with that wink would probably think what stood before them was a child. That didn't matter. What happened next would have surprised anyone.

The stars suddenly dissappeared and all light left the room. The audience, in a mixture of surprise, excitement, and fear, cried out. "Nanako!" they said "Nanoko!"

"Smile!" the girl said. The room was soon filled with a bright light in a flury of fluid motions the girl in front of them transformed into what could only be described as a magical girl, complete with a cute outfit and a little wand.

The background of stars returned and the girl smiled at the audience once more. "I am you new idol, Nanoko!" she said. "I hope we all have a lot of fun together. I like singing, of course, and a love making new friends, so I hope we can all get a long!" the crowed cheered loudly. "Now many idols would use their time to talk about themselves, but don't you all find that just a little boring?"

"No," said one fan.

"Yeah!" said another.

"Let's do something new!" said a third.

"Well I could tell you my age and where I'm from and all that stuff, my three sizes are secret though," Nanoko gave her fans a wink, "but, why don't we start with a song? I mean, idols sing right? So I should just sing for you, right, right?" The crowd cheered and the girl took a deep breath, the stage lights dimmed leaving only her in the spot light with a standing microphone. The girl opened her mouth and began to sing.

* You'll do Alright!
In the end I never revealed the age of my character. The designer had stated that, like me, Nanoko was 19, but my manager felt that she might appeal to a wider audience if a certain set of them were completely unaware of her age. I brought up some of the other details my character's designer had written up, but I did this between sets. I had gone over this with my manager. I told her I wanted to sing, and, though I did like the magical girl theme they came up with for Nanako, I wanted to be known more as an idol. After hearing me sing, my manager agreed that, the faster we planted that image in the heads of the fans the less jarring it would be when Nanoko did more singing later. So we had both come up with the idea of making her debut more of a Karoke stream.

"/Great job!/" my manager messaged just as I ended the short, 35 minute stream. "/I think they really enjoyed your singing, I know I did./" she added.

I teased my schedule, including my next stream, which was going to be out Sunday. It was going to be a gaming stream. I wasn't a fan of this part, but my manager said it was important as it was one of the easiest way for a young virtual idol to engage with fans. Now, I don't mind playing games. It wasn't the first thing that came to mind when I had free time, but I found some of them fun, especially visual novels, but I was going to have to play variety of games and I wasn't sure I'd be good at any of them. "/I'm really worried about Sunday's stream/," I messaged back to my manager.

"/You're playing a casual racing game/," she messaged back. "/Don't worry about your driving, just have fun. If you don't seem very good, just laugh it off, and say you haven't played in awhile. The important thing is just to have fun./"

"/I'll try,/" I typed.

"/You will! Don't worry./"

"Nagisa," my brother called, "aren't you done with your stream?"

"I'm talking with my manager," I replied.

"Well, the bath is ready."

"Okay." I just sent my manager a smile (🙂) emoji and told her I'm signing off for the night. She sent a thumbs up (👍🏻) and I headed off to the bath.
