#+TITLE: RE[BASE] Nagisa: More Than a Voice
#+DATE: 2023-11-30T12:50:00-08:00
#+DRAFT: true
#+WEIGHT: 2
#+TYPE: story
#+DESCRIPTION:
#+TAGS[]: nagisa original adventures rebase
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: Nagisa is a little nervous about her online debut. Hopefully everything goes well.

#+attr_html: :style font-family: monospace; font-size: 0.9em
This is an original story. The story is written in first person, please note that the thoughts and feelings expressed in this story are those of the character, Nagisa, and not those of the author, Yayoi. Thank you!

* But I'm Not a Gamer
When I interviewed for this company as a virtual idol I thought it meant that I would just be singing with the added bonus that no one would see who I was. After the interview I got a bit of a bigger picture. Idols did more than sing!

It was about an hour before my next scheduled live stream. I sat in front of the computer. The new desk chair the company had sent over made me feel like a little kid who still had to sit in daddy's lap just to see the monitor. I tried to adjust it so it would sit just a bit higher, but, seeing as I was just four feet ten inches tall, this would almost leave my feet dangling. /If only they sent a shorter desk too,/ I remember thinking to myself.

I managed to get the chair adjusted to where I could see the screen and decided to try and tuck my legs up on the cushion. I would be setting up to play a racing game and I knew that I could play it with a controller, so reaching the keyboard or the mouse wasn't a high priority right now. Still, I wasn't really able to find a comfortable position. I thought about just getting my old chair, the one I during debut, but that was just a folding metal chair with almost no padding and management was expecting me to stream for at least a few hours.

"/Any chance of getting a shorter desk?/" I joked in a message to my manager.

"/I could look into it/," she replied.

"/I'll manage,/" I sent back.

"/If you're uncomfortable, it won't be good for you or your audience./"

"/Okay, look into it please. No rush though, I'll manage for today 😉/"

"/Okay, just remember, we discussed going for at least three hours today,/" the manager said.

"/I know./"

"/But its about you so make sure to pace yourself and don't go too long. If you have to end stream a bit early then do so./"

"/Thank you 😄/" I sent.
