#+TITLE: Fledgling Adventurers
#+DATE: 2022-10-09T20:59:51-07:00
#+DRAFT: false
#+DESCRIPTION: Fledging Adventurers are characters from level 81-120, not their yet, but almost.
#+TAGS[]: guide leveling quests
#+TYPE: guide
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

If you have followed my [[{{% ref guides %}}][guides]] so
far then you'll be level 81 in no time, especially if you were power
leveled. Things will start to go really fast or depressingly slow
depending on the guild you are in, the money you have amassed, or the
friends you have. This is kinda just how it is in Fiesta, unfortunately.

** How best to exploit repeatable from level 81-120, according to Yayoi
   :PROPERTIES:
   :CUSTOM_ID: how-best-to-exploit-repeatable-from-level-81-120-according-to-yayoi
   :END:
Again, there are many leveling guides available, and a lot of opinions
on how things can be done at this stage too. For this stage I'm going to
give you a few options for some of the levels. If you have the friends
and money they'll help you level really quickly, if you don't than you
can still solo, or work with a group of close friends your level, and
still level, but it'll be slower.

*** Level 80-90
    :PROPERTIES:
    :CUSTOM_ID: level-80-90
    :END:

1. There is a repeatable for gathering armor pieces in DT. You can have
   a higher level friend or a DT runner and a few droppers run through
   DT with you. Make sure you inventory is nearly empty and just fill it
   with these armor pieces. Once full, leave the dungeon and spam turn
   ins. Rinse and repeat until your level 90. Don't forget to get the DT
   Key and quests.
2. Alternatively, you can just do all the level 7x quests. There are a
   few somewhat boring reps mixed in there to help you get to 90.

**** The slow way
     :PROPERTIES:
     :CUSTOM_ID: the-slow-way
     :END:
Here are the reps you can do to help you get to 90 if you can't do DT
for some reason:

1. Level 81-86 - Miner Mole Rep - "I Despise Moles"
2. Level 82-87 - Another Mole Rep - "It's Them Again (Repeatable Quest)"
3. Level 84-88 - Kidmon Rep - "Hans in Love"
4. Level 85-88 - Toy Spade Rep - "Kidmon The Menance"
5. Level 86-89 - Jewel Tree Rep - "Tree of Jewels"
6. Level 89-90 - Lava Gargoyle Rep - "Attack of the Lava Gargoyles"

*** Level 90-101
    :PROPERTIES:
    :CUSTOM_ID: level-90-105
    :END:

1. You can now enter Leviathan Nest. You need to complete the quest
   "Lost Key to the Lighthouse" to get the key. This requires you to
   slay Nest Slime, which is kinda strong for its level, best to have a
   friend help. Once here you have the key, you can find a guildie,
   friend, or other LN runner and just stand around and gather exp. This
   is nice because you can level while you AFK like in FM, but it can be
   expansive because runners don't run it for free, usually.
2. Alternatively, there is a non-LN strategy that is not as easy and is
   a bit slower, but more than doable.
3. Also, at this point you may begin to do [[{{% ref dailies.org %}}][daily quests]] from the Hunter's Union. These will allow you to earn tokens to exchange for items /and/ give you a bit of exp every day!

**** The slow way
     :PROPERTIES:
     :CUSTOM_ID: the-slow-way-1
     :END:

1. Level 90-94 - RS Rep - Complete the following: "Burning
   Cave">"Burning Cave 2" to unlock "My hunches never proves wrong" -
   Rock Stone is also hard to kill for someone at this level, but I love
   killing RS so just get [[https://forums.onigirionegai.info/viewforum.php?f=3][in-touch with me]], or you can have another high
   level guildie or friend kill it for you while you turn in the rep.
2. Level 94-95 - Mandrake Rep - "Outlaw of the Swamp (Repeatable)" - 15 Kill per turn in now! Much better than doing all the other quests, but you /could/ still do those if you want.
3. Level 96-97 - King Rhino Rep - "The Threats of King Rhinoce" - Pretty
   easy mini-boss, may even be able to solo him, but a higher level
   killer is faster.
4. Level 98 - do all the 9x quests to get you to 99, if you're having difficulty reaching 99 even with [[{{% ref dailies.org %}}][daily quest]] and these normal quests, there is also the Ping Pig Horn rep - "Food Thief", but this is a drop quest and can be difficult to in a party, so it is /not/ recommended.
*** Level 99-101
Whether you did or LN or not the next quest is "Personal Revenge", which is known as the "Slugs Rep" and should /not/ be confused with the "Mad slugs rep"!
*** Level 101
The "Mad Slugs Rep" mentioned above is a good way to pass level 101, it isn't very good after that level, but it does remain available. You will have to unlock it though by completing a chain of quests starting with "Suspicious Big Mudmen". This will unlock "Fire on Hands and Feet" which will finally unlock "Unextinguishable Fire", which is this rep.
*** Level 102-106
Next repeatable quest is "Black Bear Beatdown" or just BBs. It has been determined that this is now faster than Mad Slugs, though that is still available for you.

*** Level 105
    :PROPERTIES:
    :CUSTOM_ID: level-105
    :END:
If you did LN above, then just do the BB rep mentioned in the slow way
to get you to 106.

*** Level 106-108
    :PROPERTIES:
    :CUSTOM_ID: level-106-108
    :END:
Okie, most of the shortcuts are done now so, no matter what, you're
going to have to grind a bit. Fortunately it isn't really hard. Just
remember that a lot of people are going to be doing these quests, see if
you can join a party with a dedicated killer and this will go much
faster. For these levels, you have the Fire Shellas rep ("Playing with
Fire").

*** Level 109
    :PROPERTIES:
    :CUSTOM_ID: level-109
    :END:
Complete all quests you've saved until this point. If you haven't had to
do the 9x quests than this will be very quick. Otherwise, the quests in
OLT are here and they are also fairly quick with any other quests you
saved up. OLT is best tackled with a party though.

*** Level 110-116
    :PROPERTIES:
    :CUSTOM_ID: level-110-111
    :END:
Nepu Nepu Neeeeep! Its time for the Nep rep. Complete "Collecting
Twister Crystals" before getting the repeatable version. Believe it or
not, there is nothing to collect for this rep, just killing.

*** Level 112-116
    :PROPERTIES:
    :CUSTOM_ID: level-112-116
    :END:
If you can, stay on Neps! There are two additional repeatables avaialble though. Either Mean Leipoons ("Threats for Temporary Settlement 1") or Shellas
rep ("Threats for Temporary Settlement 2"). It is important to note that
you will have to completely The Mean Leipoons rep a twice times before the
Shellas rep shows up. Its weird, but true.

*** Level 116-118
    :PROPERTIES:
    :CUSTOM_ID: level-116-118
    :END:
Wrenches rep. Unfortunately, this quest is buried under a loooong list
of prequests, but here they are: "Milly's Healthy Wonder Medicine
2">"Unknown Causes.. However">"Noisy Animals 1">"Noisy Animals
2">"Special Wrenches". Once these are complete you'll get the repeatable
version of "Special Wrenches". It should also be noted that you can make
a ton of money by doing "The Workshop Master is making a weapon"
(available at 117) while you are doing the wrenches rep, not to mention
this boosts your exp too. It should be mentioned that "Noisy Animals 2" is also a repeatable quest and can be done the same time as wrenches.

*** Level 118-121
    :PROPERTIES:
    :CUSTOM_ID: level-118-121
    :END:
Junks rep. This is also buried under a loooong list of prequests (but it is worth it! these quests will give you a lot of exp and the rep gives 2-3% per turn it 😲), so
I'll give you those too. "Smart Yeti is preparing for an
Exam">"Something urgent came up to Hilda">"Sick Akisha">"North Witch's
dark power">"Pagel's voice 1">"Pagel's voice 2">"Someone can help us..
Right?">"Yeti invading Arkroute">"A strong Alliance">"To prosper Bera
Village">"The Adventurers are not arriving">"The scariest monster">"A
story of Valiere and Hilda 1">"A story of Vailere and Hilda 2">"A story
of Valiere and Hilda 3". After /aaall/ these quests, you'll finally get
/"Selling Junks"/

I've learned something just recently. There are a quite a few quests that you can do during this level, including a ton of repeatables. Junks is, by far, the fastest way, but it can be dangerous because of all the Astan's nearby. For this reason I recommend having a good party with someone tanky to pull and a good killer that could, if needed, one-shot the Astans if they get close. Bonus, a party should be able to tell you exactly where to stand, sit on your mount, or rest during the rep to minimize your likelihood of dying, however, if you don't have a lot of friends, there are easier, but slower reps. As I mentioned, a *TON* of them. Just don't get discouraged by how slow you gain exp. Also, if your in a guild that likes to do Siren's Castle raids and has a few good runners, ask if you can tag along for quests. This will be a good way to gain looots of exp at once, but be sure they are okay with you joining and it would probably good to spend some money on scrolls, tevas and charms, don't forget to grab all the dungeon quests, they should have a sword icon!

** Congrats
   :PROPERTIES:
   :CUSTOM_ID: congrats
   :END:
You are now a bone-fide adventurer. You are still 20 levels away from
cap, but keep it up! As always, you can visit the
[[http://fiesta-wiki.com/][Fiesta Wiki]] for more information on
any of the quests above.
