#+TITLE: God-like Adventurers
#+DATE: 2022-10-09T20:59:14-07:00
#+DRAFT: false
#+DESCRIPTION: The current cap is 140, these are adventurers that are a stone's throw from that (135-140) so yeah, pretty god-like!
#+TAGS[]: guide leveling quests
#+TYPE: guide
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

When I first wrote my last [[{{% ref guides %}}][guide]] the level cap was actually 135 so I said congratulations now figure out what to do next. Well cap is 140 now so I guess it's time for an update to the guide 😉. So, here's some ideas of what you can do. The same caveat exists with this guide as with the last one. My current highest level character is 140, but she is a cleric, so I have /not/ tried some of these suggestions alone. If you have better suggestions, though, let me know, you can comment on this page with a GitHub account, or send me an e-mail!
** Dailies, Dailies, Dailies, and more Dailies
:PROPERTIES:
:CUSTOM_ID: dailies-dailies-dailies-and-more-dailies
:END:
Your best bet for a while at least is to continue to do the [[{{% ref dailies.org %}}][dailies]] you've been doing up until this point. As I said above, there are no KQs for passed 135 that offer any significant amount of exp, however, many of the hidden dailies and other daily quests you got when you got to 132 are still viable passed 135 and offer some exp. A member of one a guild I am in has broken down the amount of exp, in percentage, that you receive for various levels passed 135. Please note: this is the percentage if you complete all available dailies quests, not the percentage per quest!
+ 135 - 16.70%
+ 136 - 13.22%
+ 137 - 11.02%
+ 138 - 9.07%
+ 139 - 4.60%
** New Reps!
:PROPERTIES:
:CUSTOM_ID: new-reps
:END:
There are new reps for you to complete as well. Well a couple anyway.
+ Yuna 3 (135-136)
+ Soul Rep (136-138)
+ Bug Rep (138-139)
** Questing
The [[http://fiesta-wiki.com/quests/13][fiesta wiki]] offers a few options for quests for this level range. It has been recommended to relay on dailies and reps until at least 139. This will allow you to save your quests for when normal quests are suuuper in-effective, and hopefully make that last level just a little faster.
