#+TITLE: 1. Meeting at Yawning Portal
#+DATE: 2024-01-14T17:52:51-08:00
#+DRAFT: true
#+DESCRIPTION: Keyrie, meets an interesting moon elf and a rather large barbaric woman.
#+TYPE: story
#+TAGS[]: stories adventures D&D Keyrie
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

All of my servants told me the Yawning Portal would be the best place to seek adventure. While I was not entirely sheltered by my parents, being my father's youngest daughter, ensured that I was not treated with the same freedom or independence as my eldest sister or my older brothers, but living under the shadow of my father's station, was cold and lonesome and I desired to see more of the world than our small keep. So I set out to the Yawning Portal in search of adventure, for only by setting out on my own would I be able to prove myself and earn respect and independence.

When I set out that morning, I wasn't expecting the cold, let alone the snow that began to fall as a neared Waterdeep, nor for it to accumulate nearly up to the shins of my boots as I drew nearer to the Yawning Portal. To keep my feet dry, I looked for a road often traveled by wagons. I planned on trudging through the ruts of the wagons, however, a horn of sorts would soon signal that the was less than my best idea. "Out of the way," I heard, "Tracie has places to be."

I could not see the source of the voice, but I did notice a rather ornate looking wagon, with stars painted on it, barreling my way. I decided I should adept to hold my ground, but neither the horn nor the wagon gave any indication of stopping. "I will not move for just anyone," I called, but there was no response. Reluctantly, and out of fear of my own life, I stepped aside and allowed the wagon passage, but this was not something I would forget. I would know who the owner of the wagon was, for I had some very choice words about station and respect for them.

* A Performance to be Forgotten
Upon my arrival at the large, multi-leveled tavern, I first noticed the pit at the very center. Every level opened up and looked down toward this pit. Apparently it was the entrance to a large ruined castle and was what attracted so many adventurers. There was a large robe and pulley attached to a chair used to lower adventures down into the pit.

Rather than exploring the tavern proper, however, I decided to pull up a chair by the bar. "Is there any good wine here?" I asked to no one in particular. "Of course," said a bar man. I order the finest wine. No sooner had a received my first glass than a commotion rose up between a large woman, standing nearly a head taller than me and a woman half a head shorter. I could not tell what was being said, exactly, though both seemed to be speaking in common tongue. I could make out something about a performance, then, as the two grew nearer to me, something about wine and cheese. /Brie/ I thought, that would be perfect with this wine. I decided to be generous, as the others ladies were bantering about the cheese and wine, and offered each a piece of brie. The shorter of the pair, a moon elf, with gorgeous blueish skin and light hair, took the brie and ate before heading toward the stage. Perhaps it was her that was performing.

With magic, the moon elf cleaned the stage and caused her raiment to sparkle. "The Great and Powerful Tracie will shock and amaze you all!" the woman began. Genuinely intrigued I watched as the sorceress, for that is how she referred to herself, pulled various objects out of a large wizard's hat. Mere parlor tricks, nothing of note. I was not the only one who was less than impressed with this performance as the crowd gathered in the tavern yelled and booed. "Get off the stage," I heard one say.

"Well, I never," Tracie muttered. "For my next trick, I need a volunteer."

As no one felt compelled to answer her call, and as I had a burning desire to end this ridiculous excuse for a performance, I rose up. "I'll volunteer," I cried. As there were no other volunteers, I was instructed to take a sit in a chair on the stage. Naturally, I thought of abandoning this whole performance, but, I had volunteered of my own will and I would not leave. "What is your favorite pie?" Tracie asked before listing off several different kinds, among which was banana cream.

"Banana Cream!" I responded. The sorceress, for that is how she called herself, pulled a banana cream pie from the depth of her hat. "I will now cause the pie to disappear!"

Hoping to garner at least a little praise from the crowd, or a laugh, I buried my face in the pie. Normally this was not something I would have even considered, however, if one would question it, I would simply say the woman charmed me. Surely that would also garner her some favor. I devoured the pie. Yet there was not a single chuckle or applause. Instead we were both being shooed off the stage. I was only too happy to oblige, and, was shocked when Tracie did the same. "I don't suppose you could clean the pie off my face?" I asked as I returned to my seat and my wine. "Be clean," the elf said. The cream was removed and my face was beautiful and unspotted once again, aside from the faint and small group of freckles which dotted the top of my cheeks I'm sure.

* So, You Wanted Adventure?
No sooner had the performance ended the a call rang out from the bar. "Troll!" I looked around, and spotted the offending object surrounded by three bat-like creatures. I wanted nothing to do with this, and began looking for an escape. Finding none, however, I decided to simply watch. Perhaps I would not need to draw my bow or my swords. The barkeep leapt from his bar, pulling out a large greatsword. He turned toward the woman with fiery red hair, who bantered with Tracie, I woman by the name of Ember, and said. "I'll take care of the troll, you and yours take care of the Sterges."

/What did he mean by her and hers?/ I wondered to myself. It soon became apparent, however, that I and Tracie and somehow been lumped in with this Ember woman. I fired and arrow and hit one of the bat-like creatures. I hurt it, but it remained alive. Meanwhile Ember cleaved one of them entwine while Tracie stood and watched. I fired another arrow, but, much to my embarrassment, it spectacularly missed its mark, embedding itself, instead, into a banister in the second level.

Soon, however, the creatures were slain, mostly with the help of Tracie and Ember. The barkeep, and man by the name of Durnan, slew the troll and all was well. Only we heard a call from somewhere in the crowd. "You look like adventures in need of an adventure." I, however, had a sudden yearning to return to the home of my father and forget this whole mess of a day. "I have gold," the man said. My ears perked and a turned, I was not an unwealthy woman, but I did have a strong need to earn my own way, and this would be a means to that end. "I suppose I could be persuaded," I said.

"I need to you look for someone for me," he explained. "A friend, we were out drinking and I'm afraid we parted ways, and I have not seen him since."

"Surely there is more to the story," Tracie responded.

A bit discomfort flashed on the man's face. "Aye, for you see this may have been my fault." I, however, had enough information. We were supposed to look for a princely-looking man with striking red hair. We were to be paid ten gold and than ten times that when we return with the man. What else did I need to know? Deciding we might as well work together on this as Tracie, Ember, and I were called together already, we were each given our ten gold pieces and headed out toward the last known location of the man we were tasked to find, the Skeward Dragon

* The Skeward Dragon
To saw I was worried of the future of our endeavors would have been an understatement, especially after ending up on a street they called Fillet. Every street lamp had been shattered and none gave any light. Yet something managed to catch my eye just ahead. It was on the corner of an intersection. It looked like a creature I had heard about, a beholder, I believe, but this one was stuffed and was a deep purple, a noble color. We approach the stuffed beholder and notice a sign. /Old Xoblob's Shop/
