#+TITLE: 2. A New Life in Trollskull Alley
#+DATE: 2024-02-13T19:41:58-08:00
#+DRAFT: true
#+DESCRIPTION: Keyrie vows to do much better recording these events and details their new life with Evandra and their new manor
#+TYPE: story
#+WEIGHT: 2
#+TAGS[]: story adventures D&D Keyrie
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

While I can almost guarantee that the important details were all there, looking through my entry on how I met Ember and Tracie, I know there was much that was left out. To this end I have decided that I should begin to keep a daily journal of all of my actions. Even those that may be seen as mundane. I apologize for the somewhat rushed and lax presentation of my last adventures. This will be far more detailed. My only hope is that you do not find this too boring.

I will not, however, bore you with a recap of the previous adventures. I will only say that I had decided to stay the night that night at the Yawning Portal. I came to find out that Tracie had also decided to spend her night there as well. In fact, she had a bit of a proposition for me. I guess I had impressed her on some level due to my willingness to help in her performance. She wanted to make me a more permanent part of her act. "Well," I said after she explained this to me, "that's all well and good, but what do /I/ get out of it?"

"Room and board?" Tracie replied.

In my previous life, again, I would have likely just turned this down, but it did sound attractive. I mean especially if they'd be will to comp the last night. I had to admit it was kind of fun to participate in Tracie's little shows, even if they weren't always such a success. I eventually agreed to help her at least one more time.

* A Performance and A New Life
