#+TITLE: 2. A New Life in Trollskull Alley
#+DATE: 2024-02-13T19:41:58-08:00
#+DRAFT: true
#+DESCRIPTION: Keyrie vows to do much better recording these events and details their new life with Evandra and their new manor
#+TYPE: story
#+WEIGHT: 2
#+TAGS[]: story adventures D&D Keyrie
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

While I can almost guarantee that the important details were all there, looking through my entry on how I met Ember and Tracie, I know there was much that was left out. To this end I have decided that I should begin to keep a daily journal of all of my actions. Even those that may be seen as mundane. I apologize for the somewhat rushed and lax presentation of my last adventures. This will be far more detailed. My only hope is that you do not find this too boring.

I will not, however, bore you with a recap of the previous adventures. I will only say that I had decided to stay the night that night at the Yawning Portal. I came to find out that Tracie had also decided to spend her night there as well. In fact, she had a bit of a proposition for me. I guess I had impressed her on some level due to my willingness to help in her performance. She wanted to make me a more permanent part of her act. "Well," I said after she explained this to me, "that's all well and good, but what do /I/ get out of it?"

"Room and board?" Tracie replied.

In my previous life, again, I would have likely just turned this down, but it did sound attractive. I mean especially if they'd be will to comp the last night. I had to admit it was kind of fun to participate in Tracie's little shows, even if they weren't always such a success. I eventually agreed to help her at least one more time.

* A Performance and A New Life
"Ladies and gentlemen!" Tracie starts as I wait patiently for my cue. "Feast your eyes as we experience the universe. Today you will behold and witness something only few have seen. Time and space will bend..." she continues with the prepared monologue. To be honest I didn't pay much attention to it until she said. "This is my assistant, Keyrie!"

If I'm still being honest, I was far to nervous to pay much attention to the performance or even my role in it. I simply did whatever was asked of me and then quickly retreated. I may be of noble birth, but, I was not used to a stage despite my earlier participation. In fact, the first time I was able to ignore my nerves. I didn't know these people and had no idea I would stick around to see any of them again. This was different now. I had accepted that I would be starting a new life and I would probably be sticking around Tracie at least. I only prayed that she still found my participation useful in her act. Of course, I had little idea just what would be in store for me after the performance.

Shortly after we finished we met another woman named Evandra. We were informed that Ember had gone off on some other adventure, but Evandra seemed more than willing to muscle in on our little group. I didn't have any complaints, and Tracie, if she had any, didn't voice them. "Well it seems Ember has also traded her name for yours on the deed," we were told. The deed must have been referring to the property we had been given as reward for our last quest.

"Oh, that," I said. "Were we going to take a look at the property we now somehow own?"

"I suppose we should," replied Tracie.

"I'm guessing she'll be coming with us," I said throwing eyes toward Evandra.

"I suppose she would," said Tracie.

* Trollskull Manor
Before heading out to inspect the property itself, we took out the floor plans that were attached to the deed and other documents. It was not possible to tell exactly what the manor was like just from these drawings, but, it looked pretty nice, at least it did on paper. Aside from a wine and ale cellar, there were four floors. Each floor, aside from the top, was rather spacious. Judging by the drawings and the majority of the first floor being labeled a "taproom" I gathered that the building was once used as a tavern if that was not its original purpose. The second floor was home to a large common room, a den, and two bedroom. The third floor housed a library and study as well as two additional bedrooms. The fourth floor, or attic, housed storage and a final bedroom.

"I like the attic room," I mentioned. It seemed odd to start picking out bedrooms before we even saw the property and it was meant more as a general comment, but it did seem to spark some debate among Tracie and Evandra. Neither seemed interested in the attic room, so I guess that would become mine, but they did go back and forth for a bit before they each picked out rooms on different floors. I suppose there really was plenty of room for us, or so we thought.

We finally decided to head off to the property itself. There I stood, after one fast ride in small carrage of some sort, having many more than second thoughts about the whole idea of owning this property and wishing we had some way of negotiating for gold instead. I mean maybe we could just turn around and sell the delebated old building with its boarded up windows and complete lack of useable furniture, but, alas, it was the best prospect I had at a consist place to live and seemingly only means of staving off starvation and the cold without returning to my father. "Perhaps we can fix the place up," I offered. To which I was suddenly bombered with plans and people and people and plans. Evandra and Reiner laid out all the people we would need to speak to and all the things that needed to be fixed. My head began to spin, or maybe it was just the room. Either way, I couldn't imagine how much this was all going to cost.

It was in the midst of all this that a rat ran by. I wanted to scream, but held my breath instead. Just one more thing to add to the list, I suppose.
