#+TITLE: About Commissions
#+DATE: 2023-08-31T15:20:40-07:00
#+DRAFT: false
#+DESCRIPTION: This page lays out what I can do for you as well as basic expectations I have if you want to commission me to draw for you.
#+TAGS[]: about
#+WEIGHT: 110
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Hewwo peeps and kittens!

I want to do more than just stream games, and for that I need to show off my artistic side! Believe it or not I need your help. If you'd be so kind commission art from me, this would really help the family that adopted me here in your realm and is one way you can support me as well! I have everything you need to know drawn up below. Thankies~ thankies~

* What I am willing to draw
First, I don't mind expanding my skills, so this is not an extensive list of *everything* I will draw. You can think of this more like a list of things I feel comfortable drawing. I'll draw pretty much anything so long as its not in the list of things I won't draw, but I am particularly good at a few things and those things are:
+ Cute girls! Yep I like drawing cute girls, if they are cute enough I /might/ even draw fan-art. By the way, fan-art is legally questionable, I will not handle getting permission to draw other people's characters, that's up to you, and you must let me know you have permissions /before/ I start!
+ Character designs. Similar to the above I can design new characters for you. I will do my very best if that character is a guy, but I am very good with cute girls. If you don't want cute though...probably should look elsewhere to be honest 😅.
+ Still profile pictures. I can even make profile pictures, just don't expect animations.
+ Wallpapers, we'll talk about that, but I am willing to try.
+ Other backgrounds, and "cards", these can be great for streamers. If you need a background to use while you stream, or if you need like a stand-by card, start card, or end card when you stream, [[#headline-3][contact me]], I'll do my best!

Don't forget that you can *always* [[#headline-3][reach out]] and let me know you are interested, and I'll decide if I think I can do a good job and we'll discuss things further, as long as your idea doesn't fall into the categories of things I am not willing to draw below!
* What I am not willing to draw
This is a bit more straightforward and there isn't much negotiating on anything here. Sure, you can always talk about it, but there isn't much chance I will work on a commissions on any of these topics!
+ Violence, I am against my characters getting hurt and will likely not wish this on any other characters. Still, violence can happen and mild violence is usually okay, but anything too extreme and I won't draw it, that's that!
+ Gore. Yep not touching that at all. Anything too gory and that's a complete no-go. If I even get a whiff of it then I'll stop you right there!
+ Sexual content. Yeah I don't draw Hentai, no exceptions. Also if it involves a certain male body part at all, then...yeah not going to happen. /Light/ romance and some questionable things may make it if you ask nicely
+ Anything that targets or marginalizes any group of people regardless of how large or small that groups is. This includes anything that targets racial stereotypes, stereotypes involving one's sexual orientation or gender identity, or any hate toward anyone!
+ Political party logos or anything that could be interpreted as my endorsement of any political group. Sorry just not going there!
* How to contact me if you are interested in a commission
There are a few ways you can contact me for a commission. The easiest way for the two of us is to request a commission using [[https://ko-fi.com/yayoi_chi][my Ko-Fi page's]] commissions tab. If you are a member of my [[https://discord.gg/55eJSatPwh][Discord Community]] you can also commission me through a forum thread there. Reach out in the server for instruction if you need them!
* How will you pay me?
This will fully depend on how you request a commission. If you request through Ko-Fi you will pay the full amount through Ko-Fi as soon as I accept the request. Requests through Discord are paid via Stripe directly. You will first receive a payment link for a deposit. Deposits are typically 10% of the final price, but may vary by type of commission, this will be discussed prior to accepting. You will then pay the /remaining/ balance once you have accepted the final result through another Stripe payment link. In either case *full payment* is needed /before/ final assets will be delivered!
* Cancellations and refunds
Important! Refunds on an agreed deposit will only be granted if work was *never* started. You have a short window, typically 72 hours to cancel a commission to receive a refund on any agreed deposit.

You may, however, cancel a commission at any time before final assets are received. This will cancel any additional payments you agreed to. If you requested the commission through Ko-Fi, this will also result in a refund of any payment collected on Ko-Fi up until that point.

I am very communicative during commissions and often provide many samples and opportunities for you to direct the result of your commission. Please use those opportunities! They are for both of our benefits! I understand, however, that there will be times I am unable to meet expectations. If this occurs before your final payment is received, I will treat this as a cancellation and cancel the final payment. If this occurs after the final payment and assets are received, you agree to destroy all copies of those assets in your possession and I will refund all payments, except agreed deposits. You have 14-days after the final payment is received to request a refund.

Warning! Filing a chargeback on your credit card is *not* an appropriate remedy for any dispute you have on work received! I will treat this as frued and abuse. This will also result in being blacklisted from future commissions.