#+TITLE: About Commissions
#+DATE: 2023-08-31T15:20:40-07:00
#+DRAFT: false
#+DESCRIPTION: This page lays out what I can do for you as well as basic expectations I have if you want to commission me to draw for you.
#+TAGS[]: about
#+WEIGHT: 110
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Hewwo peeps and kittens!

I want to do more than just stream games, and for that I need to show off my artistic side! Believe it or not I need your help. If you'd be so kind commission art from me. This really helps the family that adopted me here on in your realm and is one way you can support me as well! I have everything you need to lay out drawn up below. Thankies~ thankies~

* What I am willing to draw
First, I don't mind expanding my skills, so this is not an extensive list of *everything* I will draw. You can think of this more like a list of things I feel comfortable drawing. I'll draw pretty much anything so long as its not in the list of things I won't draw, but I am particularly good a few things and those things are:
+ Cute girls! Yep I like drawing cute girls, if they are cute enough I /might/ even draw fan-art. By the way, fan-art is legally questionable, I will not handle getting permission to draw other people's characters, that's up to you, and you must let me know you have permissions /before/ I start!
+ Character designs. Similar to the above I can design new characters for you. I will do my very best if that character is a guy, but I am very good with cute girls. If you don't want cute though...probably should look elsewhere to be honest 😅.
+ Still profile pictures. I can even make profile pictures, just don't expect animations.
+ Wallpapers, we'll talk about that, but I am willing to try.
+ Other backgrounds, and "cards", these can be great for streamers. If you need a background to use while you stream, or if you need like a stand-by card, start card, or end card when you stream, [[#headline-3][contact me]], I'll do my best!

Don't forget that you can *always* [[#headline-3][reach out]] and let me know you are interested, and I'll decide if I think I can do a good job and we'll discuss things further, as long as your idea doesn't fall into the categories of things I am not willing to draw below!
* What I am not willing to draw
This is a bit more straightforward and there isn't much negotiating on anything here. Sure, you can always talk about it, but there isn't much chance I will work on a commissions on any of these topics!
+ Violence, I am against my characters getting hurt and will likely not wish this on any other characters. Still, violence can happen and mild violence is usually okay, but anything too extreme and I won't draw it, that's that!
+ Gore. Yep not touching that at all. Anything too gory and that's a complete no-go. If I even get a whiff of it then I'll stop you right there!
+ Sexual content. Yeah I don't draw Hentai, no exceptions. Also if it involves a certain male body part at all, then...yeah not going to happen. /Light/ romance and some questionable things may make it if you ask nicely
+ Anything that targets or marginalizes any group of people regardless of how large or small that groups is. This includes anything that targets racial stereotypes, stereotypes involving one's sexual orientation or gender identity, or any hate toward anyone!
+ Political party logos or anything that could be interpreted as my endorsement of any political group. Sorry just not going there!
* How to contact me if you are interested in a commission
The best bet is to contact me via the right [[https://github.com/yayoi-chi/yaya-world/discussions/categories/commission-requests][GitHub Discussions caregory]]. I have set this up for this exact purpose, however, this does require a GitHub account and I understand that there may be some who do not have and do not want a GitHub account. For that reason I have several other methods you can use. You can also try [[mailto:yayoi_chi@icloud.com?subject=Commission!][e-mailing]] me directly. If that also doesn't suit you, check out my Steam, Mastodon, or Matrix accounts at the bottom of these and every page. We'll discuss things over the DMs there! Whatever is most comfortable for you.
* How will you pay me?
At this time all pricing will be discussed before I start your commission. Once we have decided on a price you are willing to pay, I will send you a payment link for $50 dollars. This is a deposit and it is not refundable. Once you pay that, I will begin work. Depending on how we establish payments you may receive other payment links or one final link for the full price after work is completed. You will be expected to pay that link before the final commission is delivered to you.

All payment is processed through Stripe. Stripe is a third-party payment processor. This is done to ensure protection for both you, as the client, and myself, as the artist. If you have any further questions on payment, we can discuss them, but no other payment processor will be accepted and I do not accept cash, check, or money order.
