#+TITLE: Introduction
#+DATE: 2022-10-09T21:44:28-07:00
#+DRAFT: false
#+DESCRIPTION: My name is Yayoi and I playing games. If you wanna learn more this is the page to do it!
#+TAGS[]: about
#+WEIGHT: 100
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

Hi hi 👋 You can call me Yayoi, all of my friends do. I am 39 years old and I live on the west coast in the USA. Just over two years ago I discovered, or rather, re-discovered the MMO Fiesta Online with friends. I was completely addicted 🤪 If I'm honest, Fiesta Online isn't exactly the best game in the world. Its grindy and it can be hard to solo, but I've made friends and just can't seem to leave them. So I'm still playing, even if I'm only slowly leveling one character 😅, and spending most of my time playing other games.

Over the last year, I learned that I don't really like playing Fiesta Online much. I'm still on every now and then, but I'd rather spend time on other games. However, I have also been a member of several guildes and picked up a few things from them, including some [[{{% ref guides %}}][guides]]. If you're looking for some help then check out those guides or just find me in game. I'd still be happy to help 😁

Though Fiesta is the game play most consistently, I am occasionally on other games, including other MMOs. Some MMOs I like are Final Fantasy XIV, Tower of Fantasy, and Ys Online. Chances are, if you run into a character named Yayoi, YayoiChi, Yayoi Chi, or something similar than I'm playing her! MMOs aren't all I play, I also play other online games like Genshin Impact and Honkai: Star Rail, and I'm a big fan of retro games, like Sonic the Hedgehog and Super Mario Brothers, and JRPGS, my favorite of which is the Xenosaga Saga and Persona series. In fact, I love these games so much, I've added some guides from them!

Also, I make a pretty good friend. If you happen to be on Steam, Mastodon, or Matrix, you can add me. I put links to my profiles on the bottom of the site. You can use these and the e-mail link to get in touch with suggestions or issues with the site as well, though a prefer to hear about page specific problems in their comments, thank you!
