#+TITLE: 第一章: Babyは何処ですか!?
#+DATE: 2022-10-09T21:56:20-07:00
#+DRAFT: true
#+DESCRIPTION: Yayoi has lost BabyYayo! Can her friends help her find her!
#+TAGS[]: story fun friends
#+TYPE: story
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

これは翻訳ではありませんよ！でもこちら英語版です。

While on an ADVENTURE with Yayoi, Baby ended up chasing a sheep. After, finally, catching up to the sheep, Baby gave it a nice pet. It was so fluffy and soft, she couldn't resist. She looked around and found that she was no longer with Yayoi. In fact, Yayoi was no where to be seen. Fortunately a party of friends was out on an ADVENTURE of their own and found her, now in Burning Hill, by herself. The friends ask baby to retrace her steps. Baby leads them back to Sea of Greed, where she last saw Yayoi, but Yayoi had already moved on. However, the group did encounter someone in Sea of Greed.

"You lost your mama again, didn't you?" Touka laughs.

"None of your business, Touka!" Baby hisses.

"What if I told you, I know where she went?"

"I'd tell you to just leave me alone!"

"I could tell you, but it'll cost ya!" Touka said, ignoring Baby's pleas. Baby looked shocked. Of course Touka wouldn't just do /anything/ just to be nice. "How about 1000 gems!"

"That's not fair!" Baby shouted. "Who even has that much!?"

"Okay fine, but I'm not going to make this easy!" Touka responded, "How about I just tell you where some /else/ who saw her went?"

"You should just tell us where Yayoi is?" Baby huffed.

"Where's the fun in that," Touka teased. "Why not go find a pink haired cleric in a forest and see if she knows where your mama is!?"

"Which other forest? There's a *ton* of them!?"

"I don't know, but I know it is not far!"

The group of friends decided to take Baby to the Forest of Mist since it was very close to the Sea of Greed and, mostly by chance, they happened across a certain cleric that definitely fit Touka's description.

"Tama-mama!" Baby cried.

"What's wrong Baby?" Tama asked

"Touka is being mean again...but that's not the real problem."

"We're looking for Yayoi," Narumi, one of the friends, interjects.

"Oh my goodness, you lost Yayoi!"

"Uh huh," whimpered Baby.

"Well, I /did/ see her," Tama explains, "but that was awhile ago. She looked like she was frantically searching for something. Maybe it was you."

"Where was she looking?" inquired Narumi.

"Well, I saw her in Vine Tomb, but I'm sure she was headed for a gate. Not sure which one, but I'm certain she's not in Vine Tomb anymore."

The group begins to deliberate. There are two gates in that area, but they decide to head to Dark Passage. They couldn't find her there, but, since someone mentioned Moonlight Tomb, Narumi decided to head there ahead of everyone. She hears Yayoi shouting for Baby and informs the rest of her friends, who all head over to her.

"I'm so happy you found Baby again!" Yayoi exclaims.

"Yayoi!" Baby cries.

Yayoi explains that she got separated from Baby and, instantly, and frantically started looking for her, eventually ending up in Moonlight Tomb where Narumi, and her friends, found her. She's so happy to see BabyYayo again and vows to keep a better eye on her in the future. We shall see!
