#+TITLE: Daily Quests
#+DATE: 2022-10-09T20:49:16-07:00
#+DRAFT: true
#+DESCRIPTION: Information on Daily Quests and some rewards you can earn for some of them
#+TAGS[]: guide quests
#+TYPE: guide
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY:

At level 95 you can begin doing daily quests. Daily quests reset every
day at 00:00 in-game time, meaning once you turn them in they are done,
but you can pick em up again the next day. From levels 90-125 you can
pick up quests by purchasing a mission scroll from the mission board in
Elderine. Talk to Verylo (who is standing next to the board) to actually
pick up the quest. You will also turn in your quests to him.

** Daily Quests (lvl 90-125)
   :PROPERTIES:
   :CUSTOM_ID: daily-quests-lvl-90-125
   :END:

- Gargoyle Trouble (lvl 90-95)
- What's in the Box (96-100)
- The Fastest Monster (90-100)
- Flapping Noises (90-100)
- Soldiers Grave (101-105)
- Holy Mother of Bears (105-110)
- Lakeside Appiration (101-110)
- King of Condors (101-110)
- A Big Pair of Paws (111-115)
- Witch Hunt (116-120)
- Look at My Horse (111-115)
- Wet Cercuits (116-120)
- As White as Snow (111-120)
- Spirit of the Vale (120-123)
- Banana Hunt (124-125)
- A Furry Gentleman (121-125)
- Quarrel of Brothers (121-125)

It should be noted (again, because no one told me) that mission scroll
cost money. You usually make enough from turning in the quest to cover
the cost of it, and then some, but you need to make that payment
upfront, so watch your money ðŸ˜‰

** Daily Quest Rewards (90-125)
   :PROPERTIES:
   :CUSTOM_ID: daily-quest-rewards-90-125
   :END:
With all the repeatables and regular quests out there, why spend money
to do dailies? That's a really good question, and the answer is....ðŸ¥
Tokens of the Hunter's Union! These coins can be used to purchase
Hunter's Pouches (either Tier 4 for 8 tokens or Tier 5 for 12) These
pouches can contain some very useful items ðŸ¤©

*** Hunter's Pouch (Tier 4)
    :PROPERTIES:
    :CUSTOM_ID: hunters-pouch-tier-4
    :END:

- Hunter's Union Gambeson (this is a permenant outfit ðŸ¤©)
- Shard of Gold Nine (Tier 4, you can use these to purchase Gold Nines
  (Grade 4))
- Hunter's Concotion
- Concentration Increase (Tier 4)
- Strength Increase (Tier 4)
- Dexterity (Tier 4)
- Protection (Tier 4)
- Rama's Potion (lvl 100)
- Hunter's War Rant (150%)(1 Hour)
- Radiant Fragment of Bijou
- Powder of Harmony

*** Hunter's Pouch (Tier 5)
    :PROPERTIES:
    :CUSTOM_ID: hunters-pouch-tier-5
    :END:

- Hunter's Union Gambeson
- Shard of Gold Nine (Tier 5)
- Hunter's Concotion
- Concentration Increase (Tier 5)
- Strength Increase (Tier 5)
- Dexterity (Tier 5)
- Protection (Tier 5)
- Rama's Potion (Lvl 110)
- Hunter's War Rant (150%)(1 Hour)
- Radiant Fragment of Bijou
- Powder of Harmony

For more information on Gold Nine and Fragment of Bijou see my
[[{{% ref enhancement.org %}}][enhancement guide]]

** Daily Quests (130+)
   :PROPERTIES:
   :CUSTOM_ID: daily-quests-130
   :END:
I have just reached this point, so I don't know the all particulars on how these work yet. For now I'll just list the quest, and any prequests you need to unlock them. Don't forget to visit the [[http://fiesta-wiki.com/quests/13][Fiesta Wiki]] if you need help following these quest trains or other unlocking steps. It should also be noted that much of this was written /before/ the 140 cap raise and it appears this quests may be available up until 140, I'll update if I find one that isn't.

- Ursula's Mad Garden (lvl 130-140)
- Enter the Dark Portal (130-140, prequest "Unusual Behavior", both this and the prequest appear to require a special item)
- Mysterious Rock (130-140, You need a mysterious rock, which apparently
  drop in Twilight Void)
- Precious Ore (131-132, this appears to also require a special item)
- The Temple Guard (132-133)
- The Land of the Golden Dragon (132-140)
- Toxic Monsters (132)
- Corrupted Adventurers (133 (also known as ghosts), prequests: 130 "To the Ominous Valley">130 "Ming's Disaster 1">130 "Ming's Disaster 2">131 "Ming's Disaster 4">133 "Ming's Disaster 5", this is /best/ done with a party as these *ghosts* are hard!)
- Most Apish Matter (134-140)
- Omamori Tailsmans (prequests: 130 "A Letter to the Civilized
  Word!">131 "Wild Kjnari"> 132 "Wil Tentaculata">133 "Toxic Kjarni">134
  "Crystallize Toxin")
