#+TITLE: Fairy Cat Vacation
#+DATE: 2026-08-24T10:34:34-07:00
#+DRAFT: false
#+DESCRIPTION:
#+TAGS[]:
#+KEYWORDS[]:
#+SLUG:
#+SUMMARY: I took ten-ish days to go to a different state to see my great-niece. I did miss my kittens, but it was a good trip even though I couldn't even update Genshin on hotel wi-fi.

Ya'llo Kittens!

I am back! As you know I was gone for around 9 to 10 days. I went quite a few states over so I can see my great-niece. Mostly it was a chill vacation. I don't like having a grand itinerary planned and there wasn't really one. The drive days were scheduled, and yes we did drive. The first drive was about 11 hours, but we made it probably more like 13 with stops. The second drive was a little less, probably about 9 hours with stops. We made it to our destination safely though.

One thing! We actually did /not/ take either my car or ya-pa's car. Both of those cars are kind of old and have issues. Nothing major for day-to-day driving, but we didn't really trust them on a long trip. So we rented a car. It was a Jeep, and I did drive it a little bit. I have actually never driven something like an SVU before and I was a little scared at first, but it worked out okay. Turns out not really much different than driving Touya (my Toyota Camry).

Before getting to our last hotel, we met with ya-ma and ya-pa's friend for dinner. This was actually a woman who's children I babysat when I was younger. It was kind of cool to meet her again. Her husband got off work just as we got her back home, so we got I got to see both parents.

The next day was mostly just taking a tour of the town ya-ma and ya-pa lived in. I say them, but I spent a bit of time in this town too. In fact, I recognized some of the houses they took me around too, even though I was pretty young around that time. We actually ended up doing that tour twice, because no one thought to take pictures the first day!

I also did my undergrad, after returning from the Philippines, in a nearby town. A town ya-ma and ya-pa also ended up living in. So, I showed them my apartment (I was a non-traditional-aged student, so I never lived in dorms) and they showed me their house. That was pretty cool too.

After the tours we ended up finally meeting my half-sister (who is not ya-nee), my nephews, their spouses, and, most importantly, my great-niece! We met at a large museum that was about 30 minutes from where we were staying. The next day we went to my nephew's house for brunch, and the third day we went to my other nephews shop and lunch. My sister and my nephews all live in different cities, but in the same state.

After a day of rest, it was time to head back. Our first leg this time was about 12 hours with stops and the second was about 7 with stops. Oh, you remember the couple we met earlier. Well, they told us one of there daughters, whom I had babysat, was up near where we were staying between our return legs. So we met her for breakfast. Sadly, it seems she doesn't remember me babysitting, but she did remember me. At least, she remembered my name.

It was a fun trip, but I am happy to be back. I can't wait for more streams for all of my kittens. In fac, I actually did two streams right after I got back!